### ISSUE TITLE
minibuffer-complete activates ivy in non-ivy completion contexts

### ISSUE THREAD

**Issue by DarwinAwardWinner** [abo-abo/swiper#1050]
When `ivy-mode` is enabled, it seems that `minibuffer-complete` (normally bound to TAB) activates ivy completion even if the current completion call is not using ivy. For example:

```elisp
(ivy-mode 1)
(completing-read-default "Pick: " '("a" "b" "c"))
```

And then pressing TAB will activate ivy, except that the selected item will simply be inserted into the minibuffer, and another RET will be required to exit completion. I'm not sure how this is getting triggered, so I can't tell from reading the code whether this is intentional. But if it's not, I recommend storing the minibuffer depth in the ivy state and making sure ivy features are only active when the result of `(minibuffer-depth)` matches the value in the ivy state. For an example of this, see the `ido-active` function and the `ido-use-mycompletion-depth` variable.

(Note: while the given example is unrealistic, I'm actually encountering the problem with smex, which binds TAB to `minibuffer-complete` during ido completion.)

**Comment by abo-abo** [comment]
I think it's triggered via `completion-in-region-function` which `ivy-mode` sets. That one is called by `minibuffer-complete`.

`completing-read-function` is another (orthogonal) variable that `ivy-mode` sets to make `completing-read` call `ivy-completing-read` instead of `completing-read-default`.

Since these two variables are not connected, the current behavior actually makes sense.

**Comment by DarwinAwardWinner** [comment]
Ok, I guess it makes sense programmatically, but would you say this is intended behavior? It seems kind of confusing to get ivy completion within another non-ivy completion call.

**Comment by abo-abo** [comment]
You get ivy completion because you have `ivy-mode` on. It's an artifact of Emacs completion interfaces that `completing-read-function` and `completion-in-region-function` are separate things.

I'm pretty sure you'd see the same type of stuff when calling `ivy-read` with `helm-mode` on or vice versa. Since there's nothing straightforward to be done here, I close the issue.
