### ISSUE TITLE
Is there an equivalent to helm-follow-mode?

### ISSUE THREAD

**Issue by chaoyi** [abo-abo/swiper#1091]
Is there an equivalent to helm-follow-mode for counsel-* functions?  The ability to preview context for candidates is very useful.

**Comment by basil-conto** [comment]
Ivy calls this behaviour "calling".

If you use `ivy-hydra` you can avail of the `c` binding to the `ivy-toggle-calling` command. When enabled, the currently selected [action](http://oremacs.com/swiper/#actions) is called on every candidate you navigate to. See [here](http://oremacs.com/swiper/#hydra-in-the-minibuffer) for more information on `ivy-hydra`.

Otherwise you can use the non-exiting candidate selection/navigation commands described [here](http://oremacs.com/swiper/#key-bindings-for-multiple-selections-and-actions-keep-minibuffer-open), such as `ivy-call` (`C-M-m`) to "follow" the current candidate.

**Comment by chaoyi** [comment]
Thank you. I should have read the manual.  Works like a charm.  I can use C-M-n & C-M-p to navigate while "calling" the current candidate.

**Comment by therockmandolinist** [comment]
@chaoyi @basil-conto just cause i'm curious, what is this commonly used for?

**Comment by abo-abo** [comment]
@basil-conto Thanks for helping out.
@therockmandolinist I like to use it e.g. for `counsel-git-grep` or `counsel-ag`. Suppose I get 100 matches in 50 files. I don't want to open 50 files while scrolling through, so I skip some files with <kbd>C-n</kbd>. Then I tap <kbd>C-M-n</kbd> for the files I'm interested in opening.

**Comment by basil-conto** [comment]
@therockmandolinist Another use case I imagine is quite popular is previewing candidates of `switch-to-buffer` before selecting one. So far the only thing I've used it for is the following workflow:

1. `C-h f` (`M-x describe-function RET`)
2. Filter candidates to the public API of some library I've forgotten, e.g. `^seq-[^-]` or `^map-[^-]`.
3. Create a new buffer containing this narrowed list: `C-c C-o` (`ivy-occur`)
4. Enable `ivy-calling` by pressing `c` or `M-x ivy-occur-toggle-calling`
5. Browse the documentation of each function in the list by pressing `n`/`p` (`ivy-occur-next-line`/`ivy-occur-previous-line`).

**Comment by dalanicolai** [comment]
Helm also offers [a configuration variable `helm-follow-mode-persistent`](https://github.com/emacs-helm/helm/blob/master/helm.el#L643) so that helm remembers the state of `helm-follow-mode` for different "sources". It would be nice to have the option to have e.g. `ivy-switch-buffer` open with "calling-mode" enabled. It would be even nicer if in "calling-mode" `C-j` would just go to next line (instead of calling `ivy-alt-done`), so that users could switch buffers using `C-j` and `C-k` (followed by RET or `C-l`) only.

If adding the variable is no option, do you have a code suggestion for how to achieve such behavior?

**Comment by basil-conto** [comment]
> If adding the variable is no option

Which variable?  Have you tried setting/binding `ivy-calling` per your preferences?

**Comment by dalanicolai** [comment]
Well yes I have tried to set the `ivy-calling` variable, but probably not in the right way.
Anyway, it has no effect when I try e.g.
```
    (let ((ivy-calling t))
      (print (ivy-switch-buffer))) 
```
also e.g.
```
    (progn (ivy-switch-buffer)
           (setq ivy-calling t))
```
has no effect, neither setting the variable as a buffer local variable.

So I concluded using this variable is non-trivial... at least for me...

**Comment by basil-conto** [comment]
What about the following?

```el
(minibuffer-with-setup-hook
    (lambda () (setq ivy-calling t))
  (ivy-switch-buffer))
```

**Comment by dalanicolai** [comment]
Ah great... that's it!

However, now comes the last bit. But first b.t.w., I think it became clear that I would like to switch buffers using `C-j` and `C-k`, as in evil-mode `C-j` seems more or less equivalent to `o` and `C-k` seems equivalent to `dd` so I never use those (I've added C-tab buffer switch this way to Spacemacs, but now I found that personally I would prefer the keybindings here. It might be a nice suggestion for more users.)

So now the last bit. Although I might be able to find some solution myself, that will probably not be the nicest/cleanest solution. So I hope you have a good suggestion for the following "issue" too:
After evaluating the code snippet you sent me in the last comment (I bind it as a command to `C-j`), Ivy preselects the "other" buffer but without calling it. Therefore, pressing `C-j` once more shows me the before last buffer. So, now I would like to "call" the preselected "other" buffer immediately when opening the ivy-buffer. Can you also suggest a solution for that?

Thanks for your help! Very much appreciated :pray:

**Comment by basil-conto** [comment]
You mean like the following?

```el
(minibuffer-with-setup-hook
      (lambda () (run-at-time nil nil #'ivy-toggle-calling))
    (ivy-switch-buffer))
```

**Comment by dalanicolai** [comment]
Haha, I would indeed not have invented that one... 
As this does not seem to me to be a trivial configuration, I think it would be nice to have similar functionality as provided by the `helm-follow-mode-persistent` variable. But otherwise, for me this works perfectly fine too!

Thanks again for your help!

**Comment by basil-conto** [comment]
> Haha, I would indeed not have invented that one...

Don't worry, it's unencumbered by patents ;).

> I think it would be nice to have similar functionality as provided by the `helm-follow-mode-persistent` variable.

Please submit a new feature request for this so that it's not forgotten. (Although it won't be me working on it any time soon.)

**Comment by dalanicolai** [comment]
Sure will make the request. Indeed with this alternative it is not a priority. Also for most other functions `C-M-n/p` work fine, just that was not really a good option here...
