### ISSUE TITLE
Navigating files with counsel-find-file; want to open folder instead of going to dired when hitting enter

### ISSUE THREAD

**Issue by nosefouratyou** [abo-abo/swiper#1102]
Is there a way to modify counsel-find-file so that it opens a folder instead of going to dired when I hit enter? Right now C-j works for opening the folder, but I was hoping I could use the enter key.

**Comment by abo-abo** [comment]
Press `C-m`.

**Comment by therockmandolinist** [comment]
@nosefouratyou see also: https://github.com/abo-abo/swiper/wiki/ido-style-folder-navigation

**Comment by drrlvn** [comment]
@abo-abo `C-m` still opens dired on the selected directory. The request was to switch `ivy-alt-done` and `ivy-done` on directories in `counsel-find-file`.

**Comment by basil-conto** [comment]
> The request was to switch `ivy-alt-done` and `ivy-done` on directories in `counsel-find-file`.

`counsel-find-file` has its own keymap, namely `counsel-find-file-map`. Does swapping `ivy-alt-done` and `ivy-done` around in `counsel-find-file-map` (as per the linked https://github.com/abo-abo/swiper/wiki/ido-style-folder-navigation) have the desired effect? If not, why not?

**Comment by basil-conto** [comment]
> Press `C-m`.

<kbd>C-m</kbd> is usually the same as <kbd>RET</kbd>; see [`(elisp) Basic Char Syntax`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Basic-Char-Syntax.html).

**Comment by drrlvn** [comment]
@basil-conto that has the desired effect but also has an undesired side-effect - return cannot be used to open a file if the user types the name of a different file (e.g. type `.zsh` and select `.zshrc`, pressing return will open the `.zsh` directory).

This is the reason I asked that the action be switched on directories and not in general.

**Comment by basil-conto** [comment]
@drrlvn Understood, thanks.

**Comment by basil-conto** [comment]
@drrlvn This "side-effect" is not a side-effect, but a bug related to #1494 and #1497. I think this issue can be closed, and your recipe be reported as a new issue. Would you like to do this, or will I?

**Comment by drrlvn** [comment]
@basil-conto I'm not sure what recipe you're referring to. I think this is a real issue and shouldn't be closed.

**Comment by basil-conto** [comment]
@drrlvn 

> I'm not sure what recipe you're referring to.

"When completing a directory `foo` and a file `foobar`, and the file `foobar` is selected, calling `ivy-alt-done` descends into the directory `foo` instead of visiting the file `foobar`." Replace `foo`and `foobar` with `.zsh` and `.zshrc`, respectively.

> I think this is a real issue and shouldn't be closed.

That's what I said. My suggestion is to open a new issue with a more accurate title, because the current issue (`counsel-find-file`/`enter`/`dired`) has almost nothing to do with the aforementioned bug.

**Comment by abo-abo** [comment]
> The bug is about ivy-alt-done and completion of files with a common prefix.

@basil-conto Thanks, please open a new issue. I'm closing this one since the main part of it is solved, and the rest will be in the new issue.

**Comment by phikal** [comment]
>Is there a way to modify counsel-find-file so that it opens a folder instead of going to dired when I hit enter? Right now C-j works for opening the folder, but I was hoping I could use the enter key.

Shouldn't this do it?

```elisp
(define-key ivy-minibuffer-map (kbd "<return>") #'ivy-alt-done)
```

Alternatively, if one used use-package to install ivy, try adding to the macro

```elisp
:bind (:map ivy-minibuffer-map
            ("<return>" . ivy-alt-done))
```

**Comment by basil-conto** [comment]
@phikal Your suggestion has already been discussed, and the issue at hand turned out to involve a separate bug.

Note that <kbd>C-m</kbd> is the same as <kbd>RET</kbd>, which in turn is often the same as <kbd>&lt;return&gt;</kbd> under a GUI. The converse is not true, though: binding <kbd>&lt;return&gt;</kbd> often does not work under a TUI.

As such, it usually recommended to use `"\C-m"`, `"\r"` or `(kbd "RET")` instead of `(kbd "<return>")`. See [`(emacs) Init Rebinding`](https://www.gnu.org/software/emacs/manual/html_node/emacs/Init-Rebinding.html), [`(elisp) Basic Char Syntax`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Basic-Char-Syntax.html), and [`(elisp) Key Sequences`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Sequences.html) for more on this.

**Comment by flyingmachine** [comment]
If anyone came here hoping to learn how to navigate into a file rather than opening it with dired, it appears the default binding is <kbd>C-l</kbd>

**Comment by abo-abo** [comment]
@flyingmachine Are you using some custom config? Because by default the binding <kbd>C-l</kbd> is `recenter-top-bottom`.

**Comment by flyingmachine** [comment]
@abo-abo whoops sorry! I'm using doom emacs 😬

**Comment by med-merchise** [comment]
Check also `ivy-immediate-done` (`C-M-j`)
