### ISSUE TITLE
Swiper all doesn't search buffers without associated file

### ISSUE THREAD

**Issue by bolivier** [abo-abo/swiper#1129]
to reproduce

1. open some file associated buffers
2. create a new buffer with no associated file
3. insert text in file no-file buffer
4. run swiper-all to search for that text

that buffer isn't searched

**Comment by abo-abo** [comment]
This is intentional. It's slow to search through all buffers. See `swiper-all-buffer-p` for a predicate that checks whether the buffer will be included.

If you want, re-define it like this:

```elisp
(defun swiper-all-buffer-p (buffer)
  (with-current-buffer buffer
    (not (eq major-mode 'minibuffer-inactive-mode))))
```

You just need to avoid the problem of `swiper-all` searching its own buffer.

Let me know after a while if it's slow. Maybe it could be made the default.

**Comment by bolivier** [comment]
I haven't had any issues thus far.  One annoying this is that it searches magit buffers and those are almost never what I'm looking for.  Thanks for the pointer to `swiper-all-buffer-p`
