### ISSUE TITLE
counsel-org-tag omits last tag 

### ISSUE THREAD

**Issue by jjlee** [abo-abo/swiper#1166]
Perhaps I'm misunderstanding what these commands are supposed to do, but selecting multiple tags using `counsel-org-tag` appears to omit the last-selected tag for me.

I have reproduced this using a relatively minimal configuration from `emacs -q`, not loading much more than org, ivy and counsel, starting from a buffer with the following content:

```
* foo									:foo:bar:baz:
* blah
```

* Move point to immediately after `* blah` (on that same line)
* `M-x counsel-org-tag`
* `C-M-m`, followed by down arrow
* Repeat last step twice more (now have all three tags selected in minibuffer: `bar, baz, foo`)
* Hit return

Expect:
```
* foo									:foo:bar:baz:
* blah								    :baz:bar:foo:
```

Got:
```
* foo									:foo:bar:baz:
* blah								    :baz:bar:
```

Interestingly, if before the final `<RET>` I hit the up arrow and de-select `baz` with another `C-M-m`, followed by `<RET>`, I get `:baz:foo:bar:`.

**Comment by abo-abo** [comment]
This is expected behavior: the action is to toggle the presence of a tag. So the last <kbd>C-M-m</kbd> toggle the presence of `:baz` to "ON", while the final <kbd>RET</kbd> toggles `:baz` back to "OFF".

Here's what you can press to add 3 tags:

- `C-M-m C-M-n C-n RET`.
- `C-o gjgjd`

I realize that it's quite a mix of bindings to get things done. But it's the best approach we've got so far. Ideas for improvement welcome.
