### ISSUE TITLE
Respect `DEFAULT-FILENAME' argument of `read-file-name'

### ISSUE THREAD

**Issue by Alexander-Shukaev** [abo-abo/swiper#1170]
The `read-file-name` function offers the `DEFAULT-FILENAME` argument.  I would have expected that whenever I run an interactive command that asks to supply a file path and utilizes this argument internally to guess the default (usually displayed in parentheses of the prompt), that file would be selected initially so that I can just tap `RET` and be done with it.  Am I missing some configuration for this to be available or is this not implemented (yet)?

**Comment by Alexander-Shukaev** [comment]
By the way, when using `rgrep`, on the second prompt, I see for example:

```
Search for "..." in files (default *.gz): /.../
```

and `*.gz` is already selected by `ivy` as the default so I can just tap `RET` to continue.  This is good but why the same does not happen for `read-file-name`?

**Comment by Alexander-Shukaev** [comment]
Furthermore, this is also somewhat related to #1142, where in case of `rgrep` there used to be `all` completion candidate and is not there anymore after one of the upgrades.

**Comment by darkfeline** [comment]
I experience this bug as well, this other bug provides a workaround that I would be satisfied with: https://github.com/abo-abo/swiper/issues/1209

**Comment by darkfeline** [comment]
For what it's worth, I've figured out why `read-file-name-default` with `ivy-mode` doesn't respect the default.

``` emacs-lisp
        (if (and default-filename
                 (string-equal val (if (consp insdef) (car insdef) insdef)))
            (setq val default-filename))
        (setq val (substitute-in-file-name val))
```

This fragment in `read-file-name-default` is responsible for replacing the "inserted default" value with the "real" default.

For example, if you're running `read-abbrev-file` from your home directory, `read-file-name-default` inserts `"~/"` into the minibuffer initially.  If you press `RET`, `read-file-name-default` will then replace the inserted default `"~/"` with the "read" default `"~/.emacs.d/abbrev_defs"`.

However, `ivy-mode` makes the `completing-read` return `"/home/bob/"` instead of `"~/"`.  `read-file-name-default` doesn't know that this is actually the initial value and thus doesn't swap it out for the "real" default.

This also means that `read-abbrev-file` will correctly read the default value if you're not inside your home directory, for example if you're in `/`.  `completing-read` would then return `"/"` and `read-file-name-default` would swap it out with the "real" default.

**Comment by abo-abo** [comment]
@darkfeline Thanks for the info. It will take some work to reconcile things:

1. I don't want `ivy-read` to replicate all the quirks of `completing-read-default`.
2. I don't want the "incompatibility" to cause major issues for the users.

If you'd like to help, I'd appreciate a PR in this direction.

**Comment by darkfeline** [comment]
My instinct would be to define a `ivy-read-file-name` to replace `read-file-name-default` when `ivy-mode` is enabled.  The issue here is strictly a mismatch between `ivy-completing-read` API and the `completing-read` API that `read-file-name-default` expects.

However, that API mismatch concerns me.  I don't intend on touching `ivy-read` of course, but perhaps `ivy-completing-read` should be fixed to comply with `completing-read-default`.

**Comment by abo-abo** [comment]
> but perhaps ivy-completing-read should be fixed to comply with completing-read-default.

This is the way to go, I think.

**Comment by nxtr** [comment]
Hey, I took another route with a ivy-immediate-done exit fix, check the PR above

**Comment by nxtr** [comment]
Another related fix to choose the caller default etc. with an empty input exit.
May be radical with a prefix, but this is an explicit use case and previously not possible to enter empty string, as far as I know.
