### ISSUE TITLE
ivy in-buffer completion does not handle immediate-done well

### ISSUE THREAD

**Issue by sooheon** [abo-abo/swiper#1178]
Having written `use-pack` I press `C-M-i` to begin completion.

<img width="304" alt="screen shot 2017-08-31 at 2 22 26 pm" src="https://user-images.githubusercontent.com/302945/29907701-ed8fbf6c-8e57-11e7-9906-30a59813fae5.png">

I type `age` but ivy still does not match `use-package`

<img width="316" alt="screen shot 2017-08-31 at 2 22 32 pm" src="https://user-images.githubusercontent.com/302945/29907703-eda9777c-8e57-11e7-8e7b-51248eb2cfc1.png">

Rather than select a completion or quit with `C-g` (which would make me lose the `age` that I've typed), I `C-M-j` (`ivy-immediate-done`) to just keep what I'd written. But this deletes the prefix to the completion.

<img width="151" alt="screen shot 2017-08-31 at 2 22 39 pm" src="https://user-images.githubusercontent.com/302945/29907702-ed92aba0-8e57-11e7-95fe-07287af0831c.png">

I think the problem is twofold: 
1. The matcher for in-buffer completion should prioritize exact matches
2. C-M-j should insert what I've typed but not delete the prefix

**Comment by abo-abo** [comment]
Thanks, <kbd>C-M-j</kbd> should work now.

I can't do anything about the matcher, as far as I see. The perfect match logic (when the text is exactly one of the candidates, that candidate is selected) won't work here, since your text is `package`, not `use-package`.  A quick fix is to add `$` to your input.

I experimented with one solution, using e.g.

```elisp
(ivy-read "test: "
          :initial-input "use-")
```

But then it's not fuzzy anymore without adding a space, e.g. `use-age` won't match anything (the same thing works properly now).
This isn't a good fix either:

```elisp
(ivy-read "test: "
          :initial-input "use- ")
```

Now it's fuzzy, but the perfect match is out the window, and a space will be added by <kbd>C-M-j</kbd>.

**Comment by sooheon** [comment]
Another fix is to special case the shortest match to always appear at the top. I *think* definitionally the shortest match to a given query ("age") which also shares the prefix ("use-pack") should be the exact match always, no?
