### ISSUE TITLE
ivy-use-selectable-prompt doesn't work when a dynamic collection is empty

### ISSUE THREAD

**Issue by Stebalien** [abo-abo/swiper#1183]
When a dynamic collection is empty, one can't select the input field by enabling `ivy-use-selectable-prompt`.

Also, pressing RET calls the action on the last highlighted item (the item that was being highlighted just before the dynamic collection function returned an empty collection). This is probably related so I figured I'd note it.

**Comment by fabacino** [comment]
Could reproduce the issue with

```elisp
(ivy-read "choose: "
          '(lambda (x)
             (if (> (length x) 2)
                 '()
               '("a" "b" "c")))
          :dynamic-collection t)
```

I will take a look at it.

**Comment by abo-abo** [comment]
@fabacino Sorry, I have to revert your commit: it breaks the smooth redisplay for `:dynamic-collection`. The minibuffer is blinking rapidly as the user types. We'll have to figure out how to fix this.

**Comment by fabacino** [comment]
@abo-abo Thanks for your feedback. I think the problem is that a value of `nil` for `ivy--all-candidates` can mean two different things:

1. The function (sync or async) has returned no candidates.
2. We don't know the candidates yet, because an async function is still running.

I made a new fix, basically checking if there is a running counsel process. If there is, an async function is still running and we don't refresh the minibuffer. If there is none, however, we can safely assume that the function has returned an empty set of candidates. In that case, we update the minibuffer.

https://github.com/fabacino/swiper/commit/b7f27003f0afd15e7013a52811da4be8b76713d1

If you like it, I can PR. The hard-coded process name is not pretty, but there are other references to the counsel package within `ivy.el`, so I figured it is probably ok.

**Comment by abo-abo** [comment]
> If you like it, I can PR. The hard-coded process name is not pretty, but there are other references to the counsel package within ivy.el, so I figured it is probably ok.

Sounds good, please PR. We can refactor the hard-coded stuff later if there's a need.
