### ISSUE TITLE
Feature request: ivy-switch-buffer mru matching

### ISSUE THREAD

**Issue by diamond-lizard** [abo-abo/swiper#1194]
It would be nice if ivy-switch-buffer could have an option to display matching buffers in most-recently-used (mru) order.

For example, if I have three w3m buffers:
```
*w3m*
*w3m*<2>
*w3m*<3>
```
and I type `w` in ivy-switch-buffer, they are displayed sorted as above, in alphanumeric order, regardless of which was most-recently-used.  This feature request is to have an option to have them displayed in most-recently-used order instead.  So, if `*w3m*<2>` was most recently used, it would be at the top of the list, etc.

**Comment by abo-abo** [comment]
There's a package `historian.el` that's supposed to help with that.

**Comment by diamond-lizard** [comment]
Thank you for the pointer.  I've just gone ahead and tried out `historian.el` and it doesn't seem to be doing what I described in my feature request above.

When using `historian.el`, ivy-switch-buffer candidates are sorted in mru order, but I think they were sorted in mru order even without it.  But what I'm looking for is for the candidates to be sorted once I've typed something in to narrow down the results, which is something `historian.el`.

Unfortunately, `historian.el` is virtually undocumented, except to say that it "Persistently store selected minibuffer candidates" and that "ivy-historian.el integrates historian with ivy."  Nowhere in the docs does it say in more detail what it does, how it does it, or if it tries to act at all on ivy candidates during search narrowing, and I'm afraid I don't know enough about ivy internals to be able to guess by looking at the source code myself.  But as far as I can see it's not doing what I need.

**Comment by basil-conto** [comment]
> they are displayed sorted as above, in alphanumeric order, regardless of which was most-recently-used.

If this was true at the time of writing, it no longer is. `ivy-switch-buffer` is ultimately completed by the function `internal-complete-buffer` and has a `nil` entry in `ivy-sort-functions-alist`.

This means that the default sort order is based on `buffer-list`, which is roughly MRU; see [`(elisp) Buffer List`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Buffer-List.html).

The proof is in the pudding:

1. `make plain`
2. <kbd>M-x</kbd>`w3m`<kbd>RET</kbd>
3. <kbd>G</kbd><kbd>RET</kbd><kbd>G</kbd><kbd>RET</kbd>
4. <kbd>C-x</kbd><kbd>b</kbd>

gives the following:

![2018-02-10-140313_1600x900_scrot](https://user-images.githubusercontent.com/9121222/36062795-3e4629a8-0e6b-11e8-8333-70c3977404a5.png)

Either way, I think this issue can be closed because users can customise the sort order by adding an entry for `internal-complete-buffer` in `ivy-sort-functions-alist`.

**Comment by abo-abo** [comment]
Thanks @basil-conto, closing.
