### ISSUE TITLE
How to save the original candidate lines ? 

### ISSUE THREAD

**Issue by hellogdut** [abo-abo/swiper#1273]
Given the following buffer
```
line1
line2
????
line3
```
input `line`，and then press `C-c C-o`  result in 
```
3 candidates:
./*scratch*:1:line1
./*scratch*:2:line2
./*scratch*:3:line3
```

What if I just want to save the original lines ? 
```
line1
line2
line3
```
It's very useful when I have to search several things and finally merge them together to analyze a log file。
Is there a solution?

**Comment by abo-abo** [comment]
Here are the steps:

1. <kbd>R</kbd> to disable `read-only-mode`.
2. `swiper` with input `.*:`.
3. `M-<` to make sure the first line you want is selected.
4. <kbd>M-q</kbd> to start quary-replace
5. <kbd>RET</kbd> to enter "nothing" as replacement.
6. <kbd>!</kbd> to replace all at once, instead of `y/n` on each item.

For a more complex buffer content, you can adjust the regex to `^.*[0-9]:`.

**Comment by hellogdut** [comment]
Thanks for your reply.
But is there anything wrong with my operation？
[Here's a gif ](https://media.giphy.com/media/xUOxf749muqIyZXpok/source.gif)

And is there a faster way to do so without taking 6 steps?

**Comment by abo-abo** [comment]
> error tips "Buffer is read-only"

You need to upgrade to the latest version of the package. The binding <kbd>R</kbd> to disable read-only mode was created only 22 hours ago in my reply to your issue.

> And is there a faster way to do so without taking 6 steps?
> Can we just press something like c-c c-p to make all things done？

It's actually only two steps:

- disable read only mode
- query replace ".*:" with "" using `swiper`

Both of these actions are highly reusable and applicable in many situations. Composing them together makes an function that's less reusable (and less discoverable, since not everyone knows it's bound to <kbd>C-c C-p</kbd>).

I'll see if it's a good idea for `swiper`'s query-replace to disable read-only mode automatically; even less steps.

**Comment by abo-abo** [comment]
OK, after the update it's one step:

    C-s .*: M-q RET !

**Comment by hellogdut** [comment]
It works！
Thanks for your time.
I will try using macro to make it less keystrike.
