### ISSUE TITLE
Ivy-modified-buffer face not carrying over when setting a display transformer.

### ISSUE THREAD

**Issue by dieggsy** [abo-abo/swiper#1292]
I have the following transformer:
```emacs-lisp
(defun d/ivy-dired-transformer (buf)
    (if (get-buffer buf)
        (with-current-buffer buf
          (if (eq major-mode 'dired-mode)
              (concat "Dired: " buf)
            buf))
      buf))
```
Which I set with:
```
(ivy-set-display-transformer 'ivy-switch-buffer 'd/ivy-dired-transformer)
```
This mostly works, except modified buffers are no longer propertized with the `ivy-modified-buffer` face.

**Comment by basil-conto** [comment]
> modified buffers are no longer propertized with the `ivy-modified-buffer` face

This is because you have replaced the default transformer `ivy-switch-buffer-transformer`, which applies the `ivy-modified-buffer` face, with your own function. Your transformer should either wrap or emulate the behaviour of `ivy-switch-buffer-transformer`, e.g.

```el
(defun d/ivy-dired-transformer (str)
  (let ((buf (get-buffer str))
        (str (ivy-switch-buffer-transformer str)))
    (if (and buf (eq (buffer-local-value 'major-mode buf) 'dired-mode))
        (concat "Dired: " str)
      str)))
```

This results in `"Dired: "` potentially being fontified differently than the buffer name it precedes, subject to the value of `ivy-switch-buffer-faces-alist`. If you want the `"Dired: "` prefix to share the same face as the buffer name, you could copy it over, e.g.

```el
(defun d/ivy-dired-transformer (str)
  (let ((buf (get-buffer str))
        (str (ivy-switch-buffer-transformer str)))
    (if (and buf (eq (buffer-local-value 'major-mode buf) 'dired-mode))
        (concat (propertize "Dired: " 'face (get-text-property 0 'face str))
                str)
      str)))
```

or you could mix and match your favourite parts of the aforementioned functions and variables to your liking. See the function `ivy--buffer-list` for how `ivy-switch-buffer-faces-alist` is used.

**Comment by dieggsy** [comment]
@basil-conto awesome. thanks for the info!
