### ISSUE TITLE
Feature request: Don't restore location on C-g

### ISSUE THREAD

**Issue by jwiegley** [abo-abo/swiper#1319]
I'm finding that sometimes, I want to be where I end up, even if the start begins to fail.  `C-g` takes me back to the beginning of the search, so it requires me to look at my search string, and "correct" it until it becomes a successful match for the present location so that I can press RET and stay there.

I'd like both:

 - an option that allows C-g to stay wherever the cursor ends up, successful or not

 - a keybinding for "abort and stay", whose behavior is flipped with "abort" if the above is set

**Comment by manuel-uberti** [comment]
FWIW, I like the second option more.

**Comment by abo-abo** [comment]
Thanks.

> a keybinding for "abort and stay", whose behavior is flipped with "abort" if the above is set

Would be nice, but there are little to none good key bindings left. Especially considering that one of Ivy's key guidelines is that the minibuffer should still behave as a proper editable text field (i.e. don't touch <kbd>C-f</kbd> etc).

I've added a boolean toggle instead, off by default. Even when it's on, you can get the old <kbd>C-g</kbd> either with <kbd>C-k C-g</kbd> or <kbd>C-k RET</kbd>, since the starting line is preselected, and when there's no input Ivy returns back to the preselected candidate.

**Comment by manuel-uberti** [comment]
Superb, thank you.
