### ISSUE TITLE
Add isearch like isearch-yank-word-or-char

### ISSUE THREAD

**Issue by jpmonettas** [abo-abo/swiper#133]
From : 
http://www.gnu.org/software/emacs/manual/html_node/emacs/Isearch-Yank.html#Isearch-Yank

> C-w (isearch-yank-word-or-char) appends the next character or word at point to the search string. This is an easy way to search for another occurrence of the text at point. (The decision of whether to copy a character or a word is heuristic.)

That's something I use all the time when using incremental search for the word at point so that would be nice. Unless there is something better of course.

**Comment by abo-abo** [comment]
There's `ivy-yank-word` that behaves similarly to <kbd>C-w</kbd> of `isearch`.  You can bind it like this:

```elisp
(define-key ivy-minibuffer-map (kbd "C-w") 'ivy-yank-word)
```

It's not bound by default, since I want ivy's minibuffer to behave more like a normal buffer, so <kbd>C-w</kbd> should call `kill-region`.

Additionally, there's an option to search for symbol-at-point with <kbd>C-s M-n</kbd>.  This one's different from `ivy-yank-word`, since it inputs symbol-at-point: you can be in the middle or behind the symbol, not just at the front.

**Comment by jpmonettas** [comment]
Didn't saw that, sorry. Works great for my needs ! Thx!
