### ISSUE TITLE
Suggestion: describe in the documentation how to configure completion by loading terms from a dictionary file

### ISSUE THREAD

**Issue by DmitriR** [abo-abo/swiper#1369]
I could not figure out how to load a dictionary file at start and use (efficiently, as it can be large) that file, and only that file, as the source of completion. Along the lines of https://github.com/auto-complete/auto-complete/blob/master/doc/manual.md#completion-by-dictionary
I am sure it is possible with ivy...

**Comment by basil-conto** [comment]
Is this the same question as https://emacs.stackexchange.com/q/37423/15748 or something different?

**Comment by DmitriR** [comment]
The Stackexchange question is not limited to Ivy.

**Comment by basil-conto** [comment]
I've given a generic answer to that which works well with Ivy.

Unless I'm missing the point, and FWIW, I don't think Ivy needs to document this particular use-case. [Emacs](https://www.gnu.org/software/emacs/manual/html_node/elisp/Completion.html) and [Ivy](http://oremacs.com/swiper/#api) already document their completion APIs and both accept the same completion data types. In fact, you don't even need to worry about the Ivy API. So long as you have `ivy-mode` enabled, it will hook into the standard `completing-read`, `completion-in-region` functions automatically. Beyond that, there are too many sources of candidates and approaches to sourcing them to properly document in the Ivy manual. If anything, i would argue such general examples would be better suited to the Emacs manual, rather than Ivy's.

**Comment by DmitriR** [comment]
The code at https://emacs.stackexchange.com/q/37423/15748  works, thank you. 
Regarding whether this type of information belongs in the Ivy docs: probably not in the core doc set; but in a HOWTO ancillary document, as a demo / example use case? Quite possibly.

**Comment by basil-conto** [comment]
> but in a HOWTO ancillary document

How about the wiki? Anyone is free to edit it AFAIK.
