### ISSUE TITLE
C-M-o and C-M-n not working when browsing for attachment in Gnus

### ISSUE THREAD

**Issue by dinojr** [abo-abo/swiper#1396]
I'm running mml-attach-file in a Message buffer with ivy-mode on. ivy-done on a given candidate in the minibuffer allows to attach the file to the message buffer (although you have to validate the mime-type and attachment type, it would be nice to have it choose silently the default choices). However, nothing happens with C-M-o and C-M-n (ivy-call and ivy-dispatching-call). These would be useful to attach several attachments to a single message in one go.

**Comment by abo-abo** [comment]
I've seen this question before, perhaps I should add it to the FAQ.

Action-related functionality only works when you call `ivy-read` and supply `:action`.  When you call `mml-attach-file`:

- it calls `completing-read-function`,
- which is `ivy-completing-read`,
- which finally calls `ivy-read`.

But there's no `:action` argument passed: Ivy only returns a string in this case, it doesn't know what the caller wants to do with this string.

The reasons above are why there are so many functions in ivy.el and counsel.el that mimic/wrap built in functions, instead of just turning on `ivy-mode` and using the built-ins directly.

Unfortunately, the only way to fix is to rewrite `mml-attach-file` for the interface that allows passing `:action`.

**Comment by dinojr** [comment]
Thanks for clarifying this point.
