### ISSUE TITLE
counsel-git-grep sometimes searches for any text without a prompt

### ISSUE THREAD

**Issue by ryankask** [abo-abo/swiper#1402]
Sometimes when running `counsel-git-grep`, the command appears to search for any text without first prompting:

![2018-01-10 at 15 12](https://user-images.githubusercontent.com/81891/34779652-c1bccc3a-f618-11e7-9a3f-931cec54eabf.png)

I would normally expect to see this prompt:

![2018-01-10 at 15 13](https://user-images.githubusercontent.com/81891/34779674-cf0a4ef8-f618-11e7-912e-ed5b18fa0c25.png)

I see screenshot one when I run the command for the first time after creating a new buffer or switching to an existing one. Subsequent calls prompt as in the second screenshot. It's not always the case though but I haven't noticed a pattern.

**Comment by abo-abo** [comment]
I can't do much without a reproduction scenario.

That said, the idea is:

- if the repo line count is below 20k lines, pipe all lines into Emacs and use Elisp filtering, which is pretty fast in that case.
- otherwise, let `git-grep` do the filtering for each input and send the results to Emacs.

It seems you're getting case 1, even though your repo line count is above 20k lines.

Try evaling `(counsel--gg-count "" t)` to see if the result ever gets messed up.

**Comment by ryankask** [comment]
Thanks for the tip. I used `emacs -Q -l ...` and saw it happening as well.

Running `(counsel--gg-count "" t)` after switching to the buffer returns 6269 at first. Then, after running `consel-git-grep` aain, `(counsel--gg-count "" t)` evaluates to 113081.

**Comment by abo-abo** [comment]
This is the shell command that runs in `counsel--gg-count`:

    git --no-pager grep -c -n --no-color -i -e "" | sed 's/.*:\(.*\)/\1/g' | awk '{s+=$1} END {print s}'

Can you check what it returns for you?

**Comment by ryankask** [comment]
I see that the lower count is the result of the above command running in the buffer's `default-directory`. The higher count is the result of running the command from the root of the repository.

I forgot to mention that I recently upgraded to emacs 26.0.90 so this could be causing problems.

**Comment by abo-abo** [comment]
Thanks, please check if it's fixed for you.

**Comment by ryankask** [comment]
Thanks for your work on this. It didn't seem to solve the issue. `counsel--gg-count` sets `default-directory` to `(ivy-state-directory ivy-last)` and it's this value that changes between the parent directory of the buffer's file and the git repository root path.

**Comment by ryankask** [comment]
@abo-abo Would it be possible to reopen this issue?

**Comment by abo-abo** [comment]
OK. Please provide a minimal repro if you can. I wasn't sure I fixed it last time.

**Comment by ryankask** [comment]
Here is a way to reproduce the issue:

1. Clone a larger git repository `git clone https://github.com/facebook/react.git`
2. Run `make plain`
3. Open $REPO_DIR/react/packages/react/index.js
4. Run `councel-git-grep`
5. Screenshot shows the result for me

![2018-01-12 at 10 11](https://user-images.githubusercontent.com/81891/34870106-0810864a-f781-11e7-8b83-218c60d97bcc.png)

**Comment by dfrib** [comment]
+1 for also seeing this issue, _sporadically_, in a repo with <= 20 000 lines, using Emacs 25.3. Possible a regression as I've only ever run into it after my latest cask packages wipe/reinstall. Currently using `swiper-20180101.1035`.

Setting `counsel-git-grep-skip-counting-lines` to non-`nil` (as show by @ryankask in his linked commit) seems to fix it, though.

```
(use-package counsel
  :after ...
  :bind (...
         ("C-c j" . 'counsel-git-grep)
         ...)
  :init (setq counsel-git-grep-skip-counting-lines t)
  )
```

> ... if the repo line count is below 20k lines, pipe all lines into Emacs and use Elisp filtering, which is pretty fast in that case.

For this case (which should be present for my repo) it would seems as if `(counsel-more-chars 3)` in [`counsel.el`](https://github.com/abo-abo/swiper/blob/ffc34c666c2b214d01e3f722249f45d1672566bb/counsel.el#L1164) does not take precedence in case `counsel-git-grep-skip-counting-lines` is `nil`, as directly upon invocation of `counsel-git-grep` a huge list is dumped in the minibuffer. Maybe [`(split-string (shell-command-to-string cmd) "\n" t)`](https://github.com/abo-abo/swiper/blob/ffc34c666c2b214d01e3f722249f45d1672566bb/counsel.el#L1169) is a participating culprit; overwriting the light-weight fake candidates from `counsel-more-chars` with a (non-lazy?) large list of sub-strings?

**Comment by ideasman42** [comment]
Running into this problem recently too.

Why is `(counsel--gg-count "" t)` needed? - it's taking a long time on 4,090,614 lines of code in our project.
As well as showing part of the results in the output (which is the bug).

Setting `counsel-git-grep-skip-counting-lines` resolves this, but I had to read the code before I knew it existed.

**Comment by abo-abo** [comment]
@ideasman42 
> Setting counsel-git-grep-skip-counting-lines resolves this, but I had to read the code before I knew it existed.

Thanks for the feedback, I removed `counsel-git-grep-skip-counting-lines`; now `du` is used to estimate the repo size - it's much faster.

@ryankask

> clone a larger git repository git clone https://github.com/facebook/react.git

I just tried it and can no longer reproduce. Please test again.

**Comment by ryankask** [comment]
@abo-abo I tried this but it doesn't work on my machine. Please see the screenshots below. 

I'd actually preferred just using `counsel-git-grep-skip-counting-lines`. The issue I was having wasn't related to speed but it was that the lines were being counted from the current directory rather than from the root repository. It had to do with `(ivy-state-directory ivy-last)`. 

![2018-02-01 at 09 20](https://user-images.githubusercontent.com/81891/35670714-310611cc-0731-11e8-8aa1-f66616da3028.png)

![2018-02-01 at 09 21](https://user-images.githubusercontent.com/81891/35670755-4eccf4fa-0731-11e8-923f-24bbd435ab7b.png)

**Comment by abo-abo** [comment]
> I tried this but it doesn't work on my machine. Please see the screenshots below.

I can't reproduce it on Ubuntu 16, Emacs 26.0.90. What are the software versions on your machine?

It looks like the problem is different this time: the async version is used (which is what you wanted), but it crashes for some reason? What are your reproduction steps for the last screenshots? Is it reliably reproduced?

**Comment by ryankask** [comment]
GNU Emacs 26.0.91 (build 1, x86_64-apple-darwin16.7.0, NS appkit-1504.83 Version 10.12.6 (Build 16G1114)) of 2018-01-22

Maybe it's because I have an alias to use human readable sizes?

```
$ which du
du: aliased to du -kh
```

**Comment by basil-conto** [comment]
@ryankask 

> Could it be related to the fact that I have an alias to use human readable sizes?

Unless you are somehow making sure that Emacs defines the alias as well, this shouldn't come into play. You can verify it yourself with `(shell-command-to-string "alias du")`.

**Comment by ryankask** [comment]
This only seems to be happening when I start emacs using `make plain` in the `swiper` directory and the project has over 20,000 lines.

It doesn't happen with my normal configuration. It could be a bug in emacs? I'll try the previous 26 pre release later.

**Comment by basil-conto** [comment]
> It doesn't happen with my normal configuration. It could be a bug in emacs? I'll try the previous 26 pre release later.

If the issue occurs with `make plain` but not when you load your configuration, all that means is there is something in your configuration which ensures your Emacs is in the right state/environment for this feature to work, not necessarily that there is a bug with Emacs (though there could very well be a subtle platform-specific bug in play).

It would help if you could recursively bisect your configuration and identify which settings make this feature work for you. As a wild guess, you may be setting some shell/process environment variables such as exec paths.

**Comment by ssnnoo** [comment]
I run into a problem that (with the git setup we have at work) in the worktree dir this command gives the correct amount of lines
git --no-pager grep -c -n --no-color -i -e "" | sed 's/.*:\(.*\)/\1/g' | awk '{s+=$1} END {print s}'
6945293

However, 

git rev-parse --git-dir

points to:
/home/yyy/reps.git/worktrees/xxx which is small because this is not where the actual source code is, i.e. counsel-git-grep thinks the rep is small ($GIT_DIR is not set).

As a workaround I set 

counsel--git-grep-count-threshold 1

would git rev-parse --show-toplevel be an option instead of --git-dir? Or re-introduce counsel-git-grep-skip-counting-lines (I think it has been removed now).

**Comment by abo-abo** [comment]
The new setting to skip counting lines is:

    (setq counsel-git-grep-count-function (lambda () most-positive-fixnum))

`counsel-git-grep-count-function` is not defined as a `defcustom` with 3 possible choices for behavior.

**Comment by basil-conto** [comment]
Note that Emacs 27 comes with bignum support, so though unlikely, `most-positive-fixnum` is not guaranteed to be larger than any given threshold.

**Comment by Alexander-Shukaev** [comment]
See also mainly #1912 (and maybe #1908).  I keep `counsel--git-grep-count-threshold` as `0` for now because

1.  it ensures the use of `ivy-more-chars` (which may save your ass on a repository with extremely long lines);
2.  it ensures the use of `counsel--async-command` making minibuffer population with candidates non-blocking.

In general, I don't see how could heuristics of `counsel-git-grep-count-function` and `counsel-git-grep-count-function-du` be useful in any case as specialized external search tool such as `git grep` will always be faster at filtering and more responsive if invoked asynchronously from UI experience.  This statements is easily extrapolated to other external search tools (hence #1908).

**Comment by abo-abo** [comment]
Thanks all. `counsel-git-grep` is now always async.

**Comment by Alexander-Shukaev** [comment]
Awesome!  And now if we also apply the same as a041fd6 from #1801, then we could potentially close #1812.

The only missing point would be what I mentioned about application of ranking/sorting algorithm on top of fuzzy search result candidates returned by external search tools in the last [comment](https://github.com/abo-abo/swiper/issues/1812#issuecomment-441403702) to #1812.  But that part is a general feature applicable to all the external search tools (e.g. `rg` and `ag` too), where a041fd6 is either already applied or would apply, so we could have a separate ticket for that feature.

**Comment by abo-abo** [comment]
@Alexander-Shukaev Please PR or open a new issue with a summary of what you want to do. I don't want to dig through several threads to understand what needs to be done.

**Comment by Alexander-Shukaev** [comment]
@abo-abo, my paper assignment is still in progress.  I do these updates mostly to document the development progress and dependencies between different issues, in order to myself follow what's going on and be able to take up the remaining open issues when I get the assignment (if not addressed by some volunteer before that happens).
