### ISSUE TITLE
Enhancement request: Insert a default (symbol at point) when using counsel-rg

### ISSUE THREAD

**Issue by hisnawi** [abo-abo/swiper#1403]
I use mostly counsel-rg for search since it is much faster than ag.
But I am envy of projectile-ag for having a default search (for symbol at point), also helm has this feature.

Is it possible to add this enhancement?

**Comment by abo-abo** [comment]
With any Ivy completion, you can press <kbd>M-n</kbd> to insert symbol at point.

**Comment by hisnawi** [comment]
I know that part, but I am wondering why the default in not inserted automatically instead of the extra key stroke? Seems like a good enhancement.

**Comment by abo-abo** [comment]
It's easy to do, but it's not aligned with the design of Ivy, so it's not included. I think typing <kbd>M-n</kbd> when I need to is a smaller annoyance than having to move my cursor out of the way so that the thing at point is not included in the input.

It's easier with sync collections, like e.g. `counsel-describe-function`. With those, the thing at point is preselected but not made part of the input.

Maybe it's possible to do some :preselect thing for async collections. I'm not sure it's worthwhile.

**Comment by hisnawi** [comment]
The problem I had with M-n is that the last search item doesn't become part of the history.
Meaning, if I did M-n and the term appeared is "test". The next time around when I want to recall "test" as a searched term doing M-p wont bring it back but will bring the term previous to that, also M-n (if the cursor is not at "test") wont bring the term back.

**Comment by abo-abo** [comment]
> The problem I had with M-n is that the last search item doesn't become part of the history.

It won't unless you press <kbd>C-m</kbd> or <kbd>RET</kbd>. Using <kbd>M-n</kbd> is akin to just entering that text.
If you enter `123` as input, the items "1", "12", and "123" should not be added to the history.

**Comment by hisnawi** [comment]
ok thanks

**Comment by codygman** [comment]
I'm moving over to ivy from helm again and was wanting this feature. Maybe I won't find `M-n` too annoying, but it'd be nice if there were a function that does take the current word at point I could bind to something else.

I think doom does this, so maybe I'll just have to grab what they do.
