### ISSUE TITLE
Swiper doesn't handle ! properly

### ISSUE THREAD

**Issue by bbatsov** [abo-abo/swiper#1418]
Just see the screenshot:

![image](https://user-images.githubusercontent.com/103882/35322007-675f08c8-00f1-11e8-999d-ab7636d48cdc.png)

Seems to me `!` should have been considered part of the search string.

**Comment by manuel-uberti** [comment]
It is working for me. Is it happening with `emacs -Q` as well?

**Comment by mookid** [comment]
I can reproduce it.

**Comment by basil-conto** [comment]
This is because the default `ivy--regex-function`, `ivy--regex-plus`, considers everything after `!` to be a negated pattern. See [`(ivy) ivy--regex-plus`](http://oremacs.com/swiper/#ivy--regex-plus).

`ivy--regex-plus` does not, however, understand escaped exclamation marks, such as `"add-class-path\\!`, in the same way that `ivy--regex-ignore-order` does. I don't know whether this is deliberate (@abo-abo ?), but IMO it's a deficiency.

**Comment by mookid** [comment]
One easy fix is just to change `(split-string str "!" t)` to `(split-string str " !" t)`, no?

**Comment by basil-conto** [comment]
@mookid No, that would break established behaviour. I think the following would be better:

```diff
diff --git a/ivy.el b/ivy.el
index 7c6cbb8..2ff7c35 100644
--- a/ivy.el
+++ b/ivy.el
@@ -2358,7 +2358,7 @@ ivy--regex-plus
   "Build a regex sequence from STR.
 Spaces are wild card characters, everything before \"!\" should
 match.  Everything after \"!\" should not match."
-  (let ((parts (split-string str "!" t)))
+  (let ((parts (ivy--split-negation str)))
     (cl-case (length parts)
       (0
        "")
```

but this results in the error `"Unexpected: use only one !"` no longer being shown when the user enters more than one unescaped `!`.
