### ISSUE TITLE
Navigate to TRAMP root?

### ISSUE THREAD

**Issue by angus-g** [abo-abo/swiper#1487]
It's pretty often the case that I'll be editing files via TRAMP (over SSH) and want to access files either in my remote home directory, or the remote root. For both of these situations, `~` and `/` refer to the local host, so they're not useful here. I've been either navigating through the entire directory structure, or re-specifying the entire TRAMP connection string.

Would it make sense to add a magic key like <kbd>:</kbd> for TRAMP paths that'll strip back to the final colon so I can easily edit things in my remote home directory, or add a `/` and access root on the remote?

**Comment by abo-abo** [comment]
> Would it make sense to add a magic key like : for TRAMP paths that'll strip back to the final colon so I can easily edit things in my remote home directory, or add a / and access root on the remote?

This would be useful for sure. Right now, I just press <kbd>DEL</kbd> a bunch of times to get to the remote root. We just need to figure out a magic key that would be usable and wouldn't conflict with anything else.

**Comment by Silex** [comment]
I have both `ivy-magic-tilde` and `ivy-magic-slash-non-match-action` set to nil, and when I `counsel-find-file` and use `/scpx:user@host` then I end up in the file selection part, and there pressing `/ RET` brings me back to the local root instead of the remote root.

I understand this is essentially what this issue is about, and I thought that instead of using a special key why not treat TRAMP a bit differently?

e.g, if `file-remote-p` then don't resolve `/ RET` to the local root, just treat it like `/scpx:user@host:/`.

Can you point to the part where the `/ RET` magic happens? Maybe I can make a PR.

**Comment by abo-abo** [comment]
Thanks, <kbd>~</kbd> and <kbd>//</kbd> now work as you expect on remote. Please test. See also: https://oremacs.com/swiper/#using-tramp.
