### ISSUE TITLE
swiper: inconsistent escaping of "!" and " "

### ISSUE THREAD

**Issue by muirrn** [abo-abo/swiper#1507]
In `ivy--regex-ignore-order` mode, I can use `\  ` (backslash space) or `\!` (backslash exclamation point) in swiper to search for a literal space or exclamation mark, but in other modes you can't. A cursory test showed only `ivy--regex-ignore-order` allows search for literal space, and all except `ivy--regex-fuzzy` allowed literal exclamation point.

**Comment by abo-abo** [comment]
Here's what I've got:

- For `ivy--regex-plus` you need to escape `!`, since it's a separator for negation groups,
- Same for `ivy--regex-ignore-order`,
- For `ivy--regex-fuzzy` you don't need to escape `!`.

**Comment by muirrn** [comment]
What about searching for a literal " "? Is it supposed to work or is it a fluke that ignore-order supports it?

**Comment by abo-abo** [comment]
To search for an 'n' followed by a space, use:

- `ivy--regex-plus`: `n  ` (double space)
- `ivy--regex-ignore-order`: `n\ ` (escaped space)
- `ivy--regex-fuzzy`: `n ` (single space), although it's not the same regex, i.e. `n.* `, not `n ` as above

I realize that it's not very tidy. But users usually prefer a single re-builder and get used to the behavior, as long as you can match everything.  For instance, I always use `ivy--regex-plus`.

I can accept a PR that improves the behavior of re-builders. At the same time, I don't want to spend to much time on `ivy--regex-ignore-order` or `ivy--regex-fuzzy` since I don't use them myself.
Finally, when updating things we should think about how people may be already used to the current behavior.

**Comment by muirrn** [comment]
I see now that the behavior is intentionally different between order and plus, and that each is maintained "separately" by its own camp.
