### ISSUE TITLE
counsel-rg-base-command with suffix?

### ISSUE THREAD

**Issue by tautologyclub** [abo-abo/swiper#1536]
Sometimes when I grep with counsel, the candidate list gets swamped with errors due to permission issues. In other words, stderr gets mixed in with the candidates. At least on Linux, this was pretty easy to solve by hacking counsel.el to append "2> /dev/null" to the grep command. But you can't customize this, so my hack got lost during an update I think. 

Is there a less hacky solution available at the moment?

**Comment by basil-conto** [comment]
Related to #1502.

**Comment by tautologyclub** [comment]
Yeah actually a shell wrapper around rg is very straightforward and elegant. I will post a 'solution' and close

**Comment by basil-conto** [comment]
> a shell wrapper around rg is very straightforward and elegant

What do you mean by "shell wrapper"? The reason I say this issue is related to #1502 is because both pertain to unhandled shell errors, and the incompatibilities between shells in handling them. I used this as an argument in favour of dropping the shell and calling processes directly, but it's been left unclear whether anyone else shares this conviction.
