### ISSUE TITLE
fuzzy matching

### ISSUE THREAD

**Issue by bling** [abo-abo/swiper#154]
i see that there's some fuzzy matching support available in `ivy` but it's not being exposed via custom variables yet.  are there any plans to add more support for this, or perhaps integration with flx?  thanks.

**Comment by abo-abo** [comment]
I haven't looked at `flx` implementation yet. If it's easy to integrate, I'm all for it. But it might take time.  I'm not too eager to start though, since `flx` is slow for large collections.

Currently, `counsel-M-x` uses `smex` for sorting (basically, instead of `flx`). It might be interesting to extend this approach to all commands that use `ivy-read`.

> not being exposed via custom variables yet

The options now are:

```elisp
(setq ivy--regex-function 'ivy--regex-plus)
;; or
(setq ivy--regex-function 'ivy--regex-fuzzy)
;; or
(setq ivy--regex-function 'ivy--regex-ignore-order)
```

The interface is simple enough that you can just write your own function and set `ivy--regex-function` to that.  I could change `defvar ivy--regex-function` to `defcustom ivy-regex-function` at some point. That would mean committing to an interface, which I was reluctant to do before, since I wanted flexibility.  But this interface seems to work quite well, maybe I'll make it permanent in the next release.

It's also possible to toggle between `-plus` (the default) and `-fuzzy` with <kbd>C-o m</kbd>.

**Comment by bling** [comment]
sounds good.  i didn't want to make any assumptions since `--` typically means "private".  also, i needed to add to following to my config:

    (setq ivy-re-builders-alist '((t . ivy--regex-fuzzy)))

currently `ivy--regex-function` always gets overwritten inside `ivy-read` so the only way to get it persistent is to make the above change.

**Comment by abo-abo** [comment]
> currently ivy--regex-function always gets overwritten inside ivy-read so the only way to get it persistent is to make the above change.

And that's exactly the recommended way to customize this currently. I'll rename to `ivy-regex-fuzzy` in an upcoming release.  But not `ivy--regex-function` - that thing is a private implementation detail. In fact, you can toggle `ivy--regex-function` while in minibuffer with <kbd>C-o m</kbd>.

**Comment by bling** [comment]
cool, i'll keep my eyes open.  i've been using it for a while now and smex is doing the job just fine.
