### ISSUE TITLE
RFE: swiper - add highlighting of regex matched/saved groups

### ISSUE THREAD

**Issue by jgubmll** [abo-abo/swiper#1550]
The regex builder has a really helpful feature where, as well as highlighting matches in the current buffer for the regex, if that regex contains saved groups (i.e. stuff between \(...\) which can be referenced in a replace string using \1 etc), those are also highlighted in the matches, in a different face to how the whole match is highlighted.

At the moment, swiper highlights fully matched strings, but gives no visual indication of what's matched in each saved group. It would be super nice if that could be added.

**Comment by basil-conto** [comment]
After a quick glance at the source, it looks like the reason the minibuffer candidates are not highlighted for any regexp builder other than `ivy--regex-plus` is that `swiper` hard-codes `swiper--re-builder` as the `:re-builder` for its session, without taking `ivy-highlight-functions-alist` into account. This should be relatively straight forward to hack around: users can add an entry for `swiper--re-builder` in `ivy-highlight-functions-alist`, or, even better, `swiper--ivy` can temporarily extend the alist for its purpose. The latter is a simple but still ugly solution; maybe I'm missing a better "monkey patch", but AFAICT the whole regexp-builder/highlight-function system has to be rethought a little for a more elegant solution.

As for the buffer overlays, I think they are not highlighted because `swiper--update-input-ivy` only considers the first regexp returned by `ivy--regex-function` for highlighting, even when this is a multi-item alist like `(("foo" . t) ("bar". t))`. The reason this limitation is not seen with the default regexp builder is because it returns all matching substrings as a single regexp, e.g. `(("\\(foo\\).*?\\(bar\\)" . t))`.

**Comment by jonathanunderwood** [comment]
I am the same user as @jgubmll - I accidentally filed this RFE with my work account. I have to admit, I am struggling to follow everything you write, as I have no familiarity with the innards of swiper/ivy etc.

I am using swiper as configured with spacemacs - it looks like that doesn't come configured to use the -plus builder - it behaves like your second example.

To answer your earlier question, I'd like to see the saved regex groups highlighted in both the original buffer and the candidate list.

To give you a better example of what I mean, start the regexp-builder with swiper.el opened in a buffer and
1. Switch to "string" syntax (M-x reb-change-syntax)
2. Enter: `"GNU General \([A-Za-z]+\) \(License\)"` in the regexp-builder.
![screenshot from 2018-05-02 22-18-40](https://user-images.githubusercontent.com/992114/39549743-e2e1e80a-4e56-11e8-8cb1-a1262feee647.png)

**Comment by basil-conto** [comment]
> I'd like to see the saved regex groups highlighted in both the original buffer and the candidate list.

Sounds like you want the highlighting that [`ivy--regex-plus`](http://oremacs.com/swiper/#ivy--regex-plus) (the default regexp builder) currently provides, assuming you're happy with its in-order processing of space-delimited search strings (i.e. `foo bar` becomes `\\(foo\\).*?\\(bar\\)`).

If so, then perhaps you should raise the issue/question with Spacemacs as to how to go about reverting to the default regexp builder. Otherwise, we'll both have to wait until the highlighting of [`ivy--regex-ignore-order`](http://oremacs.com/swiper/#ivy--regex-ignore-order) improves.

**Comment by jonathanunderwood** [comment]
Ok, I switched to ivy--regex-plus, but still I don't see saved groups highlighted in the matched text. I'll dig some more, and I presume this is a spacemacs config problem, but any pointers you might have would be great.

**Comment by abo-abo** [comment]
> but any pointers you might have would be great.

Everything separated by a space is a group, no need for extra `\(...\)` parens:
![swiper-capture-group](https://user-images.githubusercontent.com/2937359/39677306-063fd99a-5179-11e8-990f-1e6b11cc3875.png)
