### ISSUE TITLE
binding ivy-resome in ivy-minibuffer-map failed

### ISSUE THREAD

**Issue by zw963** [abo-abo/swiper#1589]
following definition:

(define-key ivy-minibuffer-map [(control r)] 'ivy-resume)

what i expect is: `Ctrl+S`, and then `Ctrl+R`, will return to previous result.

But this not work.

**Comment by basil-conto** [comment]
You don't need to be within a current completion session; you can just call `ivy-resume` directly, and that will resume the previous session. In other words, try typing just <kbd>C-r</kbd> on its own, without first typing <kbd>C-s</kbd>.

**Comment by zw963** [comment]
@basil-conto 

> You don't need to be within a current completion session; you can just call ivy-resume directly, and that will resume the previous session. In other words, try typing just C-r on its own, without first typing C-s.

I understood this, I just use `C-s` as a prefix to run other ivy relative command, because `C-r`
I binding to other useful binding.

if can support that, or offer a function like `helm-run-after-exit` as following, will very good.

```el
(defun helm-quit-and-helm-git-grep-at-point ()
  "Drop into `helm-git-grep-at-point' from `helm'."
  (interactive)
  (with-helm-alive-p
    ;; will exit helm imediately, and then run  helm-git-grep-at-point
    (helm-run-after-exit 'helm-git-grep-at-point)))
```

Thanks

**Comment by basil-conto** [comment]
> if can support that

Support what? I'm not sure what you're asking, can you please elaborate in more details?

> or offer a function like `helm-run-after-exit`

I think the closest Ivy has to that is `ivy-quit-and-run`.

**Comment by zw963** [comment]
Not work. thanks

```cl
(defun ivy-quit-and-run-ivy-resume ()
  "Drop into `ivy-resume' from `ivy'."
  (interactive)
  (ivy-quit-and-run (ivy-resume)))

(define-key ivy-minibuffer-map [(control r)] 'ivy-quit-and-run-ivy-resume)
```

**Comment by basil-conto** [comment]
I'm sorry, but I can't help you any further if you don't explain in more details what you're trying to achieve. "Not work" does not help anyone help you. Please explain in detail what you want to type, what you want to happen, and why it isn't working.

If you're trying to get `ivy-resume` to resume the second-to-last completion session, rather than the last session, then I don't think Ivy currently supports this. Perhaps @abo-abo can shine some more light on this.

**Comment by zw963** [comment]
### What I want

`Ctrl + S` run `swiper`, and then `Ctrl + R` run `ivy-resume`.

I am not binding ivy-resume directly to some direct binding, because
most binding is used by other emacs command.

### Problem

`Ctrl +S` and then `Ctrl + R`, run `ivy-quit-and-run-ivy-resume`, but, `ivy-resume` is not invoke success.

**Comment by basil-conto** [comment]
Thanks for exlaining, I understand what you're trying to do now.

The problem with this approach is that calling `swiper` before `ivy-resume` modifies `ivy-last`, which is where the information for the last completion session is stored. In other words, the following:

```el
(defun my-quit-and-ivy-resume ()
  "Quit the current completion session and call `ivy-resume'."
  (interactive)
  (ivy-quit-and-run (ivy-resume)))

(with-eval-after-load 'ivy
  (define-key ivy-minibuffer-map "\C-r" #'my-quit-and-ivy-resume))
```

works, but what it does is restore the last `swiper` session which is the same session as the one it was called from. In order to restore the last completion session, you need to save the value of `ivy-last` somewhere before `swiper` overwrites it:

```el
(defvar my-ivy-last nil
  "Store value of `ivy-last' before calling `swiper' or nil.")

(define-advice swiper (:before (&rest _) my-ivy-save-last)
  "Save last `ivy-last' as `my-ivy-last'."
  (setq my-ivy-last ivy-last))

(defun my-quit-swiper-resume-ivy ()
  "Quit `swiper' and call `ivy-resume'."
  (interactive)
  (swiper--cleanup)
  (setq ivy-last my-ivy-last)
  (ivy-quit-and-run (ivy-resume)))

(with-eval-after-load 'swiper
  (define-key swiper-map "\C-r" #'my-quit-swiper-resume-ivy))
```

**Comment by zw963** [comment]
Thank you for you explain, i will try it later, maybe, this is not a expected righting way to this. ; )
