### ISSUE TITLE
Compensate ivy height for variable height unicode fonts

### ISSUE THREAD

**Issue by kaushalmodi** [abo-abo/swiper#161]
The default way using which ivy adjusts the minibuffer height works fine for everything except when dealing with unicode fonts.

Some unicode fonts have more character height than the default and thus situations like below arise when using `counsel-unicode-char`:

- Even when I am on the last element, it is displayed partially, because some unicode characters are taller than the default.
- For instance, it can be seen that the Cyrillic Capital Letter Omega is taller than others.
- So I can never see what that last character looks like or what it is (*It's easy to guess that in this particular example though*.).

![clipboard01](https://cloud.githubusercontent.com/assets/3578197/8320173/70446c76-19e5-11e5-9943-e008158b6b47.png)

For such cases, can you add a buffer of 1 or 2 lines at the very end?

**Comment by abo-abo** [comment]
I'm not seeing your problem in my config, since I just have DejaVu Sans Mono for everything.  I solved a similar problem in #151 by getting rid of the custom string height that came from faces.

A similar approach probably won't apply here, since you don't want to have a single font in the minibuffer.  Adding an extra line is easy, what's hard is to calculate the pixel height of these 9 lines and check if it's more than the standard minibuffer height. I don't know an API for that.  In case you do, please share.
