### ISSUE TITLE
The default in ivy-sort-functions-alist should be removed

### ISSUE THREAD

**Issue by tarsius** [abo-abo/swiper#1611]
#1561 3689c8f36dc55494b2eaa7f4c4404114d02c7c9f fixed a bug that prevented the default/fallback sorting function to be used. Now that the the default **is** used, I think it should be removed by ... uhm ... default. Users could then still set the default if they think that that is a good idea. The built-in completion mechanism doesn't sort by default and Ivy shouldn't do so either.

**Comment by tarsius** [comment]
Actually built-in completion does sort the candidates by default. However it does not do so if the candidates actually are a function. Since aa5f098ab4c3e037318482355981e551b3c926f9 Magit relies on that behavior.

**Comment by basil-conto** [comment]
> [...] if the candidates are wrapped as a function

...and the default `display-sort-function` metadata entry is changed, right?

**Comment by basil-conto** [comment]
Any further thoughts on this?

FWIW, I agree that the order of a given collection shouldn't be changed by default. This behaviour is less obtrusive, more efficient, and equally customisable.

**Comment by abo-abo** [comment]
@tarsius It's not clear to me what the use case is. Please clarify.

I prefer the way it is now because it's more intuitive:

```elisp
;; makes sense
(ivy-with
 '(ivy-read "test:" '("b" "a" "c")
   :sort t)
 "C-m")
;; => "a"

;; hmm, a sort was requested but nothing was done
(let ((ivy-sort-functions-alist nil))
  (ivy-with
   '(ivy-read "test:" '("b" "a" "c")
     :sort t)
   "C-m"))
;; => "b"
```

**Comment by basil-conto** [comment]
The only reason the second example seems unintuitive is because the role of the `:sort` keyword, as part of the `ivy-read` API, is redundant in the presence of the `ivy-sort-functions-alist` variable. The latter generalises the former. When would you ever want to deliberately specify `:sort nil`, when both programmers and users can use `ivy-sort-functions-alist` to determine when and how to sort?

So, if the only reason you think `ivy-sort-functions-alist` should sort everything by default, given a corresponding `:sort t` argument, is because that's what one would expect upon seeing `:sort t`, then I would suggest obsoleting the keyword in the API and just silently ignoring it.

Unless I'm missing some purpose it serves that isn't covered by `ivy-sort-functions-alist`?

**Comment by abo-abo** [comment]
> Unless I'm missing some purpose it serves that isn't covered by ivy-sort-functions-alist?

Maybe deprecating is the way to go, the current state of things is due to an emerging (as opposed to up-front) design. The idea is currently:

- `:sort` is nil by default
- each command decides if it makes sense to turn it on, it really doesn't make sense for commands where candidates have in-buffer order
- the user can customize the sorting for all commands that have it turned on at once. Due to generality, only a few options make sense here: none, `string<`, `string>`, maybe also in combination with case sensitivity.

Suppose we deprecate `:sort` and immediately make it do nothing and use only `ivy-sort-functions-alist`. Then this default value is the only viable option:

```elisp
(defcustom ivy-sort-functions-alist
  '((read-file-name-internal . ivy-sort-file-function-default)
    (t . nil)))
```

And then we go through every `ivy-read` call that has `:sort t` and add an entry to `ivy-sort-functions-alist` with `ivy-string<`. And you could still customize all-at-once by advising `ivy-string<`. OK, I'm fine with a change like that.

Does everyone agree? Any suggestions?

PS. It just occurred to me that if we do things as above, any value for default except `(t . nil)` doesn't make sense anymore (would break e.g. `counsel-outline`). So in addition we would need to go through every `ivy-read` call that doesn't have `:sort t` and customize `ivy-sort-functions-alist` with `nil`. And that just might be too much effort.

**Comment by basil-conto** [comment]
> Does everyone agree?

+1

> Any suggestions?

I'm not sure through what channels news are usually announced, but such an API change, backward-compatible though it is, would be worth announcing prominently.

> we would need to go through every `ivy-read` call that doesn't have `:sort t` and customize `ivy-sort-functions-alist` with `nil`

Not if the default fallback in `ivy-sort-functions-alist` is set to `(t . nil)`, which, as you say, follows logically from the proposed plan.

Unless I'm missing something, the only reason we'd want to specify a `nil` sort function for all existing `:sort nil` functions is to avoid changing the sort order of users who have added a setting to `ivy-sort-functions-alist` for such an unsortable function. In other words, I think such a change would be exceedingly conservative.

**Comment by tarsius** [comment]
I can't really wrap my mind around it and there is a kid walking around in circles behind me, banging sticks together and talking to them, so I don't think I will be able to concentrate enough anytime soon to do so.

So my advice is simply to not rush deprecating `:sort` and to keep in mind that the default for completing functions defined with `ivy-read` should maybe differ from that of functions that are being replaced due to `ivy-mode`. For the latter the default should always be to do the same that would have happened if `ivy-mode` has not been enabled.

**Comment by tarsius** [comment]
2d840b8be54fbc887a6b2a6a8178d27786d1421f addresses the issue for me, by dropping the `:sort t` from `ivy-completing-read` without replacing that with a call to `ivy-configure`.

**Comment by abo-abo** [comment]
@tarsius Thanks.

**Comment by holgerschurig** [comment]
Okay, but for me now counsel-describe-function doesn't behave as I want it.

Background: when I type in a partial match, I want to have the smallest match near the top. So I type in "gen def" and want "general-define-key" above "general-evil-define-key". So achive this, I made a this function, a bit similar to ivy-string<:

```
  (defun my-ivy-sort (X Y)
    "Similar to ivy-string<, but also takes the length of the string into consideration."
    (let ((xx (if (consp X) (car X) X))
          (yy (if (consp Y) (car Y) Y)))
      (or (< (length xx) (length yy))
          (and (= (length xx) (length yy)) (string< xx yy)))))
```

and changed ivy-sort-functions-alist to only contain `( (t . my-ivy-sort) )`. And still I get this isn't honored. When I add a `:sort t` clause to the call of ivy-read in counsel-describe-function, then I get the expected behavior.

So the assumption that a list is already sorted is valid only in such cases as ivy-sort-functions-alist gives back a standard comparator predicate, but not if the predicate get's a little bit funky as in my case.

          ))

**Comment by basil-conto** [comment]
@holgerschurig I can't reproduce what you report with latest Ivy:

1. `make plain` (like `emacs -Q` but also loads Ivy and Counsel)
2. <kbd>C-h</kbd><kbd>f</kbd> (this calls `counsel-describe-function`)
3. `defa`

This results in the following sort order:

![2020-05-01-191152_1600x900_scrot](https://user-images.githubusercontent.com/9121222/80830137-5f897300-8be0-11ea-866b-e63870441dce.png)

Whereas after evaluating the following:

```el
(defun my-ivy-sort (x y)
  "Like `ivy-string<', but also consider length."
  (let ((xx (if (consp x) (car x) x))
	(yy (if (consp y) (car y) y)))
    (cond ((< (length xx) (length yy)))
          ((= (length xx) (length yy))
           (string< xx yy)))))

(setq ivy-sort-functions-alist '((t . my-ivy-sort)))
```

I get the following sort order:

![2020-05-01-191604_1600x900_scrot](https://user-images.githubusercontent.com/9121222/80830361-bbec9280-8be0-11ea-9c4f-7dd42814b96a.png)

So as far as I can tell, Ivy and Counsel are behaving as intended here. If the sort order shown in the second screenshot is not the one you desire, then the issue lies with `my-ivy-sort`, not Ivy. If you have any other issues with how Ivy does sorting, please open a new issue.
