### ISSUE TITLE
ivy-set-display-transformer doesn't work for counsel-describe-ivy

### ISSUE THREAD

**Issue by casouri** [abo-abo/swiper#1619]
I executed 
```lisp
(ivy-set-display-transformer 'counsel-describe-face (lambda (str) (format "%s modified" str)))
```

then called `counsel-describe-face`, but the candidates are not modified. Did I miss anything?

**Comment by basil-conto** [comment]
This is because `ivy-read` looks up the display transformer based (effectively) only on its `:caller` argument, which `counsel-describe-face` fails to specify. I have added the `:caller` argument for `counsel-describe-face` in #1620, but the question of whether `ivy-read` should also consult `this-command` remains.

**Comment by basil-conto** [comment]
> the question of whether ivy-read should also consult this-command remains

This question is addressed by #1621.

**Comment by casouri** [comment]
Cool! Thanks. :smile:

**Comment by basil-conto** [comment]
You could have waited until #1620 and/or #1621 were merged before closing this issue. :)

**Comment by casouri** [comment]
I’m just afraid that I will forgot and leave this open. I really don’t like stacking issues like what they got in spacemacs repo.

But it’s right to remain open until the issue is proven to be fixed. I agree.

**Comment by casouri** [comment]
Thanks again!
