### ISSUE TITLE
Unable to use "\s" escape with ivy--regex-plus

### ISSUE THREAD

**Issue by snake-scaly** [abo-abo/swiper#1626]
I'm trying to search my TAGS for `/class\s+Foo/`. However:

1. If I type `class Foo` I find everything that derives from Foo, e.g. `class Bar : public Foo`.
2. If I type `class\sFoo` it seem to work exactly as `class Foo`.
3. If I type `class\\sFoo` nothing is found.

This feels like a bug, and it probably is. I would expect 2 or 3 to work as a regular expression `/class\sFoo/`.

**Comment by basil-conto** [comment]
Unless I've misunderstood something, what you describe is expected behaviour. What is your value of `ivy-re-builders-alist`?

If you are using the default [`ivy--regex-plus`](http://oremacs.com/swiper/#ivy--regex-plus) regexp builder, then to match N spaces, you need to input N+1 spaces; so try searching for `class  Foo`, where `class` and `Foo` are separated by two literal spaces.

Alternatively, if you are using [`ivy--regex-ignore-order`](http://oremacs.com/swiper/#ivy--regex-ignore-order), then you need to escape spaces with a backlash; so try searching for `class\ Foo`.

See [`(ivy) Completion Styles`](http://oremacs.com/swiper/#completion-styles) for details on this.

Note that `\s` does not mean anything special in Elisp regexps; see [`(elisp) Regexp Backslash`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Regexp-Backslash.html). Rather, `?\s` stands for the space character, ASCII 0x20.

**Comment by snake-scaly** [comment]
Indeed it's my bad! I didn't know spaces were represented differently in Elisp regexps. What I really wanted was `class\s-+Foo`, that is, I wanted to match the `\s-` character class, or "syntax" in Elisp lingo. which works as expected. Thanks for pointing me to the right documentation! I'm closing this issue now.

You're also correct that I could do almost the same thing by putting two spaces instead of one, like `class<SPC><SPC>+Foo`. Which probably would be more practical in my case. Thanks again!
