### ISSUE TITLE
Documentation request: show how to show ivy-read for new things

### ISSUE THREAD

**Issue by brabalan** [abo-abo/swiper#163]
I’m reading this article http://kitchingroup.cheme.cmu.edu/blog/2015/06/25/Integrating-swish-e-and-Emacs/ and I would like to implement something similar, using ivy instead of helm. Looking at the counsel source it seems to be possible, but it would be great to have a recipe to follow to do so.

**Comment by abo-abo** [comment]
I've looked at the source code in the article and wrote something roughly equivalent.  Although `swish-e` seems to fail very of often (with a core dump) on Ubuntu.

```elisp
(defun counsel--swish-candidates (query)
  "Return a list of string matching QUERY."
  (let* ((idx-file "/home/oleh/Dropbox/source/lanyon/_site/index.swish-e")
         (result (shell-command-to-string
                  (format "swish-e -f %s -x \"%%r\t%%p\n\" -w %s"
                          idx-file
                          (shell-quote-argument query)))))
    (setq ivy--all-candidates (split-string result "\n" t))))

(defun counsel-swish-e (&optional query)
  "Run a swish-e QUERY."
  (interactive)
  (setq query (or query ""))
  (ivy-read "Swish-e: " nil
            :dynamic-collection #'counsel--swish-candidates
            :initial-input query
            :action (lambda (x)
                      (message x))))
```

This template is far from perfect. I'll try to improve it when I have some time.  I think at least the result of `counsel--swish-candidates` should be taken care of automatically, so that you don't have to touch `ivy--all-candidates`. And also the collection / `:dynamic-collection` split may not be great.

**Comment by brabalan** [comment]
Thanks, this is most useful!

**Comment by abo-abo** [comment]
I update this with the current prefferred way to deal with async shell processes:

```elisp
(defvar counsel-locate-history nil
  "History for `counsel-locate'.")

(defcustom counsel-locate-options (if (eq system-type 'darwin)
                                      '("-i")
                                    '("-i" "--regex"))
  "Command line options for `locate`."
  :group 'ivy
  :type  '(repeat string))

(defun counsel-locate-function (str &rest _u)
  (if (< (length str) 3)
      (counsel-more-chars 3)
    (counsel--async-command
     (format "locate %s '%s'"
             (mapconcat #'identity counsel-locate-options " ")
             (counsel-unquote-regex-parens
              (ivy--regex str))))
    '("" "working...")))

(defun counsel-locate ()
  "Call locate shell command."
  (interactive)
  (ivy-read "Locate: " #'counsel-locate-function
            :dynamic-collection t
            :history 'counsel-locate-history
            :action (lambda (file)
                      (when file
                        (find-file file)))
            :unwind #'counsel-delete-process))
```

Some notes/differences from the previous code:

- It's always good to add own history variable.
- Use `(counsel-more-chars 3)` to not start any process unless there are at least 3 characters of input.
- Use `counsel-unquote-regex-parens` as a bridge between Elisp/PCRE regex
- Put the collection function in the usual place, `:dynamic-collection` is now a boolean toggle.
- Use `counsel--async-command` rather than `shell-command-to-string`. This way it's possible to interrupt the process when the input is changed rather than wait for it to complete.
- Use `:unwind #'counsel-delete-process` so that <kbd>C-g</kbd> in the minibuffer will also stop a long running async process.

**Comment by brabalan** [comment]
Very nice, this is most useful, thank you.
