### ISSUE TITLE
Counsel/:catch: Symbol’s value as variable is void: ivy-height-alist

### ISSUE THREAD

**Issue by hfehrmann** [abo-abo/swiper#1653]
The following code fails in both 24.5 and 25.1 with the error in the title. This error doesn't allow to run ivy nor swiper. This exact file was executed in my previous PC and no error where presented.
```
;; Doesnt show init message
(setq inhibit-startup-message t)
(tool-bar-mode -1)

;; Font size
(set-face-attribute 'default nil :height 90)

;; Window size
(when window-system
  (set-frame-position (selected-frame) 0 0)
  (set-frame-size (selected-frame) 210 50))
;;(add-to-list 'default-frame-alist '(height . 50))
;;(add-to-list 'default-frame-alist '(width . 210))

(require 'package)
(setq package-enable-at-startup nil)
(add-to-list 'package-archives
	     '("melpa" . "https://melpa.org/packages/"))

(package-initialize)

;; Bootstrap `use-package'
(unless (package-installed-p 'use-package)
	(package-refresh-contents)
	(package-install 'use-package))

(use-package try
	:ensure t)

(use-package which-key
	:ensure t 
	:config
	(which-key-mode))

(use-package org-bullets
  :ensure t
  :config
  (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1))))
 
(setq ido-enable-flex-matching t)
(setq ido-everywhere t)
(ido-mode 1)

(defalias 'list-buffers 'ibuffer)

(use-package ace-window
  :ensure t
  :init
  (progn
    (global-set-key [remap other-window] 'ace-window)
    (custom-set-faces
     '(aw-leading-char-face
       ((t (:inherit ace-jump-face-foreground :height 3.0)))))
    ))

(use-package counsel
  :ensure t)
```

**Comment by basil-conto** [comment]
> This exact file was executed in my previous PC and no error where presented.

What's the difference between your current and previous PC?

Which Counsel version is installed (check the directory names under `package-user-dir`)? Are Swiper and Ivy also installed? If so, which versions?

`counsel.el` loads `swiper.el`, which in turn loads `ivy.el`, so as long as you have consistent versions of the three packages installed, there should be no problem. Can you please try to strip down your configuration to the only parts needed to reproduce the issue?

The only thing I would do differently in `counsel.el` is explicitly add `(ivy "0.9.0")` to the `Package-Requires` library header, instead of depending on `swiper.el` to load `ivy.el` for us. This is in line with the philosophy of doing as one says and as one means.

**Comment by basil-conto** [comment]
I cannot reproduce your issue on any of the following Emacs versions:

    In GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars)
     of 2017-09-12 on hullmann, modified by Debian
    Windowing system distributor `The X.Org Foundation', version 11.0.11906000
    System Description: Debian GNU/Linux testing (buster)

    In GNU Emacs 25.2.1 (x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars)
     of 2018-05-07, modified by Debian built on binet
    Windowing system distributor 'The X.Org Foundation', version 11.0.11906000
    System Description: Debian GNU/Linux testing (buster)

    In GNU Emacs 27.0.50 (build 14, x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars)
     of 2018-07-06 built on thunk
    Repository revision: 3bbd4ffc68bcc2b3e003a2179a508b82055ad770
    Windowing system distributor 'The X.Org Foundation', version 11.0.11906000
    System Description: Debian GNU/Linux buster/sid

What I did is place your configuration in `~/.emacs`, move `~/.emacs.d` to a new location, and start Emacs. All three Emacs versions correctly installed all the packages and started up without any errors. I was then able to use Counsel features like `counsel-mode` without any problems. So I suspect the issue lies with your setup somewhere. Perhaps you should try reinstalling Ivy, Swiper, and Counsel.

**Comment by hfehrmann** [comment]
A fresh install of the packages worked. While configuring, I should have done something wrong.
