### ISSUE TITLE
Some counsel functions ignores ivy-height

### ISSUE THREAD

**Issue by tautologyclub** [abo-abo/swiper#1666]
I've set `ivy-fixed-height-minibuffer` to `t` and `ivy-height` to `24`. This works for most stuff (swiper, find-file, buffer-list etc) but some fringy functions just refuses to respect it. In particular `counsel-yank-pop`. I did `emacs -Q` and only loaded relevant parts of my init, but the problem persists. From what I can see, most other counsel functions work fine (counsel-M-x, counsel-rg, counsel-git-grep, counsel-locate and a bunch of others). I know I've seen at least one other counsel function behave like this but I can't recall which one right now.

I should note that this occurs independent of the size of my kill ring - it could have one entry, or `kill-ring-max` (which is 60 in my case).

This is my ivy config:

    (use-package    ivy
      :ensure       t
      :custom       (ivy-use-virtual-buffers        t)
                    (ivy-wrap                       t)
                    (ivy-use-selectable-prompt      t)
                    (ivy-fixed-height-minibuffer    t)
                    (ivy-height                     24)
                    (ivy-extra-directories          nil)
                    (ivy-count-format               "%d/%d - ")
                    (ivy-display-style              'fancy)
      :config       (ivy-mode 1)
                    (setq ivy-virtual-abbreviate 'full))

Any idea what the problem is?

**Comment by abo-abo** [comment]
> Any idea what the problem is?

You should customize `ivy-height-alist`, it overrides `ivy-height` per-command.

One problem that still remains is that `ivy-height` is a misleading name. In code it's actually the number of candidates that get displayed. When each candidate takes one line, it's exactly the minibuffer height. But for `counsel-yank-pop` that's not the case. What's worse, `counsel-yank-pop` has candidates of variable height (either 1 line or 5 lines by default).

I think it will take a lot of work to make `ivy-height` represent the amount of lines instead of the amount of candidates. But it would be nice to have it like that.

**Comment by basil-conto** [comment]
> What's worse, `counsel-yank-pop` has candidates of variable height (either 1 line or 5 lines by default).

Which is controlled by the user option `counsel-yank-pop-truncate-radius`, FYI.
