### ISSUE TITLE
counsel-find-file: Unexpectedly selected other entry

### ISSUE THREAD

**Issue by floli** [abo-abo/swiper#1683]
Hello,
like most of us, I have `.emacs` and `.emacs.d` in my home. I use C-x C-f and type `.emac` -> `.emacs.d` is selected. I press tab -> the selection moves to `.emacs`, which is then opened by another tab.

Why is selection moved at the first <tab> press? Can this behavior be modified as it bites me regularly?

**Comment by abo-abo** [comment]
Sorry, I don't understand what you mean by pressing `->`. Could you explain it a bit more clearly?

**Comment by basil-conto** [comment]
> like most of us, I have `.emacs` and `.emacs.d` in my home

FWIW, all Emacsites I know (including myself) prefer to keep `user-init-file` under `user-emacs-directory`, i.e. `~/.emacs.d/init.el`. See https://emacs.stackexchange.com/q/1/15748 for some arguments in favour of this approach.

> I press -> the selection moves to `.emacs`, which is then opened by another .

Sorry, I also don't understand what you mean in this sentence. What do you press? What do you mean by "opened"? Opened by another what? Perhaps the markdown syntax of your message got clobbered?

> Why is selection moved at the first press?

At the first press of what, following what?

Please provide a precise step-by-step description of your actions along with what you expect to see vs what actually happens after each step. Please also try reproducing any issue you run into starting from `emacs -Q` (or `make plain` from within a checkout of this repo) so as to rule out interference from your configuration.

**Comment by floli** [comment]
Sorry, my message was clobbered by markdown. I hope it is understandable now!

**Comment by abo-abo** [comment]
> Why is selection moved at the first press?

After the first <kbd>TAB</kbd>, your input is `.emacs` and your candidates are (`.emacs` `.emacs.d`). It's often convenient to have your input selected, seeing as you've already typed it out.

> Can this behavior be modified as it bites me regularly?

I would prefer not to do it. You should not consider <kbd>TAB TAB</kbd> as a single key chord, they're two actions which produce feedback for you. Even so, if you type `.ema TAB TAB`, it's more reasonable to select `.emacs` rather than `.emacs.d`.

Maybe you could type `ema TAB TAB`? That would not select `.emacs` any more.

Or you could type `.ema RET`, since you want `.emacs.d` which is already selected.

**Comment by hnry** [comment]
This gets me often too. Would really like if there was a simple way to modify this.

Never seen this before behaviour before, and almost every other interface we as developers or users won't automatically perform a full action on one key repeat.

**Comment by abo-abo** [comment]
@floli @hnry

I recommend this setting:

    (setq ivy-tab-space t)

When deciding what <kbd>TAB</kbd> does, I looked at how the completion works in bash:

1. When there's only one candidate, e.g. `~/Doc` -> `~/Documents`, cd there.
2. When there are more than one candidate, expand as much as possible.
3. When it's not possible to expand any more, show the candidate list

Here, we're looking at the case-3. Since Ivy always shows the candidate list, it seems a waste for
<kbd>TAB</kbd> to be a no-op in that case. So it looks natural to adapt the action from case-1 to
case-3:

- When <kbd>TAB</kbd> is pressed twice on the same directory, cd there.

If setting `ivy-tab-space` doesn't fix your issue, please open a new one.

**Comment by hnry** [comment]
@abo-abo Thank you for the response. I should've clarified; I think my expectation is slightly different than OP.

I don't want it to cd or open anything no matter how many times I tab. Most inputs like this (shell, default emacs, and so on) don't do this. Most of them either do a 'bell', or cycle over candidates.

Also personally I don't like how dirs open in a buffer (whether by accident or on purpose). It pulls your focus away from the minibuffer where I'm expecting is the area I should be looking. Like default emacs behaviour, or imagine at a command prompt you didn't press enter but something popped up you have to move your eyes to.

Won't open a new issue, just giving some user feedback, I guess this is just me and what I'm use to.

**Comment by abo-abo** [comment]
> Most inputs like this (shell, default emacs, and so on) don't do this

`case-1` that I described above is exactly the behavior of the shell and default emacs.
And by setting `ivy-tab-space` you effectively disable `case-2` and `case-3`.

> Also personally I don't like how dirs open in a buffer

I don't understand what you mean here.
