### ISSUE TITLE
ivy's switch to buffer cannot regonize recent files in new frame

### ISSUE THREAD

**Issue by FirstLoveLife** [abo-abo/swiper#1695]
![image](https://user-images.githubusercontent.com/37442588/43640127-409a43fa-9751-11e8-8b37-6ed7507418e6.png)

It can recognize the files already opened in the frame:
![image](https://user-images.githubusercontent.com/37442588/43640170-734899e6-9751-11e8-8bdd-71ff632fcb17.png)

Here is my conf:
```
(use-package ivy
    :ensure t
    :custom
    (ivy-mode 1)
    (ivy-use-virtual-buffers t)
    (ivy-count-format "(%d/%d) "))
```

It seems ivy-use-virtual-buffers doesn't work?

**Comment by basil-conto** [comment]
Are you able to reproduce this starting from `emacs -Q` (or `make plain`, if you have a checkout of this repo)? If not, then it's probably an issue in your configuration. Either way, can you please try to provide more details and a precise set of steps that others can follow to reproduce this issue, e.g. which commands you invoke. Without further details, I'm afraid this may be very hard for others to reproduce/debug.

Since `ivy-use-virtual-buffers` just tells `ivy-switch-buffer` to include the elements of `recentf-list` in the completion collection, can you please check what `(buffer-list)` and `recentf-list` evaluate to, and see if there's anything amiss?

FWIW, I have `pop-up-frames` set to a non-`nil` value (i.e. my Emacs always pops up new frames instead of windows) and I used to use `recentf` and `ivy-use-virtual-buffers`, and I've never noticed the issue you describe (though I can't be sure, because your description isn't entirely clear). My guess is that there is something in your configuration or the packages you use (is that Spacemacs in the screenshots?) that is causing this.

**Comment by FirstLoveLife** [comment]
@basil-conto Thanks for the reply. I have found the problem: I used org-babel to generate configuration, but I had some typo in ivy's babel which makes it didn't come into the real init.el. Now it is fixed.
