### ISSUE TITLE
Rename file to shorter name with ivy-mode in dired-do-rename.

### ISSUE THREAD

**Issue by halloleo** [abo-abo/swiper#1723]
I am struggling with using `ivy-mode` in `dired-do-rename`:

Let's say I have the file `my_file_with_a_long_name.txt` in current directory and I ant to rename it to the short name  `my_file.`. How do I do this?

When I type the shorter name and i press `RET`, `my_file_with_a_long_name.txt` is always selected. I tried `ivy-alt-done` as well to no avail...

**Comment by basil-conto** [comment]
Try <kbd>C-M</kbd> (`ivy-immediate-done`); see the following:
* https://github.com/abo-abo/swiper/wiki/FAQ#how-to-select-the-current-input-instead-of-the-current-candidate
* [`(ivy) Key bindings for single selection action then exit minibuffer`](http://oremacs.com/swiper/#key-bindings-for-single-selection-action-then-exit-minibuffer)

**Comment by halloleo** [comment]
Thanks. 

I might try to bind `ivy-immediate-done` to `RET` - hoping ivy becomes more similar to normal completion (but keeping it's power!) :-)

**Comment by halloleo** [comment]
Sorry to bother here again, but ivy behaves quite unexpected:

Let's say I use `counsel-find-file`; I get the files in the current directory listed as candidates; say, as above set out `my_file_with_a_long_name.txt` is amongst them. Now I have two scenarios:

1. I type `my_file` and I'd  expect the default action (without *selecting* the listed candidate `my_file_with_a_long_name.txt` via cursor keys or similar) is to use `my_file`. - I know thanks to your tip! :-) I can force this with `ivy-immediate-done`.

2. I enter `counsel-find-file` and type nothing, but move with the cursor keys and want to use the selection `my_file_with_a_long_name.txt`. - I know I can do this with `ivy-done`.

*But is there a way to do these two normal actions **with the same function (i,.e, with the same key)**? I think this would be soooo much more natural!!!*

Thanks a lot for all your help! ivy is such an interesting package!

**Comment by basil-conto** [comment]
> *But is there a way to do these two normal actions **with the same function (i,.e, with the same key)**?*

Are you asking for a command which forward to `ivy-done` if there is no user input, and to `ivy-immediate-done` otherwise?

If not, then how will said command know how to pick between `ivy-done` and `ivy-immediate-done`?

Sorry if I'm misunderstanding something.

**Comment by halloleo** [comment]
> Are you asking for a command which forward to ivy-done if there is no user input, and to ivy-immediate-done otherwise?

Yes, that could do it I guess. When I *just* type text I probably normally want that text (at least in a function like `file find` - maybe not in  `execute-extended-command`) to be used. When I  select via the arrow keys (possibly after narrowing down the selection) I normally want that selection.

**Comment by abo-abo** [comment]
We could have `ivy-immediate-done` forward to `ivy-done` when there's no input and the candidate index is not 0.

@basil-conto What do you think?

**Comment by basil-conto** [comment]
> We could have `ivy-immediate-done` forward to `ivy-done` when there's no input and the candidate index is not 0.

Sounds like `ivy-immediate-done` would be trying to be too smart and might end up biting the average user, at least if this behaviour were enabled by default. Even if the user explicitly requests this behaviour, I still don't think what you suggest is a perfect heuristic: what if, say, I type <kbd>C-n</kbd><kbd>C-p</kbd>, thus ending up at index 0 again? According to @halloleo's request, `ivy-immediate-done` should then exit with the current candidate via `ivy-done`.

Another heuristic would be to check whether `last-command` is a motion command such as `ivy-next-line` or `ivy-previous-line`, but this has its edge-cases too: for example, what if the user just wanted to scroll the collection?

The fact that we're even discussing heuristics should make it clear that this is very user-specific, custom behaviour, i.e. the best solution depends entirely on how the particular user likes to use Ivy. In other words, I'm not convinced there's a general solution which can be added to `ivy.el`, let alone `ivy-immediate-done` (yet - but please try to convince me).

So my conservative suggestion is that @halloleo add whatever command we come up with to their own configuration. If you prefer to add it to `ivy.el`, then I think it should be defined as a separate command, rather than overload `ivy-immediate-done`, which IMO should be simple and do what it says on the tin. Don't forget that `ivy-immediate-done` is an important escape hatch and transducer between `ivy-read` and `completing-read`, so we should really try to avoid any problematic edge-cases.

I'm sorry if I sound too skeptical/protective; I'm all for making Ivy completion smarter, I just don't want to rush Frankensteining something like `ivy-immediate-done` without a well-defined course of action. And at the end of the day, mine is just a single opinion. :)

**Comment by halloleo** [comment]
I agree my customisation suggestion might not be right for everyone. - Therefore a new exit function (`ivy-dwim-done`?) seems to be appropriate. 

Another thought about this: Is it possible to *have the input line as a selectable line?* This would make it very clear what will happen on executing the new function: 

1. If I type letters the input line is selected (highlighted). When I now execute the new function it returns what I just had typed.

2. If I, after typing letters, use the cursor keys the selection (highlight) moves to the candidates. The new function now returns the highlighted candidate. 

The problem in the current situation is that always the first *candidate* is highlighted, even though your mind might be just on what you've typed  - this makes using the typed section strangely a special case.

Hope this helps.

**Comment by manuel-uberti** [comment]
If I understand your use case, could `ivy-use-selectable-prompt` be what you're after?

**Comment by halloleo** [comment]
That's interesting! I will try it out tomorrow.

**Comment by halloleo** [comment]
`ivy-use-selectable-prompt ` does *nearly* what I am thinking of. 

The only trouble is that the default selection is still the first candidate and not the typed text above the first candidate. 

Is there a way to default  the selection to the typed text and not to the first candidate?

**Comment by abo-abo** [comment]
> Is there a way to default the selection to the typed text and not to the first candidate?

This goes against the point of having a completion system. If you just want to type out the candidate fully by default, you don't need a completion engine.

**Comment by halloleo** [comment]
You totally have a point for completion in `find-file` or `switch-buffer` where you mainly/always want to compete to given candidates. 

However completion for `write-file` or `dired-do-rename` is a totally different matter: Candidates are here only occasionally used, so IMHO the default should not be the first candidate, but the typed text.

**Comment by abo-abo** [comment]
> However completion for write-file or dired-do-rename is a totally different matter: Candidates are here only occasionally used, so IMHO the default should not be the first candidate, but the typed text.

Not the case for me, especially for `dired-do-rename`. Using `(setq dired-dwim-target t)`, I want to overwrite around 50% of the time. I don't think we should introduce an edge case here. Consistency has value as well.
