### ISSUE TITLE
ivy-read and text properties

### ISSUE THREAD

**Issue by jdz** [abo-abo/swiper#1724]
Currently there are cases where `ivy-read` returns a propertized string (see test case below).  There is code at the end of `ivy-read` that removes `idx` property, but it is done _after_ the function return value has been calculated (`prog1`).

I think this is a bug with Ivy because:

- `ivy-completing-read` is supposed to be compatible with `completing-read`, and it is not if there are observable differences between the two given the same inputs.
- The `idx` property is an implementation detail of Ivy that should not be leaking out.

At the moment I'm using an advice around `ivy-read` to strip away any text properties (using `substring-no-properties`), but it would be nice if the library could be fixed properly.

```elisp
(ert-deftest ivy-read-no-properties ()
  (should (equal
           (format "%S" (ivy-with '(ivy-read "pattern: " '(("whatever")))
                                  "RET"))
           "whatever")))
```

**Comment by basil-conto** [comment]
> There is code at the end of `ivy-read` that removes `idx` property, but it is done after the function return value has been calculated (`prog1`).

No, the property is also removed from the return value of `prog1` - they are the same string object.

> I think this is a bug with Ivy

Yes, this is a regression caused by 4ca87866037353cb0a0ddcab13d64ab48a9ccb71 which applies the `idx` property to the entire string, whereas `ivy-read` removes it only from the first character of non-empty strings.

I've submitted PR #1725 which should fix this; please test.
