### ISSUE TITLE
Cannot diminish counsel or ivy with use-package

### ISSUE THREAD

**Issue by matthew-piziak** [abo-abo/swiper#1752]
This does not work:

```emacs-lisp
(use-package counsel
  :diminish ivy-mode counsel-mode)
```

However, this lower-level action works:
```emacs-lisp
(use-package diminish :straight t)
(require 'diminish)
(diminish 'counsel-mode)
(diminish 'ivy-mode)
```

**Comment by basil-conto** [comment]
> This does not work:

Works for me in Emacs 26 and 27 (can't currently test any earlier Emacs versions, sorry), but even if it didn't, it would more likely be a bug with `use-package` or `diminish`, rather than `ivy` or `counsel`.

I don't use or follow `use-package` any more, but IIRC you can debug it by enabling `use-package-verbose` and, more importantly, checking its expansions by placing point after the `use-package` form and typing <kbd>M-x</kbd>`pp-macroexpand-last-sexp`<kbd>RET</kbd>. When I do this I get the following:

```el
(progn
  (defvar use-package--warning0
    #'(lambda
        (keyword err)
        (let
            ((msg
              (format "%s/%s: %s" 'counsel keyword
                      (error-message-string err))))
          (display-warning 'use-package msg :error))))
  (condition-case-unless-debug err
      (if
          (not
           (require 'counsel nil t))
          (display-warning 'use-package
                           (format "Cannot load %s" 'counsel)
                           :error)
        (if #1=(fboundp 'diminish)
          (diminish 'ivy-mode))
        (if #1#
            (diminish 'counsel-mode)))
    (error
     (funcall use-package--warning0 :catch err))))
```

which looks fine to me.

Are you sure you `(require 'diminish)` or `(autoload 'diminish "diminish" nil t)` before using the `use-package` keyword `:diminish`, as suggested in https://github.com/jwiegley/use-package/#use-packageel-is-no-longer-needed-at-runtime?

By the way, I recommend using Phil Sainty's excellent [`delight`](http://elpa.gnu.org/packages/delight.html) instead of `diminish`. Some advantages include:
* Distributed via the official [GNU ELPA](http://elpa.gnu.org/).
* More actively maintained.
* Works for both major and minor modes.
* Handles arbitrary [mode line constructs](https://www.gnu.org/software/emacs/manual/html_node/elisp/Mode-Line-Data.html) like `(:eval ...)`.
* Also supported by `use-package` via the `:delight` keyword.

**Comment by basil-conto** [comment]
> Everything seems to be working now.

I'm glad. :) Does that mean the issue can be closed?

**Comment by matthew-piziak** [comment]
Yes indeed. Closing. :)

**Comment by abo-abo** [comment]
@basil-conto Thanks for helping:)
