### ISSUE TITLE
How to know what is the default action

### ISSUE THREAD

**Issue by ChoppinBlockParty** [abo-abo/swiper#1774]
I have recently got confused by actions. Could you, please, clarify what is the right way to use it? I had chosen deleted a file in actions using `ivy-dispatching-done`, then I decide to `ivy-resume`, because I actually needed to open a file, of course, I had forgotten that my last action is delete and I hit `ivy-done` (e.g. `Enter). My file is gone, I had not stashed this file to git and, for some reasons I do not have backups of it (that is another issue to investigate). Could you suggest anything to avoid this problem in future?

**Comment by abo-abo** [comment]
`ivy-dispatching-done` is a combination of `ivy-read-action` and `ivy-done`. The first command, also bound to <kbd>C-M-a</kbd> permanently modifies the action for the current session so that you can use it with e.g. <kbd>C-M-m</kbd>.

`ivy-resume` restores the last active completion session. It doesn't try to reset to the default action or anything like that.

One suggestion to avoid it would be to remove `counsel-find-file-delete` from the list of actions. I was hesitant to add it by default in the first place (I prefer to delete files only via `dired`'s mark-and-confirm approach), but it seems many users actually want it there.

I don't think it's useful for `ivy-resume` to reset the action to default. Please close the issue if you agree. Otherwise let's keep it open for some more people to chime in.

**Comment by ChoppinBlockParty** [comment]
Hmm, I see, good advice. Is it only `counsel-find-file-delete` which deletes the files, or there are others? I think I was using `counsel-projetile-switch-project`, does it use the same action? Can you suggest how to make an action that opens dired on the current file?

**Comment by iquiw** [comment]
To avoid accidental file deletion, I think the followings may be useful.

* Display the current action somewhere around the prompt.
* Confirm to user before deleting file.

**Comment by ChoppinBlockParty** [comment]
@iquiw Yup, do you have anything like this drafted?

**Comment by abo-abo** [comment]
<kbd>M-o k</kbd> will now ask for confirmation unless `delete-by-moving-to-trash` is set.

I realize that this becomes a bit clunky when deleting multiple files within one session.

This can be improved in the future once ivy gets some kind of `mark-candidate`/`bulk-action` interface.

**Comment by abo-abo** [comment]
Please let me know if your concern has been sufficiently addressed. And thanks for bringing this up.

**Comment by ChoppinBlockParty** [comment]
Yes, I think it fixes main concerns. I have one question: if the file also has a buffer(s), will it ask to kill the buffers or not?

**Comment by ChoppinBlockParty** [comment]
Yes, I think, this is helpful.
