### ISSUE TITLE
Assigning swiper to C-S (capital s), also assigns to C-s

### ISSUE THREAD

**Issue by vaddiv** [abo-abo/swiper#1805]
If I use  `(global-set-key (kbd "C-S") 'swiper)` or
```
(use-package swiper
  :ensure t  
  :bind ("C-S" . 'swiper))
``` 
to bind swiper to that key combination, whenever I press `C-s` swiper is called.
However if I bind swiper to `Super-S` or `Hyper-S`, the same doesn't happen.

**Comment by basil-conto** [comment]
This issue is not specific to `swiper`, rather it pertains to Emacs in general, specifically the input encoding of the [terminal](https://www.gnu.org/software/emacs/manual/html_node/elisp/Multiple-Terminals.html) it's running under (either graphical or text).

Try `(kbd "C-S-s")` instead of `(kbd "C-S")`. Note this may not work under text terminals; see https://emacs.stackexchange.com/a/989/15748.

By the way, I think `use-package` expects the syntax `:bind ("C-S-s" . swiper)`, not `:bind ("C-S-s" . 'swiper)` (note the lack of symbol quoting).

**Comment by vaddiv** [comment]
Thank you for the quick response. I tried using ´(kbd "C-S-s")´ and it worked.
