### ISSUE TITLE
number of results displayed in minibuffer shrinks after visiting a long multi-line result

### ISSUE THREAD

**Issue by ChrisWills** [abo-abo/swiper#1807]
This issue manifests when scrolling through the ivy minibuffer after running something like counsel-rg which could contain very long matches. Upon visiting a match that is long enough that it exceeds the width of the minibuffer and then scrolling past is such that all results currently displayed each fit on one line, the number of displayed results is reduced by one.

Here is a simple reproducer. Initially 5 results are displayed but once you visit the long line, only 4 results are displayed for the remaining life of the minibuffer. 

My desired behavior here is that once we pass the long entry, we go back to displaying 5 single line entries. 

(setq ivy-height 5)                                                                                                                                            
(ivy-read "test: " '( "one" "two" "four" "five" "six" "seven" "eight" "ttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt\
tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt\
ttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt" ))

**Comment by basil-conto** [comment]
> the number of displayed results is reduced by one

I can reproduce this neither in a graphical nor a text-based Emacs session. Under a graphical terminal, the wide ninth candidate is truncated, and neither the height of the minibuffer nor the number of candidates displayed changes. Under a text terminal, the ninth candidate is not truncated; instead, the height of the minibuffer is increased by one screen line for the remainder of the completion session, but the number of candidates shown at any given time remains the same. Here's what I mean:

1. `make plain`
2. ```el
   (setq ivy-height 5)
   ```
   <kbd>C-j</kbd>
3. ```el
   (ivy-read "prompt: " (nconc (mapcar #'number-to-string
                                       (number-sequence 0 (* ivy-height 2)))
                               (list (make-string (* (frame-width) 2) ?w))))
   ```
   <kbd>C-j</kbd>

   ![graphical-3](https://user-images.githubusercontent.com/9121222/48662871-5524f900-ea80-11e8-9246-d2a36fa3559f.png)
4. <kbd>M-></kbd>

   ![graphical-4](https://user-images.githubusercontent.com/9121222/48662880-6a018c80-ea80-11e8-9cd9-2272191855d7.png)
5. <kbd>M-<</kbd>

   ![graphical-5](https://user-images.githubusercontent.com/9121222/48662884-75ed4e80-ea80-11e8-98da-c81579e54252.png)

Note the minibuffer maintains a constant height of 5 screen lines, showing 4 completion candidates. Compare this with a text-based session:

1. `make emacs='emacs -nw' plain`
2. ```el
   (setq ivy-height 5)
   ```
   <kbd>C-j</kbd>
3. ```el
   (ivy-read "prompt: " (nconc (mapcar #'number-to-string
                                       (number-sequence 0 (* ivy-height 2)))
                               (list (make-string (* (frame-width) 2) ?w))))
   ```
   <kbd>C-j</kbd>

   ![text-3](https://user-images.githubusercontent.com/9121222/48662896-a208cf80-ea80-11e8-8184-954ae64b0981.png)
4. <kbd>M-></kbd>

   ![text-4](https://user-images.githubusercontent.com/9121222/48662899-b056eb80-ea80-11e8-9cd8-a399b4aa08d1.png)
   Note the height of the minibuffer has increased to accommodate the wide 12th candidate, but the number of candidates on display hasn't changed.
5. <kbd>M-<</kbd>

   ![text-5](https://user-images.githubusercontent.com/9121222/48662902-b947bd00-ea80-11e8-8229-d229e7dc593f.png)
   Note the height of the minibuffer remains larger than it was at the beginning of the completion session, but the number of candidates on display hasn't changed.

I tested the recipes above with the following three versions of Emacs:

```
In GNU Emacs 25.2.1 (x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars)
 of 2018-08-27, modified by Debian built on x86-csail-01
Windowing system distributor 'The X.Org Foundation', version 11.0.12003000
System Description:	Debian GNU/Linux testing (buster)

In GNU Emacs 26.1.50 (build 6, x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars)
 of 2018-11-01 built on thunk
Repository revision: d53a2b65db9952580efcf5ffe75a313bcb49a99e
Windowing system distributor 'The X.Org Foundation', version 11.0.12003000
System Description:	Debian GNU/Linux testing (buster)

In GNU Emacs 27.0.50 (build 53, x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars)
 of 2018-11-16 built on thunk
Repository revision: 644a308b4e1513e04be9360e1586e14b32ec0159
Repository branch: master
Windowing system distributor 'The X.Org Foundation', version 11.0.12003000
System Description: Debian GNU/Linux buster/sid
```

> My desired behavior here is that once we pass the long entry, we go back to displaying 5 single line entries.

Are you able to reproduce the issue starting from `emacs -Q` or `make plain`? What is your full <kbd>M-x</kbd>`emacs-version`<kbd>RET</kbd> and version of Ivy? If you are on Emacs 25 or newer, what is your value of `resize-mini-windows`? Have you tried setting it to `t` instead of the default `grow-only`? Are you running Emacs under a graphical or a text terminal? Are you able to provide a more detailed and/or reproducible recipe, perhaps accompanied by screenshots?

**Comment by ChrisWills** [comment]
Thanks very much for your detailed reply!

I am running emacs in the terminal and as it turns out I'm getting the exact same behavior that you described above. I was wrong when I said the number of displayed entries is reduced, it is just that the mini-buffer grows leaving an awkward blank area as you described.
 
Setting `resize-mini-windows` to `t` instead of `grow-only` gives me the behavior I'm looking for so that's perfect.

Thanks and apologies for the confusion!

**Comment by basil-conto** [comment]
> Setting `resize-mini-windows` to `t` instead of `grow-only` gives me the behavior I'm looking for so that's perfect.

I'm glad to hear.

I noticed an issue when `resize-mini-windows` is `t`, however; see #1809.

**Comment by basil-conto** [comment]
FWIW, there also exist the commands `ivy-minibuffer-grow` and `ivy-minibuffer-shrink`, bound to <kbd>C-o</kbd><kbd>></kbd> and <kbd>C-o</kbd><kbd><</kbd> by default, respectively; see [`(ivy) Hydra in the minibuffer`](http://oremacs.com/swiper/#hydra-in-the-minibuffer).
