### ISSUE TITLE
counsel-find-file / sometimes deletes parent directories

### ISSUE THREAD

**Issue by dwang20151005** [abo-abo/swiper#1829]
Not sure how to describe this in English, so here's a reproduction:

    mkdir -p /tmp/foo/bar/foobar

Then from a dired buffer open to /tmp, invoke counsel-find-file and type

    foo/bar/foo

Now `foobar/` is the only possible suggestion, so I type '/' expecting to complete to

    /tmp/foo/bar/foobar/

but instead it deletes the parent directory and I end up back at 

    /tmp/foo

If this is intended behavior, could you explain the rules for this deleting-completion behavior?  I find it quite surprising.

I am running counsel-20181120.1844 and emacs 25.3, in case that matters.

(And I hope this goes without saying, but thanks for all your work on this great tool.)

**Comment by dwang20151005** [comment]
Okay, fixed my reproduction.  Along the way, discovered a couple of non-reproductions:

    mkdir -p /tmp/foo/tmpbar
    M-x counsel-find-file RET /tmp/foo/tmp/

and,

    mkdir -p /tmp/foo/bar/baz/bardir
    M-x find-file RET /tmp RET
    M-x counsel-find-file RET foo/bar/baz/bar/

It appears to happen only when one completes using a unique prefix which is also exactly the name of an immediate child of the directory from whose dired buffer one invoked counsel-find-file.

That's got to be a bug, right?

**Comment by basil-conto** [comment]
> That's got to be a bug, right?

Yes, and it's caused by the following branch of `ivy--magic-file-slash`: https://github.com/abo-abo/swiper/blob/86635fb8268c07b9fb534357e8e0940c23edeef7/ivy.el#L2741-L2744

In your repro, `ivy-text` is `"foo/"`, `default-directory` is `"/tmp/"`, and `ivy--directory` is `"/tmp/foo/bar/"`, which is why `(file-exists-p ivy-text)` returns non-`nil` (relative file names are expanded against `default-directory`).

My initial guess would be to make the following change:

```diff
diff --git a/ivy.el b/ivy.el
index 1c5e5bb..2cb0be6 100644
--- a/ivy.el
+++ b/ivy.el
@@ -2738,10 +2738,11 @@ ivy--magic-file-slash
            (let ((drive-root (match-string 0 ivy-text)))
              (when (file-exists-p drive-root)
                (ivy--cd drive-root))))
-          ((and (file-exists-p ivy-text)
-                (not (string= ivy-text "/"))
-                (file-directory-p ivy-text))
-           (ivy--cd (expand-file-name ivy-text)))
+          ((let ((dir (expand-file-name ivy-text ivy--directory)))
+             (when (and (not (string= ivy-text "/"))
+                        (file-directory-p dir))
+               (ivy--cd dir)
+               t)))
           ((and (or (> ivy--index 0)
                     (= ivy--length 1)
                     (not (string= ivy-text "/")))
```

But given the history of pitfalls here (see e.g. commit f94c15c8cb40f7a9959a3ffcd2052bb3a118eb3f and #955), I'm not 100% sure this won't break something else; perhaps @abo-abo can comment.

I'm also not sure whether `default-directory` should in fact be bound to `ivy--directory` for the entirety of `ivy--magic-file-slash`, given the commentary of commit f94c15c8cb40f7a9959a3ffcd2052bb3a118eb3f.

**Comment by basil-conto** [comment]
> My initial guess would be to make the following change:

PR #1831 now contains this change.
