### ISSUE TITLE
swiper--update-input-ivy: Invalid function: with-ivy-window

### ISSUE THREAD

**Issue by cg4242** [abo-abo/swiper#185]
Since the last update I get this error when I use swiper. I use

GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2015-04-10 on builder10-9.porkrind.org

with prelude on OSX Yosemite.

**Comment by drot** [comment]
Can confirm happening on `GNU Emacs 24.5.1 (i686-pc-linux-gnu, X toolkit, Xaw scroll bars)` as well.

**Comment by abo-abo** [comment]
Make sure to update your packages and restart Emacs. `with-ivy-window` is a macro, so maybe there was some issue with package.el not loading it.

**Comment by drot** [comment]
Reinstall from scratch solved the issue for me.

**Comment by abo-abo** [comment]
Yes, that should do it. I think the issue is with byte compilation: the byte compiler did not know that `with-ivy-window` was a macro. It's likely that the byte compiler did `(require 'ivy)`, but that did nothing, since you had it loaded already.

Just to show how to do this manually: navigate to the package directory in elpa. Press <kbd>L</kbd> to force load all *.el files.  Press <kbd>B</kbd> to byte-compile the files. Just <kbd>L</kbd> is enough to fix the current session, <kbd>B</kbd> is for all future sessions.

**Comment by cg4242** [comment]
Hi Oleh,

I can confirm this. I’ve uninstalled swiper and re-installed from melpa (20150730.659), now swiper with ivy runs fine. I will test swiper-helm later.

Thanks for your quick help.

Greetings, Christoph

**Comment by abo-abo** [comment]
It appears that everyone else has updated without problems. Maybe connection issues are to blame. In any case, for a lot of packages, re-installing can fix this type of issue.
