### ISSUE TITLE
ivy--flx-sort doesn't seem to be called with ivy--regex-fuzzy

### ISSUE THREAD

**Issue by mc10** [abo-abo/swiper#1858]
I'm currently trying to use `ivy--regex-fuzzy`, but it doesn't seem like `ivy--flx-sort` is called, at least when using `counsel-find-file`. My Ivy config looks like the following (note: I'm using Spacemacs):

    (use-package ivy
      :defer t
      :after flx
      :custom
      (ivy-re-builders-alist
        '((read-file-name-internal . ivy--regex-fuzzy)
          (ivy-switch-buffer . ivy--regex-fuzzy)
          (t . spacemacs/ivy--regex-plus)))

      ;; ...
      )

Interestingly, when I replace the last config setting with just

    (ivy-re-builders-alist '((t . ivy--regex-fuzzy)))

My results do seem to be sorted by `flx`.

I'm a bit lost as to how to resolve this issue. Any ideas?

**Comment by basil-conto** [comment]
> I'm currently trying to use `ivy--regex-fuzzy`, but it doesn't seem like `ivy--flx-sort` is called, at least when using `counsel-find-file`. My Ivy config looks like the following (note: I'm using Spacemacs):

Have you tried adding an entry for `counsel-find-file` in `ivy-re-builders-alist`?

```el
(ivy-re-builders-alist
 '((counsel-find-file . ivy--regex-fuzzy)       ; <--
   (read-file-name-internal . ivy--regex-fuzzy)
   (ivy-switch-buffer . ivy--regex-fuzzy)
   (t . spacemacs/ivy--regex-plus)))
```

> Interestingly, when I replace the last config setting with just [...] My results do seem to be sorted by `flx`.

This is because the key `t` in `ivy-re-builders-alist` is the fallback for any callers (such as `counsel-find-file` in your example) which don't have their own setting.

It sounds like you were expecting `read-file-name-internal` to cover `counsel-find-file`. The reason this is not the case is that all Counsel functions use the `ivy-read` API, which allows specifying a specific `:caller` symbol to identify the command in settings such as `ivy-re-builders-alist`. `read-file-name-internal` is only used by built-in commands such as `find-file`, which don't go through the `ivy-read` API.

**Comment by mc10** [comment]
I see, that's useful to know. Thanks!
