### ISSUE TITLE
Impossible to enter a "nil" value with ivy-read

### ISSUE THREAD

**Issue by swhahn** [abo-abo/swiper#187]
If ivy-mode is switched on, it seems to be impossible to enter a "nil" value.
With ivy-mode switched on use revert-buffer-with-coding-system you get:

903  Coding system for visited file (default nil):
adobe-standard-encoding
adobe-standard-encoding-dos
...

Normally you just have to enter <enter> to revert with the current coding system.
I didn't found a solution for this situation. (Helm seems to add the nil value in the
completion list.)

Greetings
Stefan
P.S. Your code is inspiring, thank you!

**Comment by abo-abo** [comment]
You can exit the minibuffer with the current text, instead of the current candidate, with either <kbd>C-M-j</kbd> or <kbd>C-u C-j</kbd>.

Glad you like the code:). Feel free to contribute to the wiki (with this issue for example, since it comes up a lot), if you have the time. The project could really use better documentation.
