### ISSUE TITLE
show number of total matches [Feature request]

### ISSUE THREAD

**Issue by junnu-github** [abo-abo/swiper#1931]
Swiper shows the count of lines which has the matching phrase

for example , contents of buffer
```
      word1 word2 word3
      word4 word5 word6
```

when the phrase "word" is searched, the count is shown as 2, since 2 lines has the matching phrase. 
It would be nice to have option to customize to show the total match count (in this case its 6)

**Comment by basil-conto** [comment]
This has also been asked for on Emacs SE: https://emacs.stackexchange.com/q/32371/15748.

**Comment by Ergus** [comment]
Hi, yes I have been interested in this too. A similar/related functionality is to make swiper progress (go to next match) similar to isearch in case of different matches in the same line to move faster between them. 
For example if the user wants to go to the third match of a word (or subword) in a long line that has it many times; right now is a bit faster/easier to use isearch than swiper (same if he wants to go to the previous match and type C-r). 
I know there  is avy that faces this kind of issues, but sometimes is faster to type C-s regex and C-s a couple of times. 
This functionality will require also a different face for the matching pattern within the actual line.

**Comment by abo-abo** [comment]
Thanks. Please test `swiper-isearch`. It's no longer line-based like `swiper`, which makes it display the total number of matches. It also fixes the slow startup of `swiper`.

**Comment by Ergus** [comment]
Hi:
Yes it works pretty fine for me and probably it will fully replace swiper & isearch (I only need to bind C-r to invert search direction, nothing special). 
I know this is too much to ask for, but please remember to update the wiki in order to include all the extra nice fancy new features/options you have added recently. 
Once again;
Very thanks

**Comment by abo-abo** [comment]
You're welcome. The wiki is open for public edits, no pull request process necessary. PRs for documentation are welcome as well.

**Comment by Ergus** [comment]
Hi Abo-abo:

Is it there any face to change in order to distinguish the current selected candidate from the others in the same line? Because right now when using the isearch-swiper from a terminal emacs there is no way cause the cursor disappears during search and all the line is highlighted.

In graphical emacs the cursor makes the difference, but it could be also useful to have a more verbose difference for the actual candidate like a different face.

Sorry for bothering more :( tell me if you prefer to open a new issue.

**Comment by abo-abo** [comment]
Please test.

**Comment by Ergus** [comment]
Yes, better now. I would prefer the different face for the whole match, but this way is good enough. It is functional for me as is now.
Once again very thanks

**Comment by Lenbok** [comment]
@ergus Could you please show your C-r binding to change search direction?
