### ISSUE TITLE
inconsistent handling of ivy-re-builder-alist

### ISSUE THREAD

**Issue by CeleritasCelery** [abo-abo/swiper#1934]
Currently the documentation for `ivy-rebuilder-alist` says

```
  An alist of regex building functions for each collection function.

Each key is (in order of priority):
1. The actual collection function, e.g. `read-file-name-internal'.
2. The symbol passed by :caller into `ivy-read'.
3. `this-command'.
4. t.
```

However `this-command` is only consider iff there is no symbol defined by caller.

 Example from counsel:
There is a function `counsel-rg` that calls `counsel-ag`. 
`counsel-ag` defines `:caller`
`ivy-re-builder-alist` is `((counsel-rg . ivy--regex)(t . ivy--regex-plus))`
The setting for `counsel-rg` is ignored, even though the documentation says that it should be applied (`this-command` takes priority over `t`). This does not apply to the other keys (just because a collection function is defined does not make `:caller` an invalid key, etc)

Either the documentation needs be updated to reflect this inconsistency, or the handling of `ivy-re-builder-alist` needs to be updated to match the documentation.

**Comment by basil-conto** [comment]
> Either the documentation needs be updated to reflect this inconsistency, or the handling of `ivy-re-builder-alist` needs to be updated to match the documentation.

Or `counsel-rg` has to be fixed so that it doesn't call `counsel-ag` (any logic they share should be extracted as subroutines). I think that's the correct solution to the example you describe.

Having said that, I agree that the docstring of `ivy-re-builder-alist` does not apply in all cases of identifying a completion session by a symbol. In other words, collection functions, callers, and `this-command` are not treated consistently for all customisations. For example, IIRC `ivy-height-alist` only takes the caller into consideration, not the collection function.

**Comment by abo-abo** [comment]
I think this has been fixed sometime ago. Tested just now with:

```elisp
(setq ivy-re-builders-alist
      '((counsel-rg . ivy--regex-fuzzy)
        (t . ivy--regex-plus)))
```
