### ISSUE TITLE
counsel-M-x affects display-line-number-mode

### ISSUE THREAD

**Issue by purcell** [abo-abo/swiper#1940]
`counsel-M-x` affects `display-line-number-mode` negatively in a way that I have not seen any other minibuffer command do. It's been annoying me for months and I finally narrowed it down to counsel. :-)

Steps to reproduce:

- emacs -Q
- Evaluate `(add-hook 'prog-mode-hook 'display-line-numbers-mode)`
- Load ivy, counsel and swiper, enable `counsel-mode`
- Open a long prog-mode file, ensure that there are longer lines off the bottom of the buffer, e.g. if lines 1-50 are visible, and the file has 100+ lines in total.
- Hit M-x, thereby triggering `counsel-M-x`
- The width of the prog-mode buffer's line number strip shrinks.

Tested with Emacs HEAD and 26.1.

Having investigated this, it seems that this is caused by [`ivy-read` setting `resize-mini-windows` to nil in graphic display frames](https://github.com/abo-abo/swiper/blob/2a02343cdf218441158e83323ce507a6d9112445/ivy.el#L1913): with this line removed, everything works perfectly. The default for that variable since Emacs 25.1 is `grow-only`, so I think that it would be correct to either remove ivy's override of this value, or to unconditionally set it to `grow-only`, though I don't understand the intent of the code, introduced in 18019278d2b849b1287d299a894a4b98c9707ba2.

**Comment by purcell** [comment]
(P.S. I don't know *why* `resize-mini-windows` affects line numbering in another buffer, of course.)

**Comment by basil-conto** [comment]
> The default for that variable since Emacs 25.1 is `grow-only`, so I think that it would be correct to either remove ivy's override of this value, or to unconditionally set it to `grow-only`, though I don't understand the intent of the code, introduced in [1801927](https://github.com/abo-abo/swiper/commit/18019278d2b849b1287d299a894a4b98c9707ba2).

As the author of that commit, I do not fully understand why the value of `resize-mini-windows` has to be changed either. My commit merely refactored existing logic so that Ivy doesn't permanently alter the value of a user option, which is not kosher.

More enlightening precedent can be found in #1809 and the commits which actually tried to fix it, namely 36dd91e5a3e12394eb8c402997ffd80b96fa5841 and c1c1ec7cb9c99c50424416a143747f64e3083552.

**Comment by basil-conto** [comment]
FWIW, I cannot reproduce what you describe in the following Emacs version:

```
In GNU Emacs 27.0.50 (build 3, x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars)
 of 2019-02-19 built on thunk
Repository revision: 0a6c4479cff17b487580abe3a7ee202e71be25d2
Repository branch: master
Windowing system distributor 'The X.Org Foundation', version 11.0.12003000
System Description: Debian GNU/Linux buster/sid
```

I tried starting from both `make plain` (which loads Ivy and its dependencies in the right order for you) and `emacs -Q`, and opened both the 33.5kloc Emacs source file `src/xdisp.c`, as well as the 25kloc <kbd>M-x</kbd>`find-library`<kbd>RET</kbd>`org`<kbd>RET</kbd>. Invoking `counsel-M-x` did not affect the display of the line number "fringe" in any of these combinations.

Can you please share your full <kbd>M-x</kbd>`emacs-version`<kbd>RET</kbd>, or better yet the information generated by <kbd>M-x</kbd>`report-emacs-bug`<kbd>RET</kbd>, in case this issue is specific to your platform?

**Comment by purcell** [comment]
I'm on MacOS, using a graphical display. I'm digging into this a little bit more, and with `make plain` I can currently only reproduce this issue when the frame is full-screen, and it seems like `resize-mini-windows` doesn't actually affect things.

**Comment by purcell** [comment]
Okay, so this is actually related to the window height: if I `make plain` and enable `display-line-numbers-mode` in a buffer visiting `counsel.el`, and have 18 lines visible, with point on line 1...

<img width="881" alt="screenshot 2019-02-20 at 13 32 55" src="https://user-images.githubusercontent.com/5636/53057369-15086300-3514-11e9-92e4-9028781cc0d3.png">

then bringing up `counsel-M-x` doesn't affect the line number alignment:

<img width="881" alt="screenshot 2019-02-20 at 13 33 26" src="https://user-images.githubusercontent.com/5636/53057403-349f8b80-3514-11e9-958e-40faa3037436.png">

But if I show only 15 lines...

<img width="881" alt="screenshot 2019-02-20 at 13 35 08" src="https://user-images.githubusercontent.com/5636/53057449-60227600-3514-11e9-9bab-8dacc48d27aa.png">

then `counsel-M-x` causes the following narrowing of the line numbers:

<img width="881" alt="screenshot 2019-02-20 at 13 35 35" src="https://user-images.githubusercontent.com/5636/53057459-6d3f6500-3514-11e9-9439-981cd29a08d2.png">

So this is something to do with Emacs deciding that the visible line numbers in the buffer can be narrowed, and the reason why I have only seen this with ivy is because of the particular height of ivy's minibuffer. It turns out I can reproduce this with `ido-vertical-mode`.

The window length at which the behaviour changes is weird, as seen in the above screenshots.

In any case, this is either intended Emacs behaviour (ugh) or an Emacs bug, and is not specific to Ivy -- apologies for the noise here, and thanks for the sanity check.

**Comment by purcell** [comment]
(P.S. `(setq display-line-numbers-width 3)` essentially suppresses this behavioural quirk, without breaking display of buffers that have > 999 lines.)

**Comment by basil-conto** [comment]
> In any case, this is either intended Emacs behaviour (ugh) or an Emacs bug

My guess would be that it's "intended behaviour" insofar as the display code has to employ certain heuristics/optiimisations in order to remain sufficiently performant in buffers of any size. It probably wasn't designed with the use-case of frequent and drastic minibuffer window size changes in mind. The author of `display-line-numbers`, Eli Zaretskii, is also one of the head maintainers and is very active on the `bug-gnu-emacs` and `emacs-devel` mailing lists, in case you'd like to raise this issue/question.

> apologies for the noise here, and thanks for the sanity check

No worries, thanks for reporting this.

**Comment by purcell** [comment]
Yeah, I may well follow up with Eli. Thanks!
