### ISSUE TITLE
Feature request : projectile-remove-known-project in counsel mode

### ISSUE THREAD

**Issue by jayhanjaelee** [abo-abo/swiper#1944]
I use projectile remove known project when I need to organize projectile project list.
So I want it to be seen counsel mode style.

**Comment by basil-conto** [comment]
I do not understand what you are asking for, can you please elaborate? `projectile-remove-known-project` uses `projectile-completing-read` which already supports calling `ivy-read` in the same way Counsel functions do. Have you customised the user option `projectile-completion-system` to be `ivy` instead of the default `ido`?

**Comment by jayhanjaelee** [comment]
For example counsel-find-file, cursor can be moved using control + p, control + n. the vertical style minibuffer is appeared.

So I hope vertical style navigation to be applied to `projectile-remove-known-project` equally.

**Comment by basil-conto** [comment]
> For example counsel-find-file, cursor can be moved using control + p, control + n. the vertical style minibuffer is appeared.

The same applies to `projectile-remove-known-project` if you have set the user option `projectile-completion-system` to `ivy`:

```el
(setq projectile-completion-system 'ivy)
```

> So I hope vertical style navigation to be applied to `projectile-remove-known-project` equally.

What is your value of `projectile-completion-system`? <kbd>C-h</kbd><kbd>v</kbd>`projectile-completion-system`<kbd>RET</kbd>

**Comment by jayhanjaelee** [comment]
My one was ido, after I change this value to that you recommended. It works as I wanted. Thanks.
