### ISSUE TITLE
[Question] How to use ivy--regex-fuzzy with magit-builtin-completing-read

### ISSUE THREAD

**Issue by yqrashawn** [abo-abo/swiper#1946]
```emacs-lisp
(setq ivy-re-builders-alist
        '((magit-builtin-completing-read . ivy--regex-fuzzy
          (t . ivy--regex-plus)))
```
Above code won't work.
The magit function is at below.
```emacs-lisp
(defun magit-builtin-completing-read
  (prompt choices &optional predicate require-match initial-input hist def)
  "Magit wrapper for standard `completing-read' function."
  (unless (or (bound-and-true-p helm-mode)
              (bound-and-true-p ivy-mode))
    (setq prompt (magit-prompt-with-default prompt def))
    (setq choices (magit--completion-table choices)))
  (cl-letf (((symbol-function 'completion-pcm--all-completions)
             #'magit-completion-pcm--all-completions))
    (let ((ivy-sort-functions-alist nil))
      (completing-read prompt choices
                       predicate require-match
                       initial-input hist def))))
```
[Link to the code](https://github.com/magit/magit/blob/3e73ff19d342bdebf9b91ec78f03d24aa0dbe771/lisp/magit-utils.el#L483)

**Comment by basil-conto** [comment]
> Above code won't work.

This is because `magit-builtin-completing-read` is a generic subroutine of completion in Magit, rather than an interactive command. In scenarios like this, Ivy relies mostly on the value of `this-command` to identify the current completion session and apply the appropriate user settings.

Normally you'd have to add an `ivy-re-builders-alist` entry for each Magit command which uses completion, e.g. `magit-status`, `magit-fetch-other`, `forge-checkout-pullreq`, etc.

Luckily, you can wrap `magit-builtin-completing-read` in a custom function which sets `this-command` to a custom value. This is safe to do, because `magit-completing-read` saves and restores the value of `this-command` (see magit/magit#3529) around calls to `magit-completing-read-function`.

So here's one of several possible solutions for your personal configuration:

```el
(defun my-magit-command (&rest _)
  "Dummy command.
Intended as value for `this-command' during Magit completion."
  (interactive)
  (setq this-command #'my-magit-command))

(with-eval-after-load 'ivy
  ;; Use fuzzy completion style in all Magit completion sessions.
  (setf (alist-get 'my-magit-command ivy-re-builders-alist) #'ivy--regex-fuzzy))

(with-eval-after-load 'magit
  (add-function :before magit-completing-read-function #'my-magit-command))
```

**Comment by yqrashawn** [comment]
@basil-conto Thanks for your detailed explanation. Problem solved. Thanks!

**Comment by yqrashawn** [comment]
Hi @basil-conto. It seems this won't work for `magit-log-other`. Any idea how to archive that?

- magit-log-other https://github.com/magit/magit/blob/5503aa1857e78bb43502261956173a66c9b88c71/lisp/magit-log.el#L617

**Comment by basil-conto** [comment]
@yqrashawn `magit-log-other` is an interactive command so you can use it as a key in `ivy-re-builders-alist` directly.
