### ISSUE TITLE
counsel: org-agenda-bulk-action  

### ISSUE THREAD

**Issue by srustamo** [abo-abo/swiper#200]
Please consider adding a counsel function to handle org-agenda-bulk-action.

You can add/remove flags on multiple items in the agenda by selecting them using m, then B (org-agenda-bulk-action) and then + (to add tags) or - (to remove tags).

The org-mode itself does not provide the ability to apply multiple tags, however.

**Comment by abo-abo** [comment]
Now you should be able to change tags for any agenda item with `counsel-org-tag`.  If any items are marked, you can only add tags with `counsel-org-tag` instead of add/remove. Please test.

**Comment by srustamo** [comment]
Thank you. The  `counsel-org-tag` indeed works as you describe.

I guess acting on multiple marked items in the agenda (adding/removing tags, e.g.) is beyond the scope of this package, however, if this is possible, please consider this for `counsel.el`.

**Comment by abo-abo** [comment]
> I guess acting on multiple marked items in the agenda (adding/removing tags, e.g.) is beyond the scope of this package, however, if this is possible, please consider this for counsel.el.

You can **add** tags to multiple marked items in the agenda.

You can't **remove** them, because it doesn't make sense to remove a tag from a list of headings that may or may not have it.  And I don't really want to add a separate command just for removing tags from multiple items. One command is better than two.

**Comment by srustamo** [comment]
> You can't remove them, because it doesn't make sense to remove a tag from a list of headings that may or may not have it.
I guess checking if an item has a tag is more difficult than it sounds. If so, the only other request I would have is to auto-reload the agenda after running `counsel-org-tag`, so that its effect is visible.

**Comment by abo-abo** [comment]
> I guess checking if an item has a tag is more difficult than it sounds.

This isn't the problem. The problem is marking two headings, one of them has `:foo:`, the other `:bar:` and you select `:foo:`.  What should be done in this case: add or remove tag?

- have first `:foo:` and second `:foo:bar:`
- have first `::` and second `:foo:bar:`

Adding and removing in one command makes sense only for a single tag, not for many.
