### ISSUE TITLE
counsel-ag stuck at one more char

### ISSUE THREAD

**Issue by shelper** [abo-abo/swiper#2093]
as show in the image, it stucks at 1 more char no matter how many chars i input,
`counsel-ag-base-command` is set to `"ag -S --nocolor --nogroup %s"`

<img width="549" alt="Screen Shot 2019-06-13 at 9 37 56 AM" src="https://user-images.githubusercontent.com/546163/59437189-127d9200-8dbf-11e9-901e-09d86b13677c.png">

**Comment by leungbk** [comment]
Can you give an exact recipe? I can't reproduce this.

**Comment by shelper** [comment]
i think it is ag 's issue when i switch to rg, everything is fine.

**Comment by wtao137** [comment]
I also encountered this issue when using `ag version 2.2.0` on archlinux. And my `counsel-ag-base-command` is set to `"ag --nocolor --nogroup %s"`.
I found this can be fixed by changing `counsel-ag-base-command` to `ag --vimgrep %s`.
Here are the different results produced by these two commands:
```
ag --nocolor --nogroup Hello:
hello:1:Hello World
world:1:World Hello

ag --vimgrep Hello:
hello:1:1:Hello World
world:1:7:World Hello
```
As you can see, the column number is emitted in the ag version 2.2.0. I guess this is the cause of this issue. Maybe we can change `counsel-ag-base-command` to `ag --vimgrep %s` so it's the same on both linux and windows?

**Comment by abo-abo** [comment]
@wtao137 thanks, I've changed the default to `--vimgrep`. Which works fine for me with ag 2.1.0 on GNU Linux.
