### ISSUE TITLE
Better documentation about ivy-set-actions

### ISSUE THREAD

**Issue by lovaulonze** [abo-abo/swiper#2197]
### Problem description
`ivy-set-actions` covers default values in the `ivy--actions-list`. Use `ivy-add-sections` instead?
#### Environment tested
- Emacs 26.2
- Hosting OS: macOS 10.14
- Ivy version (MELPA 20190809.1551)

Following the documentation, I tried to bind extra exit points to the `counsel-find-file` using `ivy-set-actions` with the following MWE:
```Elisp
(require 'ivy)
(require 'counsel)
(require 'swiper)
(ivy-mode t)

(ivy-set-actions 'counsel-find-file
		 '(("p" (lambda (x) (with-ivy-window (insert (file-relative-name x))))
		    "insert relative file name")
		   ("n" (lambda (x)
			  (with-ivy-window
			    (insert (file-name-nondirectory (replace-regexp-in-string "/\\'" "" x)))))
		    "insert file name without any directory information")))
```

#### Issues
1) After evaluating this in the startup, the value for `counsel-find-file` in the `ivy--actions-list` only contains the options "p" and "n"
2) If the `(require 'ivy)` lines are not explicitly called, the extra options "p" and "n" are not correctly added to the `ivy--actions-list`

#### Questions
1) The correct behavior is obtained replacing the function by `ivy-add-actions`. Should this be changed in the documentation?
2) I don't know exactly why the `(require 'ivy)` lines are necessary for correct behavior of `ivy-add-actions`. Should this behavior be documented or explicitly load `counsel.el` once ivy-mode is set?

My understanding is that if the `require` lines are not specified, =counsel.el= can be loaded at the first time `counsel-find-file` is called, which is after the startup process is done. `counsel.el` explicitly uses `ivy-set-actions` to set the bindings, and overwrite the user-defined values.

**Comment by abo-abo** [comment]
> The correct behavior is obtained replacing the function by ivy-add-actions. Should this be changed in the documentation?

I don't know which documentation you're referring to. I looked at the docstrings, and they correctly describe the current behavior.

> I don't know exactly why the (require 'ivy) lines are necessary for correct behavior of
> ivy-add-actions. Should this behavior be documented or explicitly load counsel.el once ivy-mode is
> set?

I think you meant `(require 'counsel)`, since if you don't `(require 'ivy)`, `ivy-set-actions` is not defined.

You need to `(require 'counsel)` since counsel.el calls `ivy-set-actions` to initialize the list of actions. The user can then call `ivy-add-actions`.

I think the situation is fine as it is. There's no point to lazy-loading ivy or counsel, they are quite small. If you have ideas for improvement, they're welcome. Otherwise, you can close the issue.

**Comment by lovaulonze** [comment]
Thanks. The explanations are clear enough.
