### ISSUE TITLE
Ivy candidates order

### ISSUE THREAD

**Issue by iris-garcia** [abo-abo/swiper#2213]
Hi,
First of all thanks for this amazing package.
Second, probably this is not an issue but I just want to be sure as I couldn't figure out how to change the way the candidates are sorted.

Having these builders:
```
(setq ivy-re-builders-alist
      '((read-file-name-internal . ivy--regex-ignore-order)
	(counsel-M-x . ivy--regex-ignore-order)
	(ivy-switch-buffer . ivy--regex-ignore-order)
	(swiper . ivy--regex-ignore-order)
	(t . ivy--regex-fuzzy)))
```
When I use `counsel-M-x` and type for example: **magit status** I get the following candidates:

![ivy](https://user-images.githubusercontent.com/3024945/63596062-aab3a680-c5ba-11e9-8883-5e8667a59686.png)

Is there a way to sort the candidates having the shortest one at the top?

Thanks.

**Comment by abo-abo** [comment]
> First of all thanks for this amazing package.

You're welcome.

> Is there a way to sort the candidates having the shortest one at the top?

Of course. See this var:

```elisp
(defcustom ivy-sort-matches-functions-alist
  '((t . nil)
    (ivy-completion-in-region . ivy--shorter-matches-first)
    (ivy-switch-buffer . ivy-sort-function-buffer)))
```

As you see, I had the same idea. It's on by default for completion in region.

**Comment by iris-garcia** [comment]
That is awesome!

Thanks a lot for the quick answer, closing the issue.

**Comment by hmelman** [comment]
It would be nice if `ivy--shorter-matches-first` was a value option when customizing `ivy-sort-matches-functions-alist` the way `ivy--prefix-sort` is.

I think all the existing sorting functions should be value options as I find them hard to find since they don't have a common name prefix and some have double hyphens indicating they're for internal use.  Are `ivy--sort-files-by-date` and `ivy--flx-sort` valid here?

I was also confused by the fact that the functions that go in `ivy-sort-functions-alist` are comparison functions that take two values x and y and returns the "first" one and the functions in `ivy-sort-matches-functions-alist` take a name and a list of candidates returning a sorted list. These function signatures should be included in the doc strings of the two alists for anyone that wants to write a custom sorting function..

Finally the value in `ivy-sort-functions-alist` for "Plain sort" is `string-lessp`, should it be `ivy-string<`?

**Comment by basil-conto** [comment]
> Finally the value in `ivy-sort-functions-alist` for "Plain sort" is `string-lessp`, should it be `ivy-string<`?

It's probably safest to go with that, so I've done so in commit 781cbbc70adbe9cb6ce2db50bff511dd655644bd.

For your other concerns, please open a dedicated issue.
