### ISSUE TITLE
delegation with regex matchers

### ISSUE THREAD

**Issue by FelipeLema** [abo-abo/swiper#2218]
I'd like to be able to assign multiple matchers in which when the `n`th matcher has no candidates, `ivy` will call the `n`th +1 matcher with the original candidates.

why?

I frequently mis-type some of the first characters. By the time I realize that, the input is too messed up to match anything, and I have to backspace characters all the way to the beginning (or get my mind into "complex" editing mode).

I know `ivy--regex-ignore-order` exists, but I'd like to use it /only/ when I'm not currently having matches. I've not had the best UX with this matcher, since it takes a lot of characters to match the destination, so I try to avoid it as much as possible.

Since this is inconsistent and unpredictable behaviour I cannot switch between matchers beforehand.

API proposal:

Specify a list as a value in `ivy-re-builders-alist` instead of a symbol. Internally, pop matchers in a loop until we get a non-nil result (probably around `ivy--filter`.

**Comment by abo-abo** [comment]
I think it would complicate the API too much, while hurting consistency and ease of maintenance. Since I'm not sure what should happen when backspace is pressed. And I don't want to call external processes with different regexes because of a user's typo.

I suggest you play around with this advice for a while:

```elisp
(advice-add
 'ivy--filter
 :around
 (defun ivy--filter-with-redries (orig-fn name candidates)
   (let ((res (funcall orig-fn name candidates)))
     (or
      res
      (progn
        (setq ivy--regex-function #'ivy--regex-ignore-order)
        (funcall orig-fn name candidates))))))
```

If you like it, and it feels consistent, maybe we can figure out how to add it to ivy.
