### ISSUE TITLE
Single space swiper-isearch issue similar to #1554

### ISSUE THREAD

**Issue by Ergus** [abo-abo/swiper#2227]
Hi I am facing something similar to #1554 in swiper-isearch. When I add \ or \ I don't get any candidate at all. Even when there are some "foo dun". It does not work with "foo\ dun" or "foo\ dun" and with "foo dun" I get too many candidates as expected like "foo jhskdfjhksjdun".

**Comment by mookid** [comment]
I think that the problem is that you expect the regex constructed from the input "foo\ bar" to match "foo.* .*bar" while `(ivy--regex "foo\\ bar")` evaluates to `"\\(foo\\\\\\).*?\\(bar\\)"` (which matches foo, then a '\' character, then bar).

@abo-abo is that the expected semantics? this looks like a bug in `ivy--regex` to me.

**Comment by Ergus** [comment]
Hi:
Actually what I am trying to match is a string with one space in the middle, not two words in the same line with random things between them. Actually the problem is that the  \ does not scape the space... which is actually what I needed to do (and usually do in isearch with regex enabled).

**Comment by abo-abo** [comment]
With the default re-builder, you can enter literal spaces by adding one extra space. So you should enter `foo  bar` to search for `foo bar`.

**Comment by Ergus** [comment]
Ohh I see it works. I just discovered re-builder thanks to you...
