### ISSUE TITLE
Cannot set ivy-re-builders-alist

### ISSUE THREAD

**Issue by carrete** [abo-abo/swiper#2267]
This https://github.com/carrete/.emacs.d/blob/master/lisp/setup-ivy.el is how I have setup my use of ivy, swiper, and counsel. I'm at a loss to understand why `(setq ivy-re-builders-alist '((t . ivy--regex-fuzzy)))` has no effect until I highlight and eval this statement. I've tried moving this to `:config` (before and after `(ivy-mode t)`) and outside of `(use-package ivy ...` entirely. Only after I've started emacs, opened this file, highlighted this expression, and evaluated it does it ever take effect. What. Am. I. Doing. Wrong? Thanks!

**Comment by abo-abo** [comment]
Your issue seems to be with `use-package`. Try the built-in Emacs functions to see if it works:

```elisp
(require 'ivy)
(setq ivy-extra-directories nil)
(setq ivy-initial-inputs-alist nil)
(setq ivy-re-builders-alist '((t . ivy--regex-fuzzy)))
(setq ivy-use-virtual-buffers t)
(ivy-mode t)
```

Restart Emacs and eval `ivy-re-builders-alist` to check if it has the correct value.

You can also make use of this repo for testing:

```sh
git clone https://github.com/abo-abo/swiper/
```

Edit `targets/plain.el` to add `(setq ivy-re-builders-alist '((t . ivy--regex-fuzzy)))` and call `make plain` from the shell.

**Comment by MoHKale** [comment]
not sure if this is related but I'm having the same issue with `ivy-initial-inputs-alist`. I've set it up in my config like this:

```elisp
(use-package ivy
  :ensure t
  :defer nil
  :config
  (setq ivy-initial-inputs-alist '((counsel-minor . "^+")
                                   (counsel-package . "^+")
                                   (org-agenda-refile . "^")
                                   (org-capture-refile . "^")
                                   (Man-completion-table . "^")
                                   (woman . "^"))))
```

This was working fine until the recent update, however now the initial inputs seem to get reset to their `defcustom` value and I have no idea why? Running `describe-variable` on it gives the following output.

```
ivy-initial-inputs-alist is a variable defined in ‘ivy.el’.
Its value is shown below.

Documentation:
An alist associating commands with their initial input.

Each cdr is either a string or a function called in the context
of a call to ‘ivy-read’.

You can customize this variable.

Value:
((counsel-org-capture . "^")
 (counsel-M-x . "^")
 (counsel-describe-function . "^")
 (counsel-describe-variable . "^")
 (counsel-minor . "^+")
 (counsel-package . "^+")
 (org-agenda-refile . "^")
 (org-capture-refile . "^")
 (Man-completion-table . "^")
 (woman . "^"))
Original value was 
((org-refile . "^")
 (org-agenda-refile . "^")
 (org-capture-refile . "^")
 (Man-completion-table . "^")
 (woman . "^"))

[back]
```

so it seems like something in ivy is resetting the value I set after the fact or perhaps new values are being pushed onto it but I don't know why `org-refile` is in my alist but not in the final value if that's the case.

**Comment by MoHKale** [comment]
Update:

okay, dumb mistake on my part, I used `counsel-describe-variable` at startup to inspect the initial inputs variable, but it was counsel that was introducing new values to it. so when I loaded it, it always seemed to have been changed & I assumed that was because of ivy. my bad. Ignore my last comment.

**Comment by carrete** [comment]
Thanks for your kind attention to this @abo-abo!

**Comment by carrete** [comment]
Turns out `ivy-prescient.el` was to blame. https://github.com/raxod502/prescient.el/issues/45#issuecomment-546194457

**Comment by abo-abo** [comment]
@carrete Thanks for the follow-up.

**Comment by apc** [comment]
I'm running into this issue again. Adding `(require 'ivy)` to the top of my init seems to fix it. Putting this here in case it helps anyone else.

**Comment by basil-conto** [comment]
@apc You shouldn't have to `(require 'ivy)` in your `user-init-file`, so that's not really a solution.

What's the exact issue you're running into?  If it's that your setting `ivy-re-builders-alist` gets overwritten after loading some other package like `counsel`, then the solution is to defer modifying `ivy-re-builders-alist` until after that package has loaded, using the built-in [`with-eval-after-load`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Hooks-for-Loading.html), the `use-package` `:config` keyword, or similar.

**Comment by apc** [comment]
@basil-conto Thanks for your comment. Yes, that's the issue (had been using this for about a year without running into this, so some update must have changed something). Somehow `ivy-re-builders-alist` is getting overridden. 

Is there an easy way to figure out which package is changing that value? A quick search through this repository for `ivy-re-builders-alist` gives me the impression that the none of `swiper` or `counsel` are trying to set the value of `ivy-re-builders-alist`. But maybe there's some other way the variable could be getting overwritten by those packages?

**Comment by basil-conto** [comment]
> But maybe there's some other way the variable could be getting overwritten by those packages?

Not by these specific packages I don't think, no. But `ivy-prescient` modifies it.

> Is there an easy way to figure out which package is changing that value?

Depends on your setup I guess.

One way is to recursively bisect your `user-init-file` by commenting out parts of it until you narrow down to possible culprits.

You can also manually load packages in batches and check the variable's value each time.

Alternatively, you can try automating this, e.g.:

```el
;;; my-watch.el -*- lexical-binding: t -*-

(defvar my-original)
(defvar warning-minimum-log-level)

(defun my-watcher (_sym val op where)
  (let ((warning-minimum-log-level :debug))
    (lwarn 'ivy :debug "op: %s buffer-local: %s load: %s\n  %s\n%s"
           op where load-file-name val (with-output-to-string (backtrace)))))

(defun my-after-load (file)
  (and (boundp 'my-original)
       (not (equal ivy-re-builders-alist my-original))
       (let ((warning-minimum-log-level :debug))
         (lwarn 'ivy :debug "file: %s\n  old %s\n  new %s"
                file my-original ivy-re-builders-alist))))

(with-eval-after-load 'ivy
  (setq my-original ivy-re-builders-alist))

(add-hook 'after-load-functions #'my-after-load)
(add-variable-watcher 'ivy-re-builders-alist #'my-watcher)

;;; my-watch.el ends here
```

You can load this before your `user-init-file`, e.g. with `emacs -Q -l /path/to/my-watch.el -l /path/to/init.el`. Ideally it should print some debug info to the `*Warnings*` buffer if `ivy-re-builders-alist` changes, though it's possible for it to go undetected.

Finally, you can recursively search your `user-emacs-directory` for any mentions of `ivy-re-builders-alist`, e.g.:
1. `emacs -Q`
2. `M-: (cd user-emacs-directory) RET`
3. `M-x rgrep RET ivy-re-builders-alist RET *.el RET RET`

HTH.

**Comment by apc** [comment]
Thanks so much, once again. I am running `ivy-prescient`, but disabling it didn't make a difference. What did make a difference was moving the setting of the variable to the `:config` section of `use-package`.  ¯\_(ツ)_/¯

I used your watcher file to see what was happening (while leaving the variable assignment in in the `:custom` section of the `ivy` declaration and while removing the call for `ivy-prescient`), and from looking at the `*Warnings*` buffer, the only thing that's setting the value of `ivy-re-builders-alist` is `elpa/ivy-20210311.1638/ivy.elc`. 

Could this be all due to the fact that `ivy-re-builders-alist` is introduced with `defvar` and not `defcustom`? I mean, could it be that somehow variable values set under `:custom` are overwritten by a package whenever the variable is first assigned a value using `defvar` but not when using `defcustom`?

**Comment by basil-conto** [comment]
> What did make a difference was moving the setting of the variable to the `:config` section of `use-package`

Yes, that's the `eval-after-load` mechanism at play: if loading a package overwrites something (which ideally it shouldn't), then you can overwrite the overwrite by evaluating your overwrite after said package has loaded.

> Could this be all due to the fact that `ivy-re-builders-alist` is introduced with `defvar` and not `defcustom`? I mean, could it be that somehow variable values set under `:custom` are overwritten by a package whenever the variable is first assigned a value using `defvar` but not when using `defcustom`?

I don't know, but I guess so. `use-package` has started using some custom theme hacks since I last used it, maybe there's some interplay with that.  Either way my impression is that `:custom` is mostly intended for use with user options, not plain variables. You'd have to macroexpand your `use-package` stanzas and do some step or print debugging to know for sure (or ask the `use-package` devs).
