### ISSUE TITLE
Ivy breaks when resize-mini-windows = t

### ISSUE THREAD

**Issue by PythonNut** [abo-abo/swiper#230]
I have `(setq resize-mini-windows t)` in my init because it makes editing large amounts of text in the minibuffer more convenient.

Unfortunately, with that set, `ivy` fails to display any candidates (don't know why). Would temporarily setting it to `nil` fix this?

**Comment by abo-abo** [comment]
`resize-mini-windows` is bound to nil temporarily in `ivy--insert-minibuffer` - the main function that inserts text into the minibuffer.  That's the only setting that was working well for me, since I resize the minibuffer manually pixel-wise to fix the text.  `ivy--insert-minibuffer` is run from minibuffer's `post-command-hook`.

If you know a better way, let me know. I do currently have some problems with resizing the minibuffer after a recursive-edit style completion with this method.

**Comment by PythonNut** [comment]
@abo-abo is there any master wrapping function where you can temporarily let-bind `resize-mini-windows`? If you can think of one, I can test it out.

**Comment by PythonNut** [comment]
@abo-abo the following fix works for me:

```emacs
(defun nadvice/ivy-read (old-fun &rest args)
    (let ((resize-mini-windows nil))
      (apply old-fun args)))

(advice-add 'ivy-read :around #'nadvice/ivy-read)
```

**Comment by abo-abo** [comment]
Yes, this should be good enough. All completion goes through `ivy-read`. Let me know if you get any problems with it.
