### ISSUE TITLE
completing-read REQUIRE-MATCH with empty directories

### ISSUE THREAD

**Issue by equwal** [abo-abo/swiper#2368]
I have dotfiles hidden in my ivy completion (I'm not sure what variable it is that sets this).

So trying to open a directory using this code example:
```emacs-lisp
(make-directory "~/empty-dir/")
(read-directory-name "New directory: " "~/empty-dir" nil t)
```
will result in an annoying prompt `New directory (match required): ~/empty-dir/`.

This can be exited with `ivy-alt-done`, but it should work as if the dotfile `.` (this directory) were selected.

The above code example is adapted from some code in sly which is bugged because of this issue. Naturally the owner of that repo would prefer the issue be fixed upstream.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by basil-conto** [comment]
I am currently working on fixing how Ivy handles the `require-match` argument in general, which has historically been wrong or at least incompatible with vanilla Emacs.

The fix for this issue checks whether `require-match` is non-`nil` for a specific edge case, but I'm finding it difficult to understand the logic of the fix, and why it was needed.

In particular, I'm struggling to reproduce the recipe in the original report. I have tried the following with old Ivy versions (circa 13.0 and 13.1) and also old Emacs versions (24.5), but it always seems to work as I'd expect, with or without the patch claiming to fix this issue:

1. `make plain`
2. `(setq ivy-extra-directories ()) C-j`
3. `(make-directory "~/empty-dir/") C-j`
4. `(read-directory-name "New directory: " "~/empty-dir" nil t) C-j C-m`

This always gives me `"/home/blc/empty-dir"`.

What am I missing?

I'm thinking of reverting the commit in question because its handling of `require-match` is dubious and because the test suite succeeds either way. Can someone convince me why I shouldn't?

Thanks.
