### ISSUE TITLE
refresh the list of ivy-resume

### ISSUE THREAD

**Issue by c02y** [abo-abo/swiper#2372]
For instance, I search a keyword in the buffer using `swiper`, hit `Enter` to edit or delete the line, execute `ivy-resume` to restore the list, the list is still the original one, which one of the line is edited or deleted.

How to refresh the list of `swiper` in `ivy-resume` session or is there any variable that I can use to refresh the list automatically whenever I execute `ivy-resume`?

**Comment by abo-abo** [comment]
Nice suggestion, thanks.

Some notes for a future implementation:

- We could save the initial `buffer-size` then check if it changed in swiper's hook in `ivy-resume`.
- We should somehow re-use `swiper-occur`, since it "knows" how to refresh the candidates

I think a major refactor is needed of `ivy-configure :occur`, where getting the list of candidates should be separated from inserting the list of candidates into the buffer.

**Comment by c02y** [comment]
I just came from helm(replace helm layer with ivy layer in Spacemacs), and a note for the refresh:

please keep the position of the point in the list(the same index?), do not put the point to the beginning of the list after the refresh

**Comment by basil-conto** [comment]
> We could save the initial `buffer-size` then check if it changed in swiper's hook in `ivy-resume`.

I think modification count is more appropriate than `buffer-size` here; see [`(info "(elisp) Buffer Modification")`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Buffer-Modification.html).

**Comment by abo-abo** [comment]
Thanks, this is now fixed for `swiper-isearch`. Please test.

I think implementing this for `swiper` doesn't make sense right now. I'm using `swiper-isearch` for over a year now: I can't think of a scenario where `swiper` is better than `swiper-isearch`.

**Comment by basil-conto** [comment]
> I can't think of a scenario where `swiper` is better than `swiper-isearch`.

One scenario is that `counsel-grep-or-swiper` exclusively uses the former.

**Comment by abo-abo** [comment]
> One scenario is that `counsel-grep-or-swiper` exclusively uses the former.

Thanks. Does it make sense to:

- keep it as is
- change to `swiper-isearch` unconditionally
- introduce a `defcustom`?

Maybe in the future we might phase out the original `swiper`, and make `swiper-isearch` take over the name.  What do you think? Any case where `swiper` is better than `swiper-isearch`?

**Comment by basil-conto** [comment]
I'm probably not the right person to ask, because until you just mentioned that in your opinion `swiper-isearch` is superior to `swiper`, I had never even tried `swiper-isearch`, let alone studied how it works. In fact, `counsel-grep-or-swiper` is the only key I have bound in my config.

If you think they effectively provide the same functionality, and no functionality would be lost in switching to `swiper-isearch`, then `swiper` could definitely become the new name of `swiper-isearch`, with `swiper-isearch` provided as an alias of `swiper`, and the old `swiper` renamed to something like `swiper-ivy` or `swiper-legacy` or I don't know what.

If that seems too disruptive, or if they're similar but not entirely interchangeable, then for every command (like `counsel-grep-or-swiper`) that can use either `swiper` or `swiper-isearch`, a new user option would probably be easier then defining new `counsel-grep-or-swiper-isearch` commands.

Do users of `swiper-isearch` ever use `swiper`? Perhaps a new issue should be opened asking this question and discussing future approaches.

**Comment by c02y** [comment]
Sorry guys, forgot the update of this issue for some reason.

Just got annoyed by this problem again and again.

`swiper-isearch` did refresh the `ivy-resume` list, thanks.

And I just tried `counsel-grep-or-swiper` mentioned by @basil-conto , it doesn't auto refresh the `ivy-resume` list, I'll use `swiper-isearch` instead.
