### ISSUE TITLE
 [Question] Why prefer swiper over counsel-grep?

### ISSUE THREAD

**Issue by ianpan870102** [abo-abo/swiper#2390]
[Question]
I'm rather new to the ivy/counsel package family. Why would one prefer swiper over counsel-grep? The latter seems significantly faster than the former.
The only obvious advantage of swiper that I noticed is the better syntax highlighting -- is this all?

**Comment by mohkale** [comment]
In truth I find `swiper` to be faster as well... perhaps it's just because I'm running on windows and grep through cygwin is slower there, but there are other advantages.

# swiper is implemented entirely in elisp. 

This means like you mentioned the highlighting of matches is exactly the same as it would be shown in emacs; but more than that searches get added to your kill-ring and if your using evil then it updates your evil search pattern... I'm not sure whether the same is done with grep (or even whether it can be) because of regexp differences between the emacs and grep. 

# swiper can use different regex-types supported by ivy

Swiper also supports `ivy-hydra` which allows to you change the regexp type swiper uses. meaning you can fuzzy search, order independent search, literal search and of course the regular ivy search we've come to love. Grep we'll only let you search the way grep does and I don't believe there's an interactive way to toggle the search. The only difference changing the search-type does to `counsel-grep` is the coloring of output, but even that fades when you move candidates. It isn't the same.

Here's a screenshot of me using the fuzzy finding capabilities with swiper... honestly I don't think it's as quick as fuzzy finder, but it's reasonably fast on my 13000 line config so I'm not complaining.

![fz](https://user-images.githubusercontent.com/23294780/71698061-f7ea2500-2db1-11ea-9f25-4804c38e4e78.PNG)

**Comment by Alexander-Shukaev** [comment]
See #1908 for previous discussion.  I configured `counsel` in a way that it only uses `grep` apart from for file-less buffers.  However, even for file-less buffers we could just pipe the contents of a file-less buffer to `grep`, and I believe that it would be a nice feature to add.  The big advantage now is that `grep` is invoked asynchronously (see how `counsel-grep-function` calls `counsel--async-command`), so unlike `swiper`, it won't freeze your Emacs while collecting matches.

In order to support fuzzy search, the only change that needs to be done is in `counsel-grep-function`, where

```
   (let ((regex (counsel--elisp-to-pcre
                 (setq ivy--old-re
                       (ivy--regex string)))))
```

should be replaced by

```
   (let ((regex (counsel--grep-regex string)))
```

which would be consistent with `counsel-ag-function` as per #1801.  In general, there needs to be some refactoring done on all of those search functions that invoke external search tools like `grep`, `ag`, `rg`, and etc., in order for all of them to be consistent in their behavior.  They were all developed in different times by different people, hence the confusion.

As a result, the only advantage to use pure `swiper` over `grep` would only be the absence the latter on the box.

**Comment by abo-abo** [comment]
Thanks for the question and the nice answers. Closing.

**Comment by Alexander-Shukaev** [comment]
@abo-abo, I'm still waiting for my copyright assignment, would you mind to install the suggested change in `counsel-grep-function`?

**Comment by abo-abo** [comment]
@Alexander-Shukaev Updated, thanks.
