### ISSUE TITLE
counsel-locate-cmd-es partially broken

### ISSUE THREAD

**Issue by technician77** [abo-abo/swiper#2393]
It seems there is something wrong with this function, but I can't fully grasp what it is. When running it gives _**some**_ results but most of them that it should show it does not. Using the changed function below it works as expected but I'm not sure what the consequences are since it looks a lot shorter and I'm no programmer. Could you look into that?

```
    (defun counsel-locate-cmd-es (input)
      "Return a shell command based on INPUT."
      (counsel-require-program "es.exe")
      (format "es.exe -r %s"
              (counsel--elisp-to-pcre
               (ivy--regex input t))))))
```
Function above extracted from here:
[https://github.com/termitereform/JunkPile/blob/master/emacs-on-windows.md](https://github.com/termitereform/JunkPile/blob/master/emacs-on-windows.md)

**Comment by abo-abo** [comment]
Maybe some command switches don't work with your version of `es.exe`. Please test this function:

```elisp
(defun counsel-locate-cmd-es (input)
  "Return a shell command based on INPUT."
  (counsel-require-program "es.exe")
  (let ((raw-string (format
                     ;; old: "es.exe -i -r -p %s"
                     "es.exe -r %s"
                     (counsel--elisp-to-pcre
                      (ivy--regex input t)))))
    ;; W32 don't use Unicode by default, so we encode search command
    ;; to local codepage to support searching filename contains non-ASCII
    ;; characters.
    (if (and (eq system-type 'windows-nt)
             (boundp 'w32-ansi-code-page))
        (encode-coding-string raw-string
                              (intern (format "cp%d" w32-ansi-code-page)))
      raw-string)))
```

**Comment by technician77** [comment]
The gui version was always 1.4.1.935 (x64). The cli version I had was outdated, it was ES 1.1.0.10, current is  ES 1.1.0.16. But that was not relevant. The error occurs als in the new version.

I've tested the shortened version from above successfully, results are as expected. It seems even the -i option can stay in it without causing a problem. So just the -p seems to break it.

It seems there is also a problem with the German umlauts. If I would search for foo a result might show like this foo\224bar instead of fooöbar. Additionally searching using a word containing an Umlaut is causing error code 127.

**Comment by abo-abo** [comment]
The "-p" flag was added in #1633.

@et2010 @cireu does the "-p" flag work properly for you? Do you have problems with unicode file names?

**Comment by cireu** [comment]
>  Using the changed function below it works as expected but I'm not sure what the consequences are since it looks a lot shorter and I'm no programmer.

`-p` means matching the whole path (e.g. "C:\Users\foobar\qux.txt")instead of matching filename only("qux.txt"), so the result may contains some "noise".

For the coding issue, you should give more information such as `M-x describe-variable RET w32-ansi-code-page RET`. For a Win10 user, a quick solution is enable the unicode support https://stackoverflow.com/questions/56419639/what-does-beta-use-unicode-utf-8-for-worldwide-language-support-actually-do

counsel use the process mechanism of Emacs to call es.exe, and the process mechanism was delegated to cmd proxy in Windows system. However, cmd proxy won't respect the coding settings from Emacs and it will force the program to use [ANSI code page](https://en.wikipedia.org/wiki/Windows_code_page#ANSI_code_page), which is described in variable `w32-ansi-code-page`.

My ansi code page is 936(GBK), it's a coding system for East-Asian text, so lacks of umlauts support and result in `foo?bar`.  After open the unicode support, my ansi code page is 65001(UTF-8), and can display it now.

**Comment by jammid** [comment]
Switching the order of the -p and -r flags seems to fix this.

`"es.exe -i -p -r %s"` works as expected.

**Comment by abo-abo** [comment]
@jammid Thanks.
@technician77 Please test and confirm if it works now.

**Comment by technician77** [comment]
First the solution from jammid seems to work. Thanks for pointing that out jammid.

Can anyone explain how the -p parameter affects the search and how it is used? I tried my best but can't see any difference whatever I try. The manual says "Match full path and file name."
