### ISSUE TITLE
Swiper - navigation between matches on same line

### ISSUE THREAD

**Issue by svenssonaxel** [abo-abo/swiper#2396]
An entry in swiper overview represents a line containing at least one match, rather than one individual match. That's probably good.

However, for very long lines, it would be nice to have a way to _navigate between the matches on the same line_. Without this functonality, swiper cannot fully replace `isearch`.

**Comment by lmintmate** [comment]
There's a swiper command other than the default, that works a lot more like isearch, including being able to go to the next match in the same line, called `swiper-isearch`. If you like the isearch behavior you can bind that one to the search combination (usually C-s) instead of the regular swiper command (you can read more about it [here](https://oremacs.com/2019/04/07/swiper-isearch/)).

**Comment by abo-abo** [comment]
Thanks for answering, closing as resolved.
