### ISSUE TITLE
Exit swiper when using RET

### ISSUE THREAD

**Issue by vincentbernat** [abo-abo/swiper#242]
Hey!

When searching and no match is found, when pressing RET, I get "match required". I would have expected that the search would just end, like with regular isearch. Also, exiting with arrows would be nice.

**Comment by abo-abo** [comment]
I disagree with isearch behavior in this case. Not only does it move point on bad input, it also puts that input on history.  The use of `:require-match` is appropriate for swiper, since you have to select one of the lines in the buffer.  If you make a typo and press <kbd>RET</kbd>, "match required" works as a good reminder and a transaction barrier, so that the original input doesn't disappear and bad input doesn't get put on the history.

You can still quit with <kbd>C-g</kbd> as usual, or additionally <kbd>C-a DEL</kbd>.

As for arrows, I disagree here as well: navigating the input with <kbd>C-f</kbd>/<kbd>C-b</kbd> (or the corresponding arrows) is much more powerful than just quitting.  You can modify `ivy-minibuffer-map` for this if you really want, but I highly recommend to try it the way it is now.

**Comment by vincentbernat** [comment]
As for the first point, the case is that you start to type some prefix which makes you go to some point of the document. Then you continue but there is no successful search. However, you are still interested in the first point you discovered. As far as I can tell, there is now way to stay here. If you use <kbd>C-g</kbd>, you will go back to the point before the search. On the other hand, with isearch, I can stay here with <kbd>RET</kbd>, or cancel the whole thing with <kbd>C-g</kbd>.

**Comment by abo-abo** [comment]
> However, you are still interested in the first point you discovered.

In that case, you should correct the typo with <kbd>DEL</kbd>. This is very natural when entering text, so it should be fine for completion as well.
