### ISSUE TITLE
Lisp eval depth error when running ivy-read on Emacs 27

### ISSUE THREAD

**Issue by daviwil** [abo-abo/swiper#2436]
Hi @abo-abo!

While trying to upgrade from Emacs 26 to 27 I've encountered an error in Ivy on Emacs 27 that occurs as soon as I try to run any command that invokes `ivy-read`:

```
Error in post-command-hook (ivy--queue-exhibit): (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")
```

I can reproduce this even when invoking it myself:

```
(ivy-read "Test" '("one" "two"))
```

I've looked for other reports of this issue but haven't seen anything yet.  Do you have any idea what might be causing it?  This is using Ivy 0.13.0 and Emacs 27.0.50 (commit 36abf68) releases packaged with [Guix](https://guix.gnu.org).

Thanks!

**Comment by daviwil** [comment]
It appears that this is being caused by something in Guix.  I was able to boil this down to a simple init.el that only tries to load Ivy with no other external packages in the load path and it worked fine.  If my investigations lead me back to Ivy's code I'll reopen this.  Thanks!

**Comment by abo-abo** [comment]
There is indeed a bug in Emacs27 somewhere. I can fix it in my config with this hack, putting the code early in the init:

```elisp
(require 'cl-seq)
(cl-reduce (lambda (a b)) '(0 0))
```

**Comment by analyticd** [comment]
I get this runtime error too with Emacs 27. Using Nix (similar to Guix) here but I don't know that that is relevant. I tried abo-abo's hack/fix to get around this, but for me it doesn't work. Just leaving the information here for future readers.

**Comment by basil-conto** [comment]
> `(require 'cl-seq)`

Note that, in general, you should only ever load `cl-lib`, as the organisation of the other `cl-*` packages is an internal implementation detail subject to change.

---

As for the error in Emacs 27: please try deleting and reinstalling (and recompiling) Ivy or better yet all your external packages. Try reproducing the error with the latest development version of Ivy starting with `make plain` or `emacs -Q`. Is the issue affected by byte-compilation? I.e., does it occur regardless of whether Ivy is byte-compiled?

If you think the bug lies with Emacs itself, please report it via `M-x report-emacs-bug`. If you build Emacs yourself, please try a fresh build using `make bootstrap` first.
