### ISSUE TITLE
Error while using counsel-git-grep

### ISSUE THREAD

**Issue by xelibrion** [abo-abo/swiper#2479]
Hi, 

It seems there's a bug snuck in in one of the recent releases. 
I started to get `Symbol's value as variable is void: ivy-regex` when I updated `counsel` and `counsel-projectile` from `20191127.1040` to `20191127.1040`.

Did not touch version of ivy, but maybe I should have? Anyway, reverting the upgrade fixed the issue.

**Comment by ambihelical** [comment]
I can't personally reproduce this with today's melpa packages.  However I always take all the updates that are available.  Sometimes there are dependencies and things break otherwise.  Also those two versions you gave are identical.

That error indicates ivy didn't load for some reason.  Maybe there was an error in *Messages* you didn't notice?

**Comment by abo-abo** [comment]
Try re-installing `ivy` and `counsel` and restarting Emacs.

**Comment by xelibrion** [comment]
@abo-abo thanks for the suggestion, this resolved the problem. Closing the issue
