### ISSUE TITLE
Return key doesn't work in a resumed ivy session

### ISSUE THREAD

**Issue by aashwin-rs** [abo-abo/swiper#2500]
When I press RET or C-m to select a candidate in the minibuffer that was brought up using `ivy-resume`, the minibuffer will abruptly close without carrying out the action. My ivy, swiper and counsel is setup as follows.

    (setq enable-recursive-minibuffers t)
    (require 'ivy)
    (define-key ivy-mode-map (kbd "C-c r") 'ivy-resume)
    (require 'swiper)
    (define-key ivy-mode-map (kbd "C-s") 'swiper)
    (require 'counsel)
    (define-key counsel-mode-map [rebind insert-char] 'counsel-unicode-char) ;; (kbd "C-x 8 <RET>")
    (define-key counsel-mode-map (kbd "C-c g") 'counsel-git)
    (define-key counsel-mode-map (kbd "C-c j") 'counsel-git-grep)
    (define-key counsel-mode-map (kbd "C-c k") 'counsel-ag)
    (define-key counsel-mode-map (kbd "C-x l") 'counsel-locate)
    (define-key ivy-minibuffer-map (kbd "C-r") 'counsel-minibuffer-history)
    (counsel-mode 1)
    (ivy-mode 1)

**Comment by basil-conto** [comment]
I cannot reproduce this from `emacs -Q` using the setup you provide. Please try reproducing this from `emacs -Q`, so as to rule out issues in the rest of your configuration, and providing a detailed reproduction recipe that we can use to debug the issue.

**Comment by aashwin-rs** [comment]
After running `emacs -Q` I did the following:
````
M-x package-initialize <RET>
M-x ivy-mode <RET>
M-x eval-expression <RET> (define-key ivy-mode-map (kbd "C-c r") 'ivy-resume) <RET>
M-x package-install json-mode <RET>
C-r C-a C-k cobol-mode <RET>
````
After the last use of return, the minibuffer closed and cobol-mode was not installed. No messages were produced from this action.

**Comment by abo-abo** [comment]
@aashwin-rs This is expected behavior: `ivy-resume` does not work for built-in commands, like `package-install`.

It does however work for `counsel-package`: that's one of the reasons why we have the `counsel-` wrappers. They decouple the `:action` from `completing-read` so that it can be used multiple times.

**Comment by basil-conto** [comment]
Thanks, here's a simpler illustration of the problem:

1. `make plain`
2. ```el
   (defun foo ()
     (interactive)
     (message ">>> %s" (completing-read "" '("a"))))
   ```
   <kbd>C-M-x</kbd>
3. <kbd>M-x</kbd>`foo`<kbd>RET</kbd><kbd>RET</kbd>
   Result: `>>> a` is displayed in the echo area
4. <kbd>C-c</kbd><kbd>C-r</kbd><kbd>RET</kbd>
   Result: `>>> a` does not get displayed in the echo area

This result is actually expected, because `ivy-resume` is limited to supporting only those functions that call `ivy-read` directly with a meaningful `:action` keyword. This excludes all commands, including `package-install`, that use the standard built-in [`completing-read`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Completion.html) function.

This is a known limitation of `ivy-resume`, and in fact it even tries to inform the user of it:

https://github.com/abo-abo/swiper/blob/92e5a953408447f013f9f976052c772aa2581389/ivy.el#L1257-L1261

The bug here is that `ivy-read` unconditionally sets the `:action` keyword to a non-`nil` value:

https://github.com/abo-abo/swiper/blob/92e5a953408447f013f9f976052c772aa2581389/ivy.el#L2234

so `ivy-resume` doesn't notice that `package-install` is actually incompatible with it, and the user doesn't get an error message.

**Comment by basil-conto** [comment]
@abo-abo 

> This is expected behavior

That `ivy-resume` doesn't support `package-install` is indeed expected, but the user should get an error message.

**Comment by abo-abo** [comment]
I've added an error message in case the action is `identity`.

**Comment by basil-conto** [comment]
Thanks.
