### ISSUE TITLE
Counsel analogue of helm-apropos

### ISSUE THREAD

**Issue by c02y** [abo-abo/swiper#2509]
I came from helm, and I love the command `helm-apropos` which is pre-configured to describe commands, functions, variables and faces - all in one command, I thought `counsel-apropos` is the same thing, but `counsel-apropos` is totally different, although `counsel-apropos` will show the list containing commands, functions and variables and faces, so I can search a keyword in the prompt, but the result is basically useless.

Fox instance I need to check the value of a variable called major-mode, this is the result of `M-x counsel-apropos <RET> major-mode <RET>`
~~~
Type M-x apropos-follow on a type label to view its full documentation.

major-mode
  User option: Symbol for current buffer’s major mode.
  Properties: cl-generic--context-rewriter standard-value
              variable-documentation custom-type

~~~
What am I gonna do with this content? I'll just try to use `M-x counsel-desribe-variable` again.

What I need is this, this is the result of `M-x counsel-describe-variable`:
~~~
major-mode is a variable defined in ‘C source code’.
Its value is ‘emacs-lisp-mode’
Original value was ‘fundamental-mode’
Local in buffer funcs.el; global value is turn-on-evil-mode

  Automatically becomes buffer-local when set.
  You can customize this variable.

Documentation:
Symbol for current buffer’s major mode.
The default value (normally ‘fundamental-mode’) affects new buffers.
A value of nil means to use the current buffer’s major mode, provided
it is not marked as "special".

[back]

~~~

so I can get the value of the variable, the doc of the variable, and the definition link of the variable.

`helm-apropos` does this for all describe commands, functions, variables and faces in one command, that is the beautify of `helm-apropos`, why can not `counsel-apropos` do the same. so I have to use `counsel-describe-variable`, `counsel-descbinds`, `counsel-commands`, `counsel-decsribe-function`, `counsel-faces` separately?

So my question:
1. Can `counsel-apropos` combine all describe commands, functions, variables and faces in one command into one command like `helm-apropos`
2. The result of `counsel-apropos` should be exactly like individual `counsel-describe-variable`/`counsel-descbinds`/`counsel-commands`/`counsel-decsribe-function`/`counsel-faces`

**Comment by basil-conto** [comment]
> Useless counsel-apropos

That you don't understand how to use something or its purpose does not make it useless, which is quite a strong and, in this case, inaccurate conclusion.

> the command `helm-apropos` which is pre-configured to describe commands, functions, variables and faces - all in one command

This is not what "apropos" means in Emacs. In Emacs terms, apropos commands display a list summarising all symbols whose name or docstring matches a given search regexp, similarly to the `--apropos` flag that the Unix `man` utility takes.

Examples of such apropos commands are `apropos-command` (bound to <kbd>C-h</kbd><kbd>a</kbd> by default), `apropos`, `apropos-user-option`, etc. Please see [`(info "(emacs) Apropos")`](https://www.gnu.org/software/emacs/manual/html_node/emacs/Apropos.html) for more information.

In Emacs terms, what `helm-apropos` does is actually called `M-x describe-symbol`, aka <kbd>C-h</kbd><kbd>o</kbd> by default. Please see [`(info "(emacs) Help Summary")`](https://www.gnu.org/software/emacs/manual/html_node/emacs/Help-Summary.html) and [`(info "(emacs) Name Help")`](https://www.gnu.org/software/emacs/manual/html_node/emacs/Name-Help.html).

> that is the beautify of `helm-apropos`, why can not `counsel-apropos` do the same

Because `counsel-apropos` is a Counsel wrapper around the built-in `apropos` command. If you want the functionality of `describe-symbol`, then use that instead. If you want a Counsel wrapper around `describe-symbol`, then please ask for that politely.

> 1. Can `counsel-apropos` combine all describe commands, functions, variables and faces in one command into one command like `helm-apropos`

I hope I have already explained how/why `counsel-apropos` already combines a summary of all relevant commands, functions, variables, faces, etc. as intended.  As a further illustration, here's the result of calling <kbd>M-x</kbd>`counsel-apropos`<kbd>RET</kbd>`quit window`<kbd>C-M-j</kbd>:

```
Type RET on a type label to view its full documentation.

quit-restore-window
  Function: Quit WINDOW and deal with its buffer.
quit-window
  Command: Quit WINDOW and bury its buffer.
  Properties: event-symbol-element-mask event-symbol-elements
              modifier-cache
quit-window-hook
  User option: Hook run before performing any other actions in the
               ‘quit-window’ command.
  Properties: standard-value custom-type custom-version
              variable-documentation custom-requests
quit-windows-on
  Command: Quit all windows showing BUFFER-OR-NAME.
```

> 2. The result of `counsel-apropos` should be exactly like individual `counsel-describe-variable`/`counsel-descbinds`/`counsel-commands`/`counsel-decsribe-function`/`counsel-faces`

No, it should not, because that's not what `apropos` does in Emacs. If you would like a wrapper around `describe-symbol`, than it would be called `counsel-describe-symbol`, not `counsel-apropos`.

**Comment by basil-conto** [comment]
> What am I gonna do with this content? I'll just try to use `M-x counsel-desribe-variable` again.

You don't need to; you can navigate between buttons in the apropos buffer using <kbd>TAB</kbd> and <kbd>&lt;backtab&gt;</kbd>, and you can type <kbd>RET</kbd> or click on the buttons to pop up the symbol's docstring.

**Comment by c02y** [comment]
> > 1. The result of `counsel-apropos` should be exactly like individual `counsel-describe-variable`/`counsel-descbinds`/`counsel-commands`/`counsel-decsribe-function`/`counsel-faces`

> 
> No, it should not, because that's not what `apropos` does in Emacs. If you would like a wrapper around `describe-symbol`, than it would be called `counsel-describe-symbol`, not `counsel-apropos`.

Is any any wrap like `counsel-all-in-one` do the things `helm-apropos` does?



> > What am I gonna do with this content? I'll just try to use `M-x counsel-desribe-variable` again.
> 
> You don't need to; you can navigate between buttons in the apropos buffer using TAB and <backtab>, and you can type RET or click on the buttons to pop up the symbol's documentation.

Yeah, sorry, didn't realize that, but first of all, I have to switch to the "*Apropos*" buffer manually since the point is not in there after I execute `counsel-apropos`, I can write a wrapper. But secondly, I have to `TAB` and `RET` on the buffer, I really don't like to use `counsel-apropos` because of these two reasons.

So is there any existed wrapper behaving exactly like `helm-apropos`?

**Comment by basil-conto** [comment]
> Is any any wrap like `counsel-all-in-one` do the things `helm-apropos` does?

Not yet, but until there is, you can use the built-in `describe-symbol` which is bound to <kbd>C-h</kbd><kbd>o</kbd> by default.

PR #2542 adds a Counsel wrapper around `describe-symbol`; please check whether it does what you describe.

**Comment by basil-conto** [comment]
Note that `describe-symbol`, and by extension `counsel-describe-symbol`, is extensible via the variable `describe-symbol-backends`. By default, Emacs comes with 5 backends:

* `describe-function`
* `describe-variable`
* `describe-face`
* `cl-describe-type` (for [classes](https://www.gnu.org/software/emacs/manual/html_node/eieio/))
* `ert-describe-test` (for [ERT tests](https://www.gnu.org/software/emacs/manual/html_node/ert/index.html))

**Comment by c02y** [comment]
`describe-symbol` is good to me, thanks.
