### ISSUE TITLE
Calling `ivy-resume` after exiting a `counsel-imenu` session puts entire line into history

### ISSUE THREAD

**Issue by leungbk** [abo-abo/swiper#2534]
Related to https://github.com/abo-abo/swiper/issues/2533 and caused by https://github.com/abo-abo/swiper/commit/829cf8a55007df6318b1d34d150fc9aac6cc2f8a. cc @kiennq

**Comment by kiennq** [comment]
With `make plain` I cannot seems to repro this.
Do you have sample file and step by step repro?

I cannot repro with this sample
``` cpp
struct Test1
{
    Test1();
    ~Test1();
    void A();
    void B();
    void C();
};

struct Test2
{
};

Test1::Test1(){}
Test1::~Test1(){}
void Test1::A(){}
void Test1::B(){}
void Test1::C(){}

void Another(){}
void AnotherAnother(){}
```

After go to `counsel-imenu` and select an entry, only that entry is inserted into history, not the entire source line.

Or the expectation is only the typed characters should be in history instead of the candidate entry?

**Comment by leungbk** [comment]
Oh, sorry, I meant the entire line of the entry. I should have been more careful there.

> Or the expectation is only the typed characters should be in history instead of the candidate entry?

Yes, that's how the behavior was previously.
