### ISSUE TITLE
`M-o` action interface doesn't allow for resuming like `g` in `C-o` interface

### ISSUE THREAD

**Issue by tsdh** [abo-abo/swiper#254]
Ups, that issue has become a bit longer than I intended.  Here's the short version: I'd like to have a means to invoke an action with `M-o` without being done, i.e., without finishing the completion.

---------------

Ok, and this is the original long version:

I just discovered ivy's action interface and added an action for `ivy-switch-buffers` which allows you to toggle virtual buffers for just this invocation.

```diff
diff --git a/ivy.el b/ivy.el
index e06c3dd..0a765ed 100644
--- a/ivy.el
+++ b/ivy.el
@@ -1832,7 +1832,12 @@ BUFFER may be a string or nil."
     "other")
    ("r"
     ivy--rename-buffer-action
-    "rename")))
+    "rename")
+   ("v"
+    (lambda (_b)
+      (setq ivy-use-virtual-buffers (not ivy-use-virtual-buffers))
+      (ivy--reset-state ivy-last))
+    "toggle virtual buffers")))
 
 ;;;###autoload
 (defun ivy-switch-buffer ()
@@ -1840,7 +1845,10 @@ BUFFER may be a string or nil."
   (interactive)
   (if (not ivy-mode)
       (call-interactively 'switch-to-buffer)
-    (let ((this-command 'ivy-switch-buffer))
+    (let ((this-command 'ivy-switch-buffer)
+	  ;; Bind it here dynamically so that a setq in the "toggle virtual
+	  ;; buffers" action doesn't change the global value.
+	  (ivy-use-virtual-buffers ivy-use-virtual-buffers))
       (ivy-read "Switch to buffer: " 'internal-complete-buffer
                 :preselect (buffer-name (other-buffer (current-buffer)))
                 :action #'ivy--switch-buffer-action
```

Ok, so now I can do `C-x b`, enter `some-doc` and see that it's not open right now.  So I can do `C-o s s s s g`, then disable the action panel with `C-o`, and then type more or change the selection in order to select the now shown `some-doc.tex` candidate.

Well, `C-x b some-doc C-o s s s s g C-o .tex RET` is a little bit longish.  What I should also be able to do is `C-x b some-doc C-o s s s s g j d` where the `j` would select the next candidate (assuming that is `some-doc.tex`) and then `d` would open that.  But this doesn't work which looks like a bug to me.  The selected virtual buffer is not opened.  Nothing visible happens except that the ivy completion stops and I'm back in the buffer from which I've called `C-x b`.

Anyway, what this issue is actually about is that the `M-o` interface does not allow for applying an action without being done.  When I use `M-o v` that will end the completion and do absolutely nothing.

So I think the `M-o` interface also needs a possibility to distinguish "go" from "done".  With the "kill" or "rename" actions, I can easily assume that one might kill/rename and then finish or keep the completion going.  With the virtual buffers action, there is no reason why one should be done after applying it.  It's whole purpose is to restrict/enlarge the set of candidates for completion.

For implementing this, I think the actions could be lists of length 4 where the new last element would indicate how that action can be used, e.g., `go` (for actions where being stopping the completion makes no sense, e.g. "toggle virtual buffers"), `done` (for actions where resuming the completion doesn't make sense), and `go-or-done` (for actions where both make sense like "kill", "rename").  For backward compatibility, I'd treat a missing 4th entry or `nil` as `go-or-done`.

Well, then the question remains how one should be able to choose between go and done in the `M-o` interface.  If we can assume that only lower-case letters are used for actions, then we could use the lower-case letter for action+done and the uppercase letter for action+go or the other way round.  And for actions which are either `go` or `done` we could always use the lower-case letter.

**Comment by abo-abo** [comment]
Ups, the answer is equally long:). I broke it up into 4 orthogonal topics.

## Part 1
> But this doesn't work which looks like a bug to me. The selected virtual buffer is not opened. Nothing visible happens except that the ivy completion stops and I'm back in the buffer from which I've called C-x b.

It works fine for me: I start with `ivy-use-virtual-buffers` nil, type in a bookmark name and there are zero matches.  Then <kbd>C-o ssssg</kbd> to toggle it to true. After this, <kbd>wwwwg</kbd> to change the action back to the default and call it.  The bookmark is now selected, but the completion hasn't exited. In your case, <kbd>d</kbd> just toggled `ivy-use-virtual-buffers`, because of the action you selected.

## Part 2
> So I think the M-o interface also needs a possibility to distinguish "go" from "done". With the "kill" or "rename" actions, I can easily assume that one might kill/rename and then finish or keep the completion going. With the virtual buffers action, there is no reason why one should be done after applying it. It's whole purpose is to restrict/enlarge the set of candidates for completion.

<kbd>M-o</kbd> is supposed to mirror <kbd>C-m</kbd>, and not <kbd>C-M-m</kbd> or both.  A good solution could be to make <kbd>C-M-o</kbd> to dispatch on action, execute it and not quit. This would keep the nice mnemonic thing going that holding the meta key makes the completion persist. I think this is more simple than what you propose.

## Part 3
In addition, I think I should bind <kbd>a</kbd> to a select action interface, e.g. <kbd>a4</kbd> would select action number 4, instead of having to do <kbd>sss</kbd> if you're on the first action.  The numbering could be customizable, I'd rather press <kbd>aa</kbd> for first, <kbd>as</kbd> for second, <kbd>ad</kbd> for third etc.

## Part 4
As a final thought, it could be possible to assign a different hydra to `ivy-switch-buffers`, since toggling `ivy-virtual-buffers` should be a simple thing like toggling the matcher with <kbd>m</kbd>.  The only thing is that `ivy-virtual-buffers` makes sense only in this completion, so it should not be present in all other completions. Something like this:

```elisp
(define-key map (kbd "C-o")
  (lambda ()
    (interactive)
    (if (eq (ivy-state-caller ivy-last) 'ivy-switch-buffer)
        (hydra-ivy-sb/body)
      (hydra-ivy/body))))
```

Of course, `hydra-ivy-sb` would have to be maintained separately from `hydra-ivy`, making sure that it doesn't use keys that `hydra-ivy` might introduce in the future. So a lot more hassle to maintain, but the end-result would be better.

**Comment by tsdh** [comment]
**Part 1:** Ah, yes, you are right of course.  But `wwww` for switching back to the default action is of course a bit inconvenient.

**Part 2:** Yes, that's another possibility (and simpler than what I proposed).  The problem I see with this is that "toggle virtual buffers" shouldn't really appear in `M-o` because it's useless there.

**Part 3:** I don't really think "I want to select the n-th action".  I'd rather like to have a `M-o` like selection.  But part 4 is actually better.

**Part 4:** Yes, togging virtual buffers is in the category of the pink entries in `C-o` (thus, it is an option toggle and no real action) but using two different hydras which are almost the same sounds like a bad idea.  Instead, I see it as a feature request for hydra: you should be able to define heads which are only enabled under certain conditions, e.g., hydra heads should support an `:when` key whose value is a lambda.  If that returns `nil`, the head is disabled.

**Comment by abo-abo** [comment]
> Part 1: Ah, yes, you are right of course. But wwww for switching back to the default action is of course a bit inconvenient.

Yeah, it's still work-in-progress. The point of <kbd>s</kbd>/<kbd>w</kbd> was to make things more discoverable and extensible (so that the interface looks the same for any number of actions).  More keys can be added to actually make it convenient.

> Part 2: Yes, that's another possibility (and simpler than what I proposed). The problem I see with this is that "toggle virtual buffers" shouldn't really appear in M-o because it's useless there.

True. Although it's doable, the toggle doesn't really belong in actions.

> Part 3: I don't really think "I want to select the n-th action". I'd rather like to have a M-o like selection. But part 4 is actually better.

Still, I think it wouldn't hurt to have this. For example, <kbd>a3cjjjjjj</kbd> to cycle selected buffers in other window. <kbd>a</kbd> to <kbd>s</kbd> should be as `ace-window` is to `other-window`: it's possible to get by with only `other-window`, but it becomes harder as the number of windows grows.

> Part 4: Yes, togging virtual buffers is in the category of the pink entries in C-o (thus, it is an option toggle and no real action) but using two different hydras which are almost the same sounds like a bad idea. Instead, I see it as a feature request for hydra: you should be able to define heads which are only enabled under certain conditions, e.g., hydra heads should support an :when key whose value is a lambda. If that returns nil, the head is disabled.

You're right. This is a long standing [issue](https://github.com/abo-abo/hydra/issues/86).  It's possible to implement, but only for simple hydra docstrings (e.g. plain ones that only set `:columns`).  But the thing is that hand-formatted docstrings are usually the best: they're compact and precise.  The disadvantage is that it's hard to amend them.

Here's a possible solution:

```elisp
(defhydra hydra-ivy-sb (:hint nil
                        :color pink
                        :inherit (hydra-ivy/heads))
  ("v" (setq ivy-use-virtual-buffers (not ivy-use-virtual-buffers))))

(defun hydra-ivy-sb-docstring ()
  (hydra--vconcat
   (list
    (eval hydra-ivy/hint)
    (format "\n\n\n   %sirtual: %S\n\n"
            (propertize "v" 'face 'hydra-face-pink)
            ivy-use-virtual-buffers))))

(setq hydra-ivy-sb/hint '(hydra-ivy-sb-docstring))
```

The first statement is short enough for what it does: define a new hydra that inherits all heads from `hydra-ivy` and adds one more.  The second statement generates a new docstring from the old one.  The third statement overrides `hydra-ivy-sb/hint` that was set by the first statement. Eventually, the first and third statements could be merged like this:

```elisp
(defhydra hydra-ivy-sb (:hint nil
                        :color pink
                        :inherit (hydra-ivy/heads))
  (hydra-ivy-sb-docstring)
  ("v" (setq ivy-use-virtual-buffers (not ivy-use-virtual-buffers))))
```

**Comment by tsdh** [comment]
>> Part 2: Yes, that's another possibility (and simpler than what I
>> proposed). The problem I see with this is that "toggle virtual
>> buffers" shouldn't really appear in M-o because it's useless there.
>
> True. Although it's doable, the toggle doesn't really belong in
> actions.

Agreed.

>> Part 3: I don't really think "I want to select the n-th action". I'd
>> rather like to have a M-o like selection. But part 4 is actually
>> better.
>
> Still, I think it wouldn't hurt to have this.

No, obviously not.

>> Part 4: Yes, togging virtual buffers is in the category of the pink
>> entries in C-o (thus, it is an option toggle and no real action) but
>> using two different hydras which are almost the same sounds like a
>> bad idea. Instead, I see it as a feature request for hydra: you
>> should be able to define heads which are only enabled under certain
>> conditions, e.g., hydra heads should support an :when key whose value
>> is a lambda. If that returns nil, the head is disabled.
>
> You're right. This is a long standing
> [issue](https://github.com/abo-abo/hydra/issues/86).

Oh, I didn't know there's already an issue.

> It's possible to implement, but only for simple hydra docstrings
> (e.g. plain ones that only set `:columns`).  But the thing is that
> hand-formatted docstrings are usually the best: they're compact and
> precise.  The disadvantage is that it's hard to amend them.

Wouldn't it be possible to mark up such conditional entries somehow?
E.g., "%OPT(_v_: toggle virtual buffers)" would mean that the enclosed
thing is optional and so `hydra--format' would expand that to either
"v: toggle virtual buffers" or a whitespace string of the same length.

Well, that wouldn't really be extensible, i.e., when you'd want to add
yet another option, you have to amend the docstring again.

Hm, here are some other ideas:

1. All (enabled) heads which are not mentioned in the docstring could be
simply appended, one entry per line.
Additionally, a conditional head might also have a `:docstring` entry
which would define its own layout.  So for example, I could define it
as `"\n                              _v_: virtual buffers"` in order
to have it aligned in the Maybe column.

2. Alternatively, you could decide that all heads with `:when` are layed
out in columns at the end of the buffer and users have no further
control about laying out such optional entries.  Then `hydra-ivy` could
just drop the Maybe column from the table in the docstring and instead
add `:when (lambda () t)` to all those entries.

IMO, alternative 2 is better, simpler, and wouldn't really degrade the
`hydra-ivy` interface.

**Comment by abo-abo** [comment]
> Wouldn't it be possible to mark up such conditional entries somehow?

It can be done. But I think the inheritance approach that I described before is a lot more extensible.  For example, `hydra-ivy-switch-buffer` and `hydra-ivy-find-file` could both inherit from `hydra-ivy` and then be edited independently without changing the parent, just like in the common OOP languages like C++.  The approach of putting a toggle for every conceivable child class into the parent class would result in a mess.

One disadvantage that I see here is the over-generation of code. Each hydra generates own lambda wrappers for each head. These lambda wrappers aren't re-used through inheritance. This can be fixed in the future though, if it ever becomes a big problem.

**Comment by tsdh** [comment]
Well, but with the inheritance approach I still need to somehow tell `ivy` that `hydra-ivy-sb` should be used for `ivy-switch-buffer`.  So every extension I want to make requires a custom hydra, mangling of the inherited docstring, and somehow making this new hydra being used.

I still think that hydras with conditional heads which are just appended to the docstring would be simpler.  And there could be a convenient interface for extending hydras, e.g.,

```elisp
(hydra-add-heads 'hydra-ivy
  '("v" ivy-toggle-virtual-buffers "toggle virtual buffers"
    :when (eq (ivy-state-caller ivy-last) 'ivy-switch-buffer))
  ...)
```

**Comment by abo-abo** [comment]
> So every extension I want to make requires a custom hydra, mangling of the inherited docstring, and somehow making this new hydra being used.

That's the idea. Each command that wants to override <kbd>C-o</kbd> can use this:

```elisp
(ivy-read
 ;; ...
 :keymap (let ((map (make-sparse-keymap)))
           (define-key map (kbd "C-o") 'hydra-ivy-sb/body)
           map))
```

And it makes sense to clone your own copy of the object instead of modifying the global one.

This approach is also more discoverable: if the user wants to see where a different <kbd>C-o</kbd> is coming from, she can press <kbd>C-h k C-o</kbd> and jump to the definition of the new hydra, and not the old one.

> hydra-add-heads

This function would inevitably define new functions (lambda wrappers for heads). These won't be byte-compiled, unlike with the inheritance approach.  In addition, I think debugging one case of `hydra-ivy` would be hard, once ~20 calls of `hydra-add-heads` are done for 20 different commands.

This doesn't mean that this function can't or shouldn't be added. You could implement it by having `hydra-ivy` inherit from `hydra-ivy` and manipulate the docstring appropriately. The byte compilation issues would remain though.

**Comment by tsdh** [comment]
Ok, thanks.

**Comment by abo-abo** [comment]
Here's what I've added to my config for now:

```elisp
(defhydra hydra-ivy-sb (:hint nil
                        :color pink
                        :inherit (hydra-ivy/heads))
  ("v" (progn
         (setq ivy-use-virtual-buffers (not ivy-use-virtual-buffers))
         (ivy--reset-state ivy-last))))

(defun hydra-ivy-sb-docstring ()
  (hydra--vconcat
   (list
    (eval hydra-ivy/hint)
    (format "Misc
------------
%sirtual: %-3S

"
            (propertize "v" 'face 'hydra-face-pink)
            ivy-use-virtual-buffers))))

(setq hydra-ivy-sb/hint '(hydra-ivy-sb-docstring))

(define-key ivy-switch-buffer-map (kbd "C-o") 'hydra-ivy-sb/body)
```

This code requires no modification of hydra or ivy, since `ivy-switch-buffer-map` was already there because of some other issue.  Quite a few entries can still easily be added to the `hydra-ivy-sb` docstring without increasing the amount of rows (I like to keep rows to a minimum so that they don't distract).  If you want to add rows instead of columns, it's even easier: use `concat` instead of `hydra--vconcat`.

I'll keep this code in my config for now, maybe you'd like to try it as well.  If at some point I implement hydra in a way that adding heads doesn't create lambda wrappers for all inherited heads, the code above can be included into ivy cheaply.  I think this is a real concern, since `hydra-ivy` expands to 1000 lines of code, and so does `hydra-ivy-sb`.

> (hydra-add-heads 'hydra-ivy
>   '("v" ivy-toggle-virtual-buffers "toggle virtual buffers"
>     :when (eq (ivy-state-caller ivy-last) 'ivy-switch-buffer))
>   ...)

This will be added to hydra eventually, both `:when` and `hydra-add-heads`. But it's tricky to do without generating overhead, in case these options aren't used.

**Comment by tsdh** [comment]
Oh, I didn't realize there's `ivy-switch-buffer-map` already.  So I could solve my virtual buffer toggle much easier (and not as an action).

```elisp
(defun th/ivy-toggle-virtual-buffers ()
  (interactive)
  (setq ivy-use-virtual-buffers (not ivy-use-virtual-buffers))
  (ivy--reset-state ivy-last))

(define-key ivy-switch-buffer-map (kbd "M-v") #'th/ivy-toggle-virtual-buffers)
```

**Comment by abo-abo** [comment]
Sure, if that works for you. But <kbd>M-v</kbd> and all the good bindings are usually already occupied in the standard setup.

**Comment by tsdh** [comment]
Oh, right, `M-v' was not a good choice of mine. ;-)

**Comment by abo-abo** [comment]
Thanks for the discussion. I'm trying to clean up the issue list, so I'm closing this one.  If there's still something not implemented from this discussion, open a new issue.
