### ISSUE TITLE
ivy-display-style nil no longer works

### ISSUE THREAD

**Issue by ianpan870102** [abo-abo/swiper#2570]
I like a minimum setup, so I've always had `(setq ivy-display-style nil)`. Unfortunately, this doesn't seem to work after I updated ivy this morning. Is there a workaround? I prefer not to have those colours in the minibuffer, I personally find them more distracting than helpful.
Thank you in advance!

**Comment by abo-abo** [comment]
You can remove the extra highlighting like this:

```elisp
(setq ivy-highlight-functions-alist
      '((ivy--regex-ignore-order . identity)
        (ivy--regex-fuzzy . identity)
        (ivy--regex-plus . identity)))
```

If you care about only one re-builder, you can configure just that one.

**Comment by basil-conto** [comment]
> Unfortunately, this doesn't seem to work after I updated ivy this morning.

For the record: this is because the user option `ivy-display-style` was completely removed from the sources without so much as a deprecation warning in commit a4a22e0755a9a7155e5bc8fd88ac0db03889d135.

@abo-abo Why was the user option completely removed? Just because it defaults to `fancy` doesn't make `nil` an unacceptable value.

Also, shouldn't setting `ivy-highlight-functions-alist` to `nil` have the same effect as adding entries whose value is `identity`?

**Comment by ianpan870102** [comment]
@abo-abo Thanks for the reply, but I have to agree with @basil-conto that `Just because it defaults to fancy doesn't make nil an unacceptable value.`
If I remember correctly, it was defaulted to fancy anyways before. I fail to see why we need to have the display-style option completely removed.

**Comment by abo-abo** [comment]
Thanks for the feedback, I've reverted the removal of `ivy-display-style`.

> Also, shouldn't setting `ivy-highlight-functions-alist` to `nil` have the same effect as adding entries whose value is `identity`?

I think we should refactor/simplify the code until that's the case, then deprecate and remove `ivy-display-style`.
