### ISSUE TITLE
counsel-find-file's counsel-up-directory preselects current dir

### ISSUE THREAD

**Issue by articuluxe** [abo-abo/swiper#2593]
If I am in a directory, do M-x counsel-find-file, press DEL to move up to the parent directory, then press ENTER, I am in the same directory as before.  The DEL action moves up to the parent, but preselects the prior directory.  This is a change in behavior and seems quite counter-intuitive.  I have tried to get used to this but haven't so far.  

I believe this was changed due to #1424.  Is this really how it is intended to be used? Is there an option I'm overlooking?

Thanks.

**Comment by abo-abo** [comment]
Thanks for the feedback. The idea was to make <kbd>DEL</kbd> more reversible, so that if you hit it by accident, you can always go back with <kbd>RET</kbd>.

But now I find myself getting annoyed that <kbd>DEL RET</kbd> doesn't work anymore to select the parent directory. The current work-around is to do <kbd>DEL . C-m</kbd>.

Maybe we should re-work this and have the `undo` mapping "undo" the <kbd>DEL</kbd>, instead of <kbd>RET</kbd>.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by articuluxe** [comment]
Much better, thank you.
