### ISSUE TITLE
Can `swiper` command choose the symbol or word at cursor point?

### ISSUE THREAD

**Issue by goofansu** [abo-abo/swiper#260]

**Comment by abo-abo** [comment]
Yes, press <kbd>M-n</kbd> (`ivy-next-history-element`) to get symbol-at-point into the minibuffer.
And/or press <kbd>M-j</kbd> (`ivy-yank-word`) to extend the minibuffer input with the next word (similar to <kbd>C-s C-w</kbd> of `isearch`).

**Comment by jonEbird** [comment]
Glad I saw this as being new to swiper I was looking for this as well. It might be a good idea to just include `"C-w"` in your `ivy-minibuffer-map` to also call `ivy-yank-word`. For now, I'm including a `define-key` call of my own config.

**Comment by abo-abo** [comment]
> For now, I'm including a define-key call of my own config.

<kbd>C-w</kbd> should be redefined in your config if you so choose. By design, it should call `kill-region`, like it does in all other buffers.

At first, it's hard to adapt the finger memory from <kbd>C-s C-w</kbd> to <kbd>C-s M-j</kbd>. But being able to use <kbd>C-w</kbd> for killing regions is an advantage.

If you've used `ido-find-file`, you might recall having to fall back to `find-file` with <kbd>C-f</kbd>, just to do normal editing things in the minibuffer. You can do those in ivy without having to switch a mode.

**Comment by goofansu** [comment]
Thanks. I should have read this on the [Wiki](https://github.com/abo-abo/swiper/wiki/generic-completion).

**Comment by abo-abo** [comment]
No problem. The wiki still needs improvement. I'm also trying to write a sort of a self-contained manual.
It's nice to keep track of the most common questions:)

**Comment by goofansu** [comment]
@abo-abo Great. Thank you.

**Comment by hex2010** [comment]
How can i do ivy-next-history-element automatically for swiper command?

**Comment by abo-abo** [comment]
@hex2010 `swiper` has an `inital-input` arg. Wrap your function around that and use `symbol-at-point`.
