### ISSUE TITLE
counsel-ag searches in the project root, not default-directory

### ISSUE THREAD

**Issue by mnewt** [abo-abo/swiper#2636]
The docstring of `counsel-ag` says "Grep for a string in the current directory using ag." But if `default-directory` is a subdirectory inside a project root according to `counsel--git-root`, it searches in the project root instead.

I suggest that either:

1. The docstring should be changed to clarify the behavior
2. The behavior should be changed to match the docstring.

I personally vote for the latter, since `counsel-projectile` provides comprehensive project-oriented commands, such as `counsel-projectile-ag`. But of course that's just my personal preference. 

What do you think?

**Comment by basil-conto** [comment]
Many Counsel search commands, not just `counsel-ag`, can start the search under different directories, and I think can even change the directory during completion.

As Emacs 28 will introduce a lot more built-in project-related functionality, I think it is important for Counsel to continue supporting related notions of search directory.

Counsel needs to unify its interface across different search commands w.r.t. these semantics, e.g. by accepting a prefix argument to toggle current directory vs project root, and the docstrings need to be fixed accordingly.

What `counsel-projectile` does shouldn't affect Counsel's design or interface, especially as Emacs' built-in project support gains prominence and features.

**Comment by abo-abo** [comment]
Thanks, I've clarifed the docstring. I think we should keep to the current behavior of using the project root by default.

However, I've made it easier to bring up the prompt for the current directory. So if `counsel-ag` is bound to <kbd>C-c k</kbd>, to search in the current directory instead of the project root you can press <kbd>C-u C-c k RET</kbd>.

If this is not sufficient, it's easy to make a customization:

```elisp
(defun my-counsel-ag ()
  (interactive)
  (counsel-ag "" default-directory))
(global-set-key (kbd "C-c K") 'my-counsel-ag)
```
