### ISSUE TITLE
Question about Ivy status

### ISSUE THREAD

**Issue by Ergus** [abo-abo/swiper#2676]
Hi @abo-abo:

In the devel mailing list we have been commenting some potential improvements for the next emacs release. One of the proposals on the table was to add Ivy to vanilla or add some configs for final users that could potentially include ivy/counsel/ivy-posframe.

In this message:
https://lists.gnu.org/archive/html/emacs-devel/2020-09/msg01110.html

Stefan mentioned some previous known issues and we would like to know if they are already solved.

There were also this emails mentioning issues:

https://lists.gnu.org/archive/html/emacs-devel/2020-09/msg01099.html
https://lists.gnu.org/archive/html/emacs-devel/2020-09/msg01091.html

Best,
Ergus

**Comment by basil-conto** [comment]
As I mentioned in those threads, given that Ivy is already distributed via GNU ELPA, I don't see the net benefit of including Ivy into Emacs, at least not as it currently stands.  Historically Ivy has rolled out its own entire completion mechanism that is quite separate and not easily reconcilable with vanilla completion (though there have been various efforts over the years to bridge various gaps).

So, from where I stand, it would make most sense to integrate into Emacs those parts of Ivy that are useful in general and for the benefit of all completion packages, e.g. customisable completion actions, and leave Ivy as a standalone package.

Either way, I think this discussion belongs on `emacs-devel` and `bug-gnu-emacs`.  I'm therefore closing this issue, but feel free to reopen it if you think there's something left to discuss here.  Please report any specific issues with Ivy as separate bugs, so that they can more easily be tracked and handled.
