### ISSUE TITLE
What does colon (:) do in regular ivy/counsel input?

### ISSUE THREAD

**Issue by WorldsEndless** [abo-abo/swiper#2697]
I use Ivy/Counsel globally. When creating a new org capture item (nothing specifically Ivy here), when filling in the title I often want to say "blah blah re: that subject". As soon as I get to the ":" after "re", though, it erases my whole prompt and I need to start over.  I recall reading someone elses issues/features and there were some super-powers related to the colon, but in any case, I've search the documentation and this codebase and can't find a clear explanation. What's going on with ":" in generic inputs? Is it a bug? Is it a feature?

**Comment by basil-conto** [comment]
Sorry, it's not clear what it is you are doing, and what happens when. Normally, Org capture items are entered into an `org-mode` buffer, and have nothing to do with Ivy/Counsel. You can inspect what <kbd>:</kbd> is bound to at any time via the usual <kbd>C-h</kbd><kbd>k</kbd><kbd>:</kbd>.

The only place I'm aware of where colons are special, is in Org's tag syntax, and when visiting remote files, e.g. `/ssh:foo:bar`.

In order to understand what's happening, please try to provide a detailed and reproducible recipe for the issue, including exactly which keys/commands you type and what you see at each stage. Please check whether you can reproduce the issue starting from `emacs -Q` or `make plain`, as if you cannot, it could indicate an issue with your configuration.  A recipe starting from `emacs -Q` will also help in reproducing the error on our side. Thanks.

**Comment by WorldsEndless** [comment]
trying to make a reproducible recipe has been problematic. In fact, it doesn't happen every time; I start typing "re:" and it erases everything; I try again and it erases everything again; but then I try a third time and it works. When I do `C-h k :` I just see self-insert, so I'm really not sure. But I suppose the "it does nothing special" is a good enough answer for this question.

**Comment by basil-conto** [comment]
Could you list the precise steps you take (i.e. keypresses, command invocations) that lead up to the colon problem, even if it doesn't happen every time?

**Comment by basil-conto** [comment]
> I use EXWM, though I don't think that matters.

[citation needed] ;)

> I have the following short stuff which is an Ivy interface to org template selection:

I tried this, but couldn't reproduce the problem (and I suspect I won't be without other parts of your configuration and environment). Feel free to reopen this issue if you manage to narrow it down.
