### ISSUE TITLE
Serious edge case of passing function in `ivy-ignore-buffers`

### ISSUE THREAD

**Issue by lackhoa** [abo-abo/swiper#2703]
If I'm not mistaken, if `ivy-use-virtual-buffers` is also enabled, then the user-provided predicate for ignoring buffer names will also be passed virtual buffers such as `#("init.el" 0 23 (face ivy-virtual))`, thus won't work correctly.

**Comment by basil-conto** [comment]
> thus won't work correctly.

Won't work correctly according to what?

**Comment by lackhoa** [comment]
> Won't work correctly according to what?

The function in `ivy-use-virtual-buffers` were supposed to be passed **buffer names**, not vectors. If a function expecting a type is passed another type, it wouldn't work correctly.

**Comment by basil-conto** [comment]
> `#("init.el" 0 23 (face ivy-virtual))`

This is a string, not a vector. What am I missing?

**Comment by basil-conto** [comment]
See [`(info "(elisp) Text Props and Strings")`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Text-Props-and-Strings.html).

**Comment by lackhoa** [comment]
Oh, I see, my function was expecting an actual buffer name, not one that doesn't exist, so my `get-buffer` call returned null and the rest errored out.

Alright, thanks @basil-conto, even though you are a douche.

**Comment by basil-conto** [comment]
Thanks for confirming, and please refrain from ad hominem name calling on this issue tracker; see the [GNU Kind Communications Guidelines](https://www.gnu.org/philosophy/kind-communication.en.html).

**Comment by lackhoa** [comment]
Oh sorry I should have been clear: it's your statements that are douchy, not you yourself.
You're by no means represented by your actions.

**Comment by basil-conto** [comment]
I'm sorry if my statements or actions came across as douchey, as this was never my intention.  I was only trying to help resolve whatever issue you were facing with Ivy.  If you describe more clearly what came across as douchey, perhaps I may be able to avoid it in the future.  If it's due to my replies being curt/brief/terse, then please understand that I am volunteering my limited free time to help with this project, and that my comments were intended in an objective and technical way (to better understand the issue you were facing and provide you with assistance) and not at all in a rude or dismissive way, even if they came across otherwise.

Either way, in the future please assume that participants on this issue tracker are posting in good faith, and do not take a harsh tone with them (e.g. by calling them, their actions, or their statements douchey), as that can unnecessarily hurt people's feelings and is counterproductive.  TIA.

**Comment by lackhoa** [comment]
I don't have a formal code for what is douchey and what's not, because I'm not a robot. It might have something with you be curt/brief/terse, but I'm not so sure.

> please assume that participants on this issue tracker are posting in good faith
I did exactly that, before your very first reply. Either way I did not come to my conclusion based on any random assumption.

> that can unnecessarily hurt people's feelings
It can also alert them about their behaviour, prompting them to change. Very productive thing.
