### ISSUE TITLE
Improve installation instructions

### ISSUE THREAD

**Issue by dalanicolai** [abo-abo/swiper#2734]
I have just tried to install Ivy first using [the instructions from the github README](https://github.com/abo-abo/swiper#installation), and subsequently using [the instructions from the manual](https://oremacs.com/swiper/#installing-from-emacs-package-manager), both ways resulting in an erroneous installation.

The README instructs to install the Ivy package from MELPA/ELPA, but when installing Ivy using the package manager the counsel, swiper and ivy-hydra packages do not get installed (the installation is complaining about the last one not being available)

The manual instructs to install counsel using the package manager However when installing counsel from ELPA while also the MELPA packages are available, then Emacs will by default install the dependencies from MELPA (as explained [here](https://www.reddit.com/r/emacs/comments/8ua8e6/is_it_possible_specify_repository_preference_with/e1dqxl6?utm_source=share&utm_medium=web2x&context=3), resulting in the error as reported in issue #2591.

Please update the installation instructions to preferably install the counsel package from MELPA, or otherwise install from ELPA but then make sure that the dependencies are installed from ELPA also.

**Comment by basil-conto** [comment]
(Nit: ELPA is the protocol, GNU ELPA is the archive.)

> when installing Ivy using the package manager the counsel, swiper and ivy-hydra packages do not get installed

Can you please describe in more detail the steps you took, what you expected to see, and what went wrong?  Emacs defaults to having only GNU ELPA in `package-archives`, from which you can install `ivy`, `swiper`, `counsel` (and optionally `hydra`):

1. `HOME="$(mktemp -d)" emacs -Q`
2. `M-x package-refresh-contents RET`
3. `M-x package-install RET counsel RET`

This succeeds in installing `ivy`, `swiper`, and `counsel`. The only bug I see here is that `ivy-hydra.el`, which is distributed with `ivy`, cannot be successfully byte-compiled since it unconditionally loads `hydra`, which is a separate package available on GNU ELPA. (In general the dependencies between these packages is a mess, but I'm not in a position to fix them.)

But assuming you don't want to install and use `hydra`, then you can just ignore this byte-compilation error.

> However when installing counsel from ELPA while also the MELPA packages are available, then Emacs will by default install the dependencies from MELPA

Carelessly mixing packages is never a good idea, and not just in the Emacs world. If a user wants to fetch packages from both GNU ELPA and MELPA (as I routinely do), then the onus lies on the user to set `package-archive-priorities` and `package-pinned-packages` appropriately.

If Emacs mishandles something here, then please report it via `M-x report-emacs-bug RET`.

If this project mishandles something here (other than the aforementioned `ivy-hydra.el` error), could please describe it in more detail?

> Please update the installation instructions to preferably install the counsel package from MELPA, or otherwise install from ELPA but then make sure that the dependencies are installed from ELPA also.

I suggest advertising GNU ELPA, which is the official Emacs package archive, more prominently than the third-party MELPA.

Could you please describe which dependencies you're referring to?

Thanks.

**Comment by dalanicolai** [comment]
I am trying to replicate the behavior, but everything works now when I simply install `counsel` from GNU ELPA using via the package manager. I am not sure what caused the behavior and the the error as mentioned in #2591 (although it seems like chemacs might have something to do with it). Anyway, thanks for checking and providing the detailed explanations. I will close this issue now then.

**Comment by basil-conto** [comment]
FWIW: some issues with how the various Ivy packages and their different versions were bundled on GNU ELPA have now been fixed, so [GNU-devel ELPA](https://elpa.gnu.org/devel/) (for bleeding edge versions) and [GNU ELPA](https://elpa.gnu.org/packages/) (for point releases) are once again the official channels for these packages :).
