### ISSUE TITLE
Bookmark names disappeared ?

### ISSUE THREAD

**Issue by pseudomyne** [abo-abo/swiper#2739]
Hi and thank you for the Ivy suite. 
I have just upgraded to latest version of the packages and I'm a bit disappointed by the new way bookmarks are displayed in the minibuffer. When calling `M-x bookmark-jump`, bookmark **names** are not fully displayed anymore.
I find this annoying because I try to invent names that I can easily memorize and sort. 

Is there a way to restore the old display fashion ? (couldn't find anything through `M-x customize`)
Thanks

**Comment by basil-conto** [comment]
I don't think I can reproduce this. Please try to provide more information, particularly your versions of the Ivy suite packages and Emacs itself (`M-x version RET`). A reproducible recipe including precise steps taken, with expectations and reality described at each step, and starting from `emacs -Q` or `make plain`, would be ideal.

What do you mean by "not fully displayed"?

**Comment by pseudomyne** [comment]
What I mean is, now I have lines in the minibuffer that display, namely FILE or DIRED or NOTFOUND, followed by the location of what is bookmarked (home/me/dir/file). The name I gave to the bookmark does not appear at all in that line.

**Comment by basil-conto** [comment]
I'm sorry, but you haven't provided enough information in order to figure out what's going wrong.  What is your precise Emacs version?  Have you tried upgrading Ivy to a newer version?  Can you give an example of the contents of your `bookmark-file`?  Can you describe which steps you take, and ideally provide a transcript or screenshot of what you see in the minibuffer?

Here's what I've tried:

1. `emacs -Q`
2. `M-x package-initialize RET`
3. `M-x ivy-mode RET`
4. `M-x bookmark-jump RET`

This results in the following completion session:

![bkmk](https://user-images.githubusercontent.com/9121222/100802958-3523c080-3422-11eb-887b-1d16c417ffd6.png)

If I disable `ivy-mode`, I see the exact same candidates, so I don't see how Ivy could be doing something wrong here.

The candidates above are based on the following `bookmark-file` contents:

```el
(("init.el"
 (filename . "~/.emacs.d/init.el")
 (front-context-string . ")\n\n;; disaster\n\n")
 (rear-context-string . "        \"pdf\")))")
 (position . 83363))
("org-capture-last-stored-marker"
 (filename . "~/Dropbox/index/emacs/org/emacs.org")
 (front-context-string . "** Uninstalling ")
 (rear-context-string . "emacs\n\n* Inbox\n\n")
 (position . 61))
("org-refile-last-stored"
 (filename . "~/Dropbox/index/emacs/org/emacs.org")
 (front-context-string . "** bug#42112 :ex")
 (rear-context-string . "emacs\n\n* Inbox\n\n")
 (position . 61))
("org-pomodoro.el"
 (filename . "~/.emacs.d/elpa/org-pomodoro-20161119.226/org-pomodoro.el")
 (front-context-string . ";;; org-pomodoro")
 (rear-context-string)
 (position . 1)
 (annotation . "Use it!\n"))
("debian-emacs-policy.gz"
 (filename . "/usr/share/doc/emacsen-common/debian-emacs-policy.gz")
 (front-context-string . "-*-indented-text")
 (rear-context-string)
 (position . 1)
 (annotation . "Debian startup\n"))
("(gcc-6) Instrumentation Options"
 (front-context-string . "\n3.11 Program In")
 (rear-context-string . "p: Invoking GCC\n")
 (position . 402440)
 (filename . "/usr/share/info/gcc-6")
 (info-node . "Instrumentation Options")
 (handler . Info-bookmark-jump)
 (annotation . "Building emacs like the deb package maintainers\n"))
("(elisp) Creating Symbols"
 (front-context-string . "table called an ")
 (rear-context-string . "d an index in a\n")
 (position . 378949)
 (filename . "/home/blc/.local/share/info/elisp")
 (info-node . "Creating Symbols")
 (handler . Info-bookmark-jump)
 (annotation . "obarray vs hash table\nsee which packages are using the former still and rewrite them\n"))
("ggtags.el"
 (filename . "~/.emacs.d/elpa/ggtags-20161022.251/ggtags.el")
 (front-context-string . ";;; ggtags.el --")
 (rear-context-string)
 (position . 1)
 (annotation . "Configure\n"))
("counsel-gtags.el"
 (filename . "~/.emacs.d/elpa/counsel-gtags-20170326.559/counsel-gtags.el")
 (front-context-string . ";;; counsel-gtag")
 (rear-context-string)
 (position . 1)
 (annotation . "Configure\n"))
```

My Ivy version is `ivy-20201110` and my Emacs version is `GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.16.0, Xaw3d scroll bars) of 2020-12-01`.

**Comment by pseudomyne** [comment]
Thank you for trying to help basil-conto. 
I have found the origin of my problem : it's `ivy-rich`. 
Disabling it makes things back to normal ivy display. For some reason, `ivy-rich` didn't work for `counsel bookmarks` before my latest upgrade. 

Here's a screenshot (didn't know I could post some) :

![ivy-rich](https://user-images.githubusercontent.com/11979451/100847369-09372800-3480-11eb-8299-8833752b8796.png)
