### ISSUE TITLE
Defining aiases to replace emacs commands with counsel ones.

### ISSUE THREAD

**Issue by sshbio** [abo-abo/swiper#277]
I used to define mosts keybindings to replace mosts emacs commands with counsel and ivy counterparts.

I only had issues with find-file, which counsel find-file calls itself, can be used in eshell, and is much like system part of emacs.

For the other, I did not had any problem.  Is it ok to make aliases?  Is it better to use global-set-key instead?

[EDIT]: describe varialbes and funtions also needs to be defined as keybindings.

Aliases
```elisp
(defalias 'execute-extended-command 'counsel-M-x)
(defalias 'yank-pop 'counsel-yank-pop)
(defalias 'isearch-forward 'swiper)
(defalias 'isearch-backward 'swiper)
(defalias 'load-theme 'counsel-load-theme)
(defalias 'load-library 'counsel-load-library)
(defalias 'org-set-tags 'counsel-org-tag)
(defalias 'switch-buffer 'ivy-switch-buffer)
```

Keybindings
```elisp
(global-set-key (kbd "C-x C-f") 'counsel-find-file)
(global-set-key (kbd "C-h f") 'counsel-describe-function)
(global-set-key (kbd "C-h v") 'counsel-describe-variable)
```

These are only commands that do not require extra packages.

I tried emacs without any completion system for a few weeks: emacs feels even more vanilla and lightweight with ivy than without or with ido/icomplete-mode!

**Comment by abo-abo** [comment]
> I used to define mosts keybindings to replace mosts emacs commands with counsel and ivy counterparts.

Yes, that's what I do currently.

> For the other, I did not had any problem. Is it ok to make aliases? Is it better to use global-set-key instead?

I've never thought of using aliases for that. I guess `global-set-key` is the advertised approach, because you can flexibly revert any change. However, using `defalias` hard-wires things and is harder to revert. On the other hand, `defalias` can potentially reach more places, by `ivy-mode` does that anyway.

I think it's up to you, what you want to do. One important thing is that the argument lists need to match, for instance `counsel-find-file` should certainly take `filename` argument, possibly `(filename &optional wildcards)` to be just like `find-file`.

> (defalias 'execute-extended-command 'counsel-M-x)

This one has a different calling convention, which I wouldn't want `counsel-M-x` to have.

> (defalias 'yank-pop 'counsel-yank-pop)
> (defalias 'isearch-forward 'swiper)
> (defalias 'isearch-backward 'swiper)

Same goes for these 3. It actually matters for `isearch-forward`, since a lot of Emacs code calls this function and expects it to do what the original `isearch-forward` does.

> (defalias 'load-theme 'counsel-load-theme)
> (defalias 'load-library 'counsel-load-library)

Same for these 2. Emacs code calls these functions with arguments, while the `counsel` variants don't have arguments.

> (defalias 'org-set-tags 'counsel-org-tag)
> (defalias 'switch-buffer 'ivy-switch-buffer)

Same here. Overall, it seems that using `defalias` causes a lot of trouble, and otherwise requires me to rewrite the signatures of a whole lot of functions, making them take arguments that I don't really care about etc.

Therefore, I think it's best to use the advertised `global-set-key` approach. In the end, the difference between `counsel-find-file` and regular `find-file` with `ivy-mode` on is only that <kbd>C-M-n</kbd>, <kbd>C-M-p</kbd> and `ivy-resume` don't work.  If you make the alias, and e.g. `eshell` calls `find-file` (remapped to `counsel-find-file`), followed by some other `eshell` code, the above things still won't work properly, because they have no idea about the `eshell` code that gets called after `counsel-find-file` exits.

> I tried emacs without any completion system for a few weeks: emacs feels even more vanilla and lightweight with ivy than without or with ido/icomplete-mode!

Thanks, that's what I was going for, I guess :)

**Comment by sshbio** [comment]
Thank you for this! Very instructive, I will choose the wiser global-set-key.

Arguments was indeed the issue I had by aliasing.

I will keep emacs sane, and let ivy guide my input!

`(global-abo-abo-mode 1)`

**Comment by abo-abo** [comment]
OK, closing the issue.
