### ISSUE TITLE
ivy insinuates switch-buffer faces

### ISSUE THREAD

**Issue by WorldsEndless** [abo-abo/swiper#2801]
I'm trying to use plain old `switch-to-buffer` (with selectrum), but still need ivy for hydra stuff. But I can't get ivy to stop insinuating undesirable faces into my switch-buffer selection! I've got the following, but it doesn't seem to stop the buffer faces from creeping in.

```lisp
(use-package ivy-hydra
  :custom
  (ivy-display-style nil)
  (ivy-minibuffer-faces nil)
  (ivy-switch-buffer-faces-alist nil))
```

How can I get Ivy to leave my buffer formatting alone?

**Comment by basil-conto** [comment]
It is unclear what you mean.  Please list the precise steps you take (which keys/commands you invoke), describing what you see and what you expect at each stage, ideally starting from some reproducible state such as `emacs -Q` or `make plain`.

**Comment by WorldsEndless** [comment]
1. cause ivy to load (e.g. `use-package ivy-hydra`)
2. make sure some org buffers are in the buffer list, e.g. with `M-x org-agenda`
3. view buffer selection list with `M-x switch-to-buffer`
4. Buffer styles are messed up, showing the ivy buffer face match rules

**Comment by basil-conto** [comment]
I assume you're also enabling `ivy-mode`?

In any case, the screenshot does not look like what `ivy-mode` does to `switch-to-buffer`.  I assume you're using some other package like `ivy-rich` or similar.  Please try reproducing the error from `emacs -Q` or `make plain` like I asked, or try commenting-out parts of your `user-init-file` until you've identified which parts give rise to this behaviour.

**Comment by WorldsEndless** [comment]
In no place have I ever enabled ivy-mode (even when I was primarily using ivy); it just worked. Now the only ivy-related item in my config is this:

```lisp
(use-package ivy-hydra
  :custom
  (ivy-display-style nil)
  (ivy-minibuffer-faces nil)
  (ivy-switch-buffer-faces-alist nil))
```

I've verified that `ivy-mode nil`, but still I am seeing orgmode files changed consistently with the ivy face rule for those...

**Comment by WorldsEndless** [comment]
Hmmm... the problem occurs in all variants of buffer-switch I Have on my system (most of which I didn't even know I had, and never use): bufler, ido, ivy...

**Comment by basil-conto** [comment]
> Now the only ivy-related item in my config is this:

Like I said, your screenshot clearly shows that some **other** part of your config is giving rise to this issue, since Ivy on its own does not make `switch-to-buffer` completion look like that.  To illustrate this, here's the kind of reproducible recipe I was hoping for:

1. `emacs -Q`
2. `M-x package-initialize RET`
3. `M-x load-library RET ivy-hydra RET`
4. `C-x b foo RET M-x org-mode RET`
5. `C-x b bar RET M-x org-mode RET`
6. `M-x switch-to-buffer RET TAB`

   ![2021-02-08-182755_661x181_scrot](https://user-images.githubusercontent.com/9121222/107265614-629d7380-6a3c-11eb-9276-f4fecb5ee1b6.png)

7. `C-g`
8. `M-x ivy-mode RET`
9. `M-x switch-to-buffer RET`

   ![2021-02-08-182849_669x142_scrot](https://user-images.githubusercontent.com/9121222/107265669-734de980-6a3c-11eb-8bf7-3e5f0d6ae1cf.png)

As you can see, the result is nothing like the screenshot you provided.  Without more information, I can only guess that what you see is unrelated to Ivy proper, and the result of using some other package like `ivy-rich`, `selectrum`, Doom, or Spacemacs.

Please try reproducing the issue starting from `emacs -Q` and/or by recursively commenting-out parts of your config to see which ones are relevant.

**Comment by basil-conto** [comment]
> Hmmm... the problem occurs in all variants of buffer-switch I Have on my system (most of which I didn't even know I had, and never use): bufler, ido, ivy...

Thanks, that confirms my suspicions ;).  Then your best friends are `emacs -Q` and/or recursively bisecting your config to narrow it down to the culprit.

**Comment by WorldsEndless** [comment]
Agreed. bisection it is.
