### ISSUE TITLE
Counsel rg base command string to exclude a directory

### ISSUE THREAD

**Issue by revrari** [abo-abo/swiper#2802]
I would like to add a string to the variable `counsel-rg-base-command` that would allow me to exclude my `tmp` directory from `counsel-rg` searches. This directory sits in my home folder (`~/`). I have tried various glob expressions, none of which seem to work. I would appreciate some guidance in this regard. My current string is as follows:

```
 '(counsel-rg-base-command
   '("rg" "-M" "240" "--with-filename" "--no-heading" "--line-number" "--color" "never" "%s" "--no-hidden"))
```

**Comment by basil-conto** [comment]
> I have tried various glob expressions, none of which seem to work.

It's always useful to say what you've tried ;).

> I would like to add a string to the variable `counsel-rg-base-command` that would allow me to exclude my `tmp` directory from `counsel-rg` searches. This directory sits in my home folder (`~/`).

It is not possible to do this in the general case, since `rg` always uses relative file names.  See BurntSushi/ripgrep#973.

If you always initiate the relevant searches from the same directory, then you can indeed add a static value to `counsel-rg-base-command`.  For example, if you always start these searches from `~/`, then you can exclude files under `~/tmp` by including something like `"-g" "!tmp/**"` in `counsel-rg-base-command`.

Alternatively, you can craft the appropriate glob on the fly (without statically modifying `counsel-rg-base-command`), e.g.:

![rg](https://user-images.githubusercontent.com/9121222/107257616-c1f68600-6a32-11eb-9edb-f1f83911e437.png)

If you'd rather avoid having to think about that each time, you can achieve the same using [function advice](https://www.gnu.org/software/emacs/manual/html_node/elisp/Advising-Functions.html).  For example:

```el
(define-advice counsel-rg
    (:around (fn &optional in dir opts &rest args) my-glob)
  "Exclude files under ~/tmp from `counsel-rg' results."
  (let* ((ign "~/tmp") ;; Directory to ignore.
         (dir (or dir default-directory))
         (glob (and (file-in-directory-p ign dir)
                    (file-relative-name (expand-file-name "**" ign) dir))))
    (when glob (setq opts (concat "-g !" glob " " opts))))
  (apply fn in dir opts args))
```

**Comment by revrari** [comment]
Thank you. This works perfectly. I presume one can only exclude one directory with a `let` expression?

**Comment by basil-conto** [comment]
> I presume one can only exclude one directory with a `let` expression?

Depends on the `let` expression ;).

Here's one way to extend the advice to multiple exclude patterns:

```el
(defvar my-rg-excludes '("~/foo" "~/bar")
  "List of directories to exclude from `counsel-rg' results.")

(define-advice counsel-rg
    (:around (fn &optional in dir opts &rest args) my-glob)
  "Exclude `my-rg-excludes' from `counsel-rg' results."
  (let ((dir (or dir default-directory)))
    (dolist (x my-rg-excludes)
      (let ((glob (and (file-in-directory-p x dir)
                       (file-relative-name (expand-file-name "**" x) dir))))
        (when glob (setq opts (concat "-g !" glob (and opts " ") opts))))))
  (apply fn in dir opts args))
```

**Comment by revrari** [comment]
This is awesome. I cannot thank you enough.

**Comment by basil-conto** [comment]
Glad it works, happy to help :).
