### ISSUE TITLE
Swiper: pcre2el not found

### ISSUE THREAD

**Issue by veronikazaglotova** [abo-abo/swiper#2810]
Using straight, I installed swiper, ivy and counsel. Whenever I ran swiper I got this error. I installed pcre2el manually and the issue got solved. Is it a straight issue or is the recipe missing a dependency?
![screenshot](https://user-images.githubusercontent.com/52463107/107880088-cc1ef580-6f06-11eb-91ad-235b3f7355cb.png)

**Comment by basil-conto** [comment]
None of Ivy, Swiper, or Counsel use the `pcre2el` package.

**Comment by veronikazaglotova** [comment]
What is happening on my machine?

**Comment by basil-conto** [comment]
Sorry, I don't have a crystal ball :).

Before the error happens, enable error backtraces with `M-x toggle-debug-on-error RET`.  Then reproduce the error, and post the backtrace here.

I also recommend commenting out parts of your config to narrow down which parts of it give rise to the error.

So far it's looking pretty unlikely that this is caused by Ivy/Swiper/Counsel.

**Comment by veronikazaglotova** [comment]
It's a boon issue.

**Comment by basil-conto** [comment]
Thanks for confirming.
