### ISSUE TITLE
ivy 0.13.2 is missing changelog

### ISSUE THREAD

**Issue by joca-bt** [abo-abo/swiper#2822]
ivy 0.13.2 was released but the [changelog ](https://github.com/abo-abo/swiper/blob/master/doc/Changelog.org) was not updated.

**Comment by basil-conto** [comment]
I know, see the commit message of 1deef7672b25e2cb89dfe5cc6e8865bc6f2bcd4e.

`0.13.2` was intended as a point (aka bugfix) release to reconcile `0.13.0` on GitHub with `0.13.1` on GNU ELPA, but this process is still in progress, and GNU ELPA remains broken; see the following `emacs-devel` thread: https://lists.gnu.org/r/emacs-devel/2021-02/msg01935.html

More generally, updating the change log and cutting releases has until now been @abo-abo's responsibility.  I am neither familiar with the process, nor know whether I am authorised to do so.

Sorry if this has caused you any inconvenience.

**Comment by joca-bt** [comment]
Not sure why this was closed already. A new release is present in MELPA stable but there is no changelog for it.

I'd guess other users obtaining the stable versions from MELPA stable rely on the changelog to see the new features, which they won't be able to find now although they'd get notified there is a new version available.

**Comment by basil-conto** [comment]
> Not sure why this was closed already.

Because `0.13.2`, and potentially `0.13.3`, if necessary, won't include a change log - the purpose of these point releases is to fix the state of Ivy et al. on GNU ELPA.  This is a higher priority than updating the change log, and anyway I am not in a position to write a full change log or cut a proper release.

This is an unfortunate symptom of this project's bad habit of not keeping the change log up to date as changes are made, as well as its lack of a documented release project.

Would you prefer to reopen this issue retitled as "Please release 0.14.0", which will have to wait until @abo-abo decides to cut such a release?

> A new release is present in MELPA stable but there is no changelog for it.

The change log is where it's always been: `doc/Changelog.org`.  It just hasn't been kept up to date, and now point releases are required to fix other, more pressing issues.

> I'd guess other users obtaining the stable versions from MELPA stable rely on the changelog to see the new features, which they won't be able to find now although they got notified there is a new version available.

Where do MELPA Stable users usually see their news?

**Comment by joca-bt** [comment]
> Where do MELPA Stable users usually see their news?

Emacs shows there's a new version available for update -> users come and check the changelog to see what's up.

**Comment by basil-conto** [comment]
> This wasn't an issue before since there were no ninja releases.

Yes, but also GNU ELPA wasn't (or was less) broken then, and @abo-abo was still actively maintaining the project.

There's only so much I can do as a collaborator without help from the maintainer.

> Emacs shows there's a new version available for update -> users come here and check the changelog to see what's up.

Then I suggest they wait until `0.14.0` is finally released.
