### ISSUE TITLE
ivy-call / openwith switches focus to previous window

### ISSUE THREAD

**Issue by ave-63** [abo-abo/swiper#2842]
I'm using arch linux, emacs 27.2 with ivy-20210311.1635, and the openwith package for opening PDF's, CSV's, etc in non-emacs programs. Whenever I call `ivy-call` from an ivy minibuffer (like `counsel-find-file` or `counsel-fzf`) to open a PDF, CSV, etc, it properly opens the file and leaves the ivy minibuffer there, but the main window from which I called `counsel-fzf` is focused, instead of the ivy minibuffer. So, I have to `other-window` back to the ivy minibuffer, a minor inconvenience.

This doesn't happen when I `ivy-call` to open text files within emacs. It also doesn't happen if I `ivy-dispatching-call` and select `x: open externally`. The problem does happen when I use `ivy-next-line-and-call`.

This seems related to [1767](https://github.com/abo-abo/swiper/pull/1767) and [1607](https://github.com/abo-abo/swiper/pull/1607), but I am not an emacs/elisp expert and don't understand ivy source code yet.

I was able to reproduce the issue in `emacs -Q` by running the following in the scratch buffer:

    (require 'package)
    (add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
    (package-initialize)
    
    (unless (package-installed-p 'use-package)
    (package-refresh-contents)
    (package-install 'use-package))
    (eval-when-compile
      (require 'use-package))

    (use-package openwith
      :ensure t
      :config
      (openwith-mode t)
      (setq openwith-associations '(("\\.pdf\\'" "zathura" (file))
                                    ("\\.xlsx\\'" "soffice" (file))
                                    ("\\.docx\\'" "soffice" (file))
                                    ("\\.pptx\\'" "soffice" (file))
                                    ("\\.csv\\'" "soffice" (file))
                                    ("\\.ods\\'" "soffice" (file))
			      	("\\.xopp\\'" "xournalpp" (file)))))

**Comment by basil-conto** [comment]
> Whenever I call `ivy-call` from an ivy minibuffer (like `counsel-find-file` or `counsel-fzf`) to open a PDF, CSV, etc, it properly opens the file and leaves the ivy minibuffer there, but the main window from which I called `counsel-fzf` is focused, instead of the ivy minibuffer.

Indeed, this is because `openwith` works by signalling an error:

https://github.com/jpkotta/openwith/blob/1dc89670822966fab6e656f6519fdd7f01e8301a/openwith.el#L116-L118

This is... unexpected, to put it politely :).

The simplest way to handle this on the Counsel side would be to put an `ignore-errors` around the `find-file` call in `counsel-find-file-action`, and similarly `ivy-call` could catch errors from calling actions.

But I don't think that would be TRT - an error is an error, and `find-file` shouldn't fail on success :).

On your end, you could place some [function advice](https://www.gnu.org/software/emacs/manual/html_node/elisp/Advising-Functions.html) around `openwith-file-handler` to ignore its errors.

I'm tempted to close this as a bug with `openwith`, but I'd like to hear your thoughts first.

BTW, Counsel has a poor-man's emulation of `openwith` in the form of the user option `counsel-find-file-extern-extensions`.  Files with the listed extensions get opened with `xdg-open` on non-Windows/macOS systems.  Perhaps this feature can be extended to support your workflow.

**Comment by ave-63** [comment]
> BTW, Counsel has a poor-man's emulation of `openwith` in the form of the user option `counsel-find-file-extern-extensions`. Files with the listed extensions get opened with `xdg-open` on non-Windows/macOS systems. Perhaps this feature can be extended to support your workflow.

This is a good suggestion, and I tried it out and it works fine from `counsel-find-file`, but it doesn't work apply to opening files from dired or `counsel-fzf` (which is what I usually use). Extending the feature to `counsel-fzf` seems like a good idea, but I'd also like it to apply to dired, and that seems outside the scope of `ivy`. So I will continue with `openwith` or something like it.

> On your end, you could place some [function advice](https://www.gnu.org/software/emacs/manual/html_node/elisp/Advising-Functions.html) around `openwith-file-handler` to ignore its errors.

This is probably what I'll do. It also seems like a good learning project, to figure out how `openwith` works and make my own simpler version, so maybe I'll do that.

**Comment by basil-conto** [comment]
> > On your end, you could place some [function advice](https://www.gnu.org/software/emacs/manual/html_node/elisp/Advising-Functions.html) around `openwith-file-handler` to ignore its errors.
> 
> This is probably what I'll do. It also seems like a good learning project, to figure out how `openwith` works and make my own simpler version, so maybe I'll do that.

Sure, in that case I'm closing this issue. Thanks.
