### ISSUE TITLE
Why does "counsel-yank-pop" has a hardcoded ":height" value?

### ISSUE THREAD

**Issue by rodrigo-morales-1** [abo-abo/swiper#2854]
Why is the value of `ivy-height` enforced for `counsel-yank-pop`? Wouldn't it be better to use the default value of `ivy-height` which is set by the user?

```
(ivy-configure 'counsel-yank-pop
  :height 5
  :format-fn #'counsel--yank-pop-format-function)
```

I know that I can fix this just by including the following in my configuration file but that would add an extra-line which I will need to maintain over time.

```
(ivy-configure 'counsel-yank-pop :height ivy-height)
```

**Comment by basil-conto** [comment]
> Why is the value of `ivy-height` enforced for `counsel-yank-pop`?

It's not enforced, it just has a different default.  This is because `counsel-yank-pop` can display multiple lines per candidate, subject to the user option `counsel-yank-pop-truncate-radius`.  So a lower default number of candidates shown ensures that the minibuffer doesn't get too large with multiline candidates. See #315.

> Wouldn't it be better to use the default value of `ivy-height` which is set by the user?

Maybe if they never have multiline strings, sure. But that's not the case for everyone by default. The height for `counsel-yank-pop` is configurable exactly because different users have different use cases and preferences.

> I know that I can fix this just by including the following in my configuration file but that would add an extra-line which I will need to maintain over time.

That's the cost of configurability I'm afraid ;).
