### ISSUE TITLE
ivy-completing-read do something on highlighted selection without exiting completing-read instance

### ISSUE THREAD

**Issue by bcmertz** [abo-abo/swiper#2858]
I am attempting to write a theme switcher that lists all the available themes and whichever theme is currently highlighted will be applied, so that themes can easily be previewed.

Right now I am using `ivy-completing-read` like this dummy code:

```
(setq selected-theme (ivy-completing-read "theme: " (custom-available-themes)))
(load-theme selected-theme t)
```

But instead of exiting on enter there should be a loop that repeats and every time I change the theme highlighted or press some key combo like <C-return> ivy should spit out the highlighted option to the theme loading code beneath and continue the loop displaying the options. Is there a builtin function that would allow this behavior?

I know something like this happens in swiper, where whatever is highlighted is jumped to in the document even without pressing enter. I read swiper's source code but couldn't figure out how it was achieving this

Any help is greatly appreciated, I hope I explained my problem adequately :)

**Comment by basil-conto** [comment]
I think you're describing the command `counsel-load-theme`:

![output-2021-05-04-09:31:28](https://user-images.githubusercontent.com/9121222/116978436-a14d6d80-acbb-11eb-986d-c30b8dce4186.gif)

For the non-exiting preview, just use `C-M-n`, `C-M-p`, and `C-M-m` instead of `C-n`, `C-p`, and `C-m` respectively; see [`(info "(ivy) Key bindings for multiple selections and actions keep minibuffer open")`](https://oremacs.com/swiper/#key-bindings-for-multiple-selections-and-actions-keep-minibuffer-open).

Alternatively, if you `C-o c` (`ivy-toggle-calling`) then `C-n` and `C-p` will also update the theme; see [`(info "(ivy) Hydra in the minibuffer")`](https://oremacs.com/swiper/#hydra-in-the-minibuffer).

> Right now I am using `ivy-completing-read`

Note that `ivy-completing-read` is a drop-in replacement for the built-in `completing-read`, so it does not support Ivy-specific features like doing something with the current completion candidate without exiting completion. For that, you should use `ivy-read` instead. This is why the `counsel` library of functions that call `ivy-read` exists; see [`(info "(ivy) Counsel commands")`](https://oremacs.com/swiper/#counsel-commands).

> Is there a builtin function that would allow this behavior?

Two ways to achieve this are via the `:action` and `:update-fn` arguments to `ivy-read`. The former is invoked e.g. when typing `C-M-n` or `RET`.  The latter is invoked after every refresh, i.e. after pretty much every keypress.

If `counsel-load-theme` doesn't work for you, I suggest you either submit a feature request or patch for improving it, or try calling `ivy-read` with a custom `:action` function in your custom command.

> I read swiper's source code but couldn't figure out how it was achieving this

`swiper` uses an `:update-fn`:

https://github.com/abo-abo/swiper/blob/4ffee1c37340a432b9d94a2aa3c870c0a8203dcc/swiper.el#L828-L832

**Comment by bcmertz** [comment]
Hi @basil-conto this is exactly what I needed, thank you! One last question is I want slightly different behavior from `counsel-load-theme`, ideally I could set `ivy-calling` to t for a specific function, such as my simple clone:
```
(defun bcm/theme ()
  "Dynamic themeing. C-M-m to preview theme without exiting."
  (interactive)
  (setq theme (ivy-read
                  "theme: "
                  (custom-available-themes)
                  :action '(1
                            ("t"
                             (lambda (theme)
                               (dolist (theme custom-enabled-themes)
                                 (disable-theme theme))
                               (load-theme (intern theme) t))
                             "switch theme"
                             )))
        )
  (load-theme (intern theme) t)
  )
```
but no matter where I call `ivy-toggle-calling` or `(setq ivy-calling t)` I don't get the behavior desired. Is there a proper way to call ivy-toggle-calling that I'm not doing? Thank you again for your help!

**Comment by bcmertz** [comment]
Solved with this https://github.com/abo-abo/swiper/issues/2210, thanks for all your help! I really love ivy :)

**Comment by basil-conto** [comment]
> Is there a proper way to call ivy-toggle-calling

The `ivy-calling` variable is buffer-local, so it needs to be set in the minibuffer.

In vanilla Emacs, this can be achieved using [`minibuffer-with-setup-hook`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Minibuffer-Misc.html), e.g.:

```el
(defun bcm/theme ()
  "Dynamic theming.
\\<ivy-minibuffer-map>\\[ivy-call] to preview theme without \
exiting completion."
  (interactive)
  (minibuffer-with-setup-hook
      (lambda () (setq ivy-calling t))
    (ivy-read "Theme: " (mapcar #'symbol-name (custom-available-themes))
              :action (lambda (name)
                        (mapc #'disable-theme custom-enabled-themes)
                        (load-theme (intern name) t))
              :caller #'bcm/theme)))
```

With Ivy, you can apply customisations like this more modularly:

```el
(defun bcm/theme ()
  "Dynamic theming.
\\<ivy-minibuffer-map>\\[ivy-call] to preview theme without \
exiting completion."
  (interactive)
  (ivy-read "Theme: " (mapcar #'symbol-name (custom-available-themes))
            :action (lambda (name)
                      (mapc #'disable-theme custom-enabled-themes)
                      (load-theme (intern name) t))
            :caller #'bcm/theme))

(with-eval-after-load 'ivy
  (push (cons #'bcm/theme (lambda () (setq ivy-calling t)))
        ivy-hooks-alist))
```

**Comment by bcmertz** [comment]
Awesome, thank you so much for all your help!

**Comment by basil-conto** [comment]
You're welcome, glad to help :).
