### ISSUE TITLE
Ivy will trigger insert-char error: `C-x 8 RET c` will input `^F` instead of `^L`.

### ISSUE THREAD

**Issue by hongyi-zhao** [abo-abo/swiper#2888]
On Ubuntu 20.04, I'm using git master version of Emacs and swiper with the following configuration:

```emacs-lisp
 (straight-use-package
 `(swiper :type git :host github :repo "abo-abo/swiper"
    :pre-build (
               ;("bash" "-c" "cd ~/.emacs.d/straight/repos/swiper")
               ;https://github.com/abo-abo/swiper/issues/2886#issuecomment-860605327
               ("make" "deps")
               ("make" "compile")
               )))
                    
(require 'ivy)
(ivy-mode 1)
(setq ivy-use-virtual-buffers t)
(setq ivy-count-format "(%d/%d) ")
```
I found the above configuration will trigger the insert-char error: `C-x 8 RET c` will input `^F` instead of `^L`, see the screenshot below for more detailed info:

![image](https://user-images.githubusercontent.com/11155854/124595458-9ff31980-de93-11eb-91ec-5a18b4f1e94b.png)

If I don't use the above configuration, the result will look like follows:

![image](https://user-images.githubusercontent.com/11155854/124595679-e6487880-de93-11eb-815f-cc93ffa43a8f.png)

It's well known that the second should be the expected character input by the corresponding typesetting sequence.

Any hints for this problem will be highly appreciated.

Regards,
HY

**Comment by basil-conto** [comment]
I don't think there's anything Ivy can do about this, i.e. as far as I'm concerned it's a pilot error arising from a known limitation of eager interactive completion systems like that of Ivy.

`C-x 8 RET` (`insert-char`) reads user input using the function `read-char-by-name`, which unconditionally calls `completing-read`.

In vanilla Emacs, no completion actually takes place until the user asks for it by typing e.g. `TAB`. So `read-char-by-name` actually behaves differently depending on whether you perform completion: you can enter either a hex codepoint like `c` (ASCII `^L`), or the equivalent Unicode name `FORM FEED (FF)`.

With Ivy, the completion happens straight away, so typing `c` just filters the set of Unicode names to those containing the character `c`. The first such result just happens to be `ACKNOWLEDE` (ASCII `^F`).

So the solution is to exit completion without selecting the current candidate, i.e. type `C-M-j` (`ivy-immediate-done`) instead of `RET` (`ivy-done`). See [`(info "(ivy) Key bindings for single selection action then exit minibuffer")`](https://oremacs.com/swiper/#key-bindings-for-single-selection-action-then-exit-minibuffer).

**Comment by hongyi-zhao** [comment]
Got it. Thank you very much for your insightful analysis.

**Comment by basil-conto** [comment]
You're welcome, glad it helped.

By the way: if you have `counsel` installed you can also use the command `counsel-unicode-char` as an alternative or in addition to `insert-char`.  It wouldn't really help in your `^L` scenario, but it has the benefit of including the codepoint, Unicode name, and a character preview all in one.

By the way part two: a faster way of inserting `^L` is `C-q C-l` (`C-q` causes any subsequent character sequence to be inserted literally).

**Comment by hongyi-zhao** [comment]
Thank you very much for your additional comments. 

Out of curiosity, I tried [this configuration](https://github.com/jeremyf/dotzshrc/blob/e063baf78b8049dede98dea2c84ec3329310806a/emacs/jnf-selectrum.el), and it gives the following fancy representations when I hit `C-x 8 RET`:

![image](https://user-images.githubusercontent.com/11155854/124620054-b907c480-deab-11eb-942b-0ef96df1af43.png)

**Comment by basil-conto** [comment]
> Any comments/hints/suggestions with this style?

Not sure what you're looking for - AFAICT that config uses Vertico, Consult, Marginalia, and Selectrum instead of Ivy and Counsel. I suggest you go with whichever set of packages works best for you.

**Comment by hongyi-zhao** [comment]
Thank you again for your advice.

**Comment by hongyi-zhao** [comment]
> By the way: if you have `counsel` installed you can also use the command `counsel-unicode-char` as an alternative or in addition to `insert-char`.

Thanks. I adopted the key binding suggested [here](https://github.com/jeremyf/dotzshrc/blob/e063baf78b8049dede98dea2c84ec3329310806a/emacs/jnf-ivy.el#L36):

`         ("C-x 8 RET" . counsel-unicode-char)`
