### ISSUE TITLE
ivy-mark seems to break in ivy-bibtex-with-local-bibliography

### ISSUE THREAD

**Issue by jsilve24** [abo-abo/swiper#2898]
I was just starting to look over ivy-bibtex and look at trying to extend it to act on multiple selected candidates when I ran into what I think is a bug on ivy's end. 

Steps to reproduce:
Opening bibliography (so far only tried local) `ivy-bibtex-with-local-bibliography` then `M-o` then `m` to mark entries. 

Expected behavior:
get a `> ` prefix in front of marked entry

Observed behavior:
nothing, in fact ivy seems ot freeze.  For example, before pressing `m` the arrow keys move between candidates. After pressing `m` the arrow keys no longer work...

**Comment by basil-conto** [comment]
Both the lack of a `>` mark, and the `Error in post-command-hook (ivy--queue-exhibit): (wrong-type-argument numberp nil)` when trying to mark a candidate, seem to be bugs in `ivy-bibtex-display-transformer`.

The error happens because `ivy-bibtex-display-transformer` assumes the internal Ivy property `idx` is on the first character of the candidate, whereas the addition of the `>` mark shifts the `idx` to the second character of the candidate.

Even if this is changed, though, `bibtex-completion-format-entry` doesn't seem to display Ivy `>` marks at the start of the candidate.

So unless someone can establish that Ivy's doing something wrong here, it looks to me like `ivy-bibtex` just doesn't support marks yet.

**Comment by jsilve24** [comment]
Cool thanks! This is super helpful. Sounds like this can be closed.

**Comment by basil-conto** [comment]
Great, thanks for confirming!

**Comment by basil-conto** [comment]
> The error happens because `ivy-bibtex-display-transformer` assumes the internal Ivy property `idx` is on the first character of the candidate, whereas the addition of the `>` mark shifts the `idx` to the second character of the candidate.

Correction: the `idx` property is not entirely internal, because while it's undocumented, it was announced in the release notes: https://github.com/abo-abo/swiper/blob/master/doc/Changelog.org#implement-unique-index-for-alist-completion

**Comment by basil-conto** [comment]
So I've now made `ivy-mark` preserve the `idx` property in commit 031d4d051da1d8fd20f0f46e8df66c426bf3174c.  This should at least avoid errors in `ivy-bibtex`, even if the mark prefix is not currently shown.
