### ISSUE TITLE
Swiper moves to the line of the first match when visual-line-mode is enabled

### ISSUE THREAD

**Issue by defaultxr** [abo-abo/swiper#291]
Similar to #290 except with the addition of visual-line-mode. I'm using the latest swiper from git so it doesn't look like the fix for that issue resolves the problem when visual-line-mode is enabled.

To reproduce:

1. Open emacs: emacs -Q
2. Go to scratch buffer: C-x b *scratch* RET
3. Enter some text, with a few lines being the same
4. Activate ivy-mode: M-x ivy-mode
5. Activate visual-line-mode: M-x visual-line-mode
6. Go to one of the duplicate lines (but not the first one)
7. M-x swiper
8. The point moves to the first instance of the duplicate line before any text is typed.

Also, thanks for writing this software, I'm already using ivy-mode as a replacement for helm and am enjoying it much more - it's so much faster and the keyboard shortcuts are much better.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by defaultxr** [comment]
Thanks, it doesn't seem to jump to the beginning anymore, but now it seems to jump down a few lines if the search is started from a point below a line that is "wrapped" with visual-line-mode.

**Comment by abo-abo** [comment]
Please provide an example: some text, `(window-width)` and `(point)` for which the bug happens.

**Comment by defaultxr** [comment]
It seems to be affected by the major mode that's in use. So far I've been able to reproduce it with buffers in emacs-lisp-mode (my init.el file) and org-mode (a sample file is attached). It doesn't seem to have any effect in fundamental-mode. I'm guessing it has something to do with the way these modes fontify the buffer.

(window-width) is 156 in the following example.
(point) is 3175 as noted in step 6.

[test.txt](https://github.com/abo-abo/swiper/files/36203/test.txt)

1. emacs -Q
2. Open this file
3. M-x org-mode
4. C-u 0 M-x org-global-cycle
5. M-x visual-line-mode
6. M-x goto-char 3175
7. M-x swiper

**Comment by abo-abo** [comment]
Thanks for the example.

The issue was specific to `org-mode` since `swiper` doesn't use visual line functionality with `org-mode`.  Besides being really slow (a general attribute of `visual-line-mode`), there was problem getting the outline-hidden text when `visual-line-mode` was on.

I've re-enabled it for `org-mode`, but it will now reveal all the headings (if `visual-line-mode` is on).

If you encounter the bug in a different mode, add another example. Also note that the visual line functionality is limited to the buffers smaller than 20000 (i.e. <20K files). For larger buffers, it's simply too slow to start up, because `visual-line-mode` is slow.
