### ISSUE TITLE
counsel-grep shows error code 2 when searching with non English string with rg backend

### ISSUE THREAD

**Issue by Ynjxsjmh** [abo-abo/swiper#2919]
I use `rg` as `counsel-grep` base command

```elisp
;; Use the faster search tools
(when (executable-find "rg")
  (setq counsel-grep-base-command "rg -S --no-heading --line-number --color never '%s' '%s'"))
```

However, when searching with non English string like `测试`, it gives me `error code 2`. I test the command `rg -S --no-heading --line-number --color never '测试' test.txt` on command line, it works fine with line number and line returned.

There is a similar issue comment before on https://github.com/abo-abo/swiper/issues/700#issuecomment-517664189 whose main language is neither English, he also faces this issue when searching with string like `настройки` after setting backend of `counsel-grep` to `rg`.

My OS is arch and emacs version is 27.2.

**Comment by basil-conto** [comment]
The docstring of `counsel-grep-base-command` says:

```
Format string used by `counsel-grep' to build a shell command.
It should contain two %-sequences (see function `format') to be
substituted by the search regexp and file, respectively.  Neither
%-sequence should be contained in single quotes.
```

The last sentence means you should use `%s` instead of `'%s'`.  When I do this I have no problem searching for `测试` with `rg` via `counsel-grep`, so I'm closing this as a pilot error.  If you still face an issue please reopen this issue and provide more detailed information on the steps you take.  Thanks.
