### ISSUE TITLE
Real fuzzy search?

### ISSUE THREAD

**Issue by kovrik** [abo-abo/swiper#294]
I'm trying to switch from Helm to Swiper (+Ivy and Counsel).

One problem is the way Swiper searches for candidates.

In Helm if I want to search for `emacs-lisp-mode` I press `M-x` and type `emlm` and it returns me correct match.

If I do `counsel-M-x` and type `emlm` it returns nothing.
It returns correct match only if I type `em l m`.

I understand, that Swiper is using regex to match candidates.
But I think that fuzzy != regex.

Is there a way to get Helm-like behaviour?

**Comment by ardpp** [comment]
Try setting
```
(setq ivy-re-builders-alist
      '((t . ivy--regex-fuzzy)))
```

**Comment by kovrik** [comment]
@ardpp 
Seems to work! Thank you!
(I was setting `ivy--regex-function` to `ivy--regex-fuzzy`. It didn't work)

**Comment by abo-abo** [comment]
> But I think that fuzzy != regex.

`emlm` with `ivy--regex-fuzzy` is `e.*m.*l.*m`. `em l m` with `ivy--regex-plus` is `em.*l.*m`.  They are both regex, but the first is more general, while the second is more specific. My preference is the second, since I think it's more powerful.

> I was setting ivy--regex-function to ivy--regex-fuzzy. It didn't work

That's because it's a temporary variable that gets reset all the time.  See also [info:ivy#Completion styles](https://github.com/abo-abo/swiper/blob/master/doc/ivy.org#completion-styles).  I'll also promote `ivy-re-builders-alist` to `defcustom` at some point, so it will be possible to set it with <kbd>M-x</kbd> `customize-group` `ivy`.
