### ISSUE TITLE
Counsel-ag has spurious unicode matches

### ISSUE THREAD

**Issue by antoine-levitt** [abo-abo/swiper#3017]
When trying to use counsel-ag on a codebase that has unicode characters, spurious matches are found. For instance, when trying to ag for "unique", the ag calling sequence (found by adding a print statement in counsel-ag-function) is 
```
("ag" "--vimgrep" "-i" "(?:(?:u[̀-̄̆̈-]|[uù-üũūŭůűųưǔǖǘǚǜȕȗᵘᵤṳṵṷṹṻụủứừửữựⓤｕ𝐮𝑢𝒖𝓊𝓾𝔲𝕦𝖚𝗎𝘂𝘶𝙪𝚞])(?:n[]|[nñńņňǹṅṇṉṋⁿₙⓝｎ𝐧𝑛𝒏𝓃𝓷𝔫𝕟𝖓𝗇𝗻𝘯𝙣𝚗])(?:i[̀-]|[iì-ïĩīĭįǐȉȋᵢḭḯỉịⁱℹⅈⅰⓘｉ𝐢𝑖𝒊𝒾𝓲𝔦𝕚𝖎𝗂𝗶𝘪𝙞𝚒])[qⓠｑ𐞥𝐪𝑞𝒒𝓆𝓺𝔮𝕢𝖖𝗊𝗾𝘲𝙦𝚚](?:u[̀-̄̆̈-]|[uù-üũūŭůűųưǔǖǘǚǜȕȗᵘᵤṳṵṷṹṻụủứừửữựⓤｕ𝐮𝑢𝒖𝓊𝓾𝔲𝕦𝖚𝗎𝘂𝘶𝙪𝚞])(?:e[̀-̄̆-]|[eè-ëēĕėęěȅȇȩᵉḕḗḙḛḝẹẻẽếềểễệₑℯⅇⓔｅ𝐞𝑒𝒆𝓮𝔢𝕖𝖊𝖾𝗲𝘦𝙚𝚎])|unique|\\b(u)\\w*\\W*\\b(n)\\w*\\W*\\b(i)\\w*\\W*\\b(q)\\w*\\W*\\b(u)\\w*\\W*\\b(e)\\w*)")
```
I don't really know what's going on, but this matches sequences that have unrelated unicode, such as for instance `#    xₙ₊₁ = xₙ + αₙ P⁻¹ f(xₙ)`. Doing "ag unique" from a shell works fine. Looks like the issue is in `counsel--grep-regex`, but I'm unable to debug further.

**Comment by basil-conto** [comment]
The generated regexp looks like the doing of `search-default-mode` when set to `char-fold-to-regexp` or similar (for more on this see [`(info "(emacs) Lax Search")`](https://gnu.org/s/emacs/manual/html_node/emacs/Lax-Search.html)).

Looks like `counsel--grep-regex` looks up the `re-builder` slot of the current `ivy-state` stored in `ivy-last`.

`counsel-ag` doesn't seem to specify an explicit `re-builder`, so I'm guessing the default one is computed in `ivy--reset-state` (one of the first steps in `ivy-read`).

What's your value of `ivy-re-builders-alist`?

The only place I can find where `search-default-mode` is used is in `swiper--re-builder`, which as the name implies is the `re-builder` used for `swiper` and `swiper-isearch`.

So at first glance I'm guessing `swiper`'s `re-builder` is being picked up, either as a result of local customisations, or because of a bug that results in a stale `re-builder` for `counsel-ag`.

Can you reproduce the issue starting from `emacs -Q` or `make plain`? I.e., with user customisations and other third-party packages out of the picture?

Thanks.

**Comment by antoine-levitt** [comment]
ivy-re-builders-alist : `((t . ivy-prescient-re-builder))`
search-default-mode : nil

> Can you reproduce the issue starting from emacs -Q or make plain? I.e. with user customisations and other third-party packages out of the picture?

Good catch. I can reproduce the issue with 
```
(require 'ivy-prescient)
(ivy-prescient-mode 1)
```
I have to confess I'm confused by all these packages, and I did this config years ago. Should I file the issue at ivy-prescient instead?

**Comment by basil-conto** [comment]
I'm unfamiliar with `prescient`, but have you tried setting the user option `prescient-use-char-folding` to `nil`?

**Comment by antoine-levitt** [comment]
Thanks, that fixes it. I have no idea what char folding is or why it should affect ag, though.

**Comment by basil-conto** [comment]
> Thanks, that fixes it.

Great! Can this issue be closed then?

> I have no idea what char folding is

If you're interested, have a look at the last few paragraphs in the section of the Emacs manual I linked to earlier: https://www.gnu.org/software/emacs/manual/html_node/emacs/Lax-Search.html#index-character-folding-in-search

Or from inside Emacs navigate to `C-h r char fold search TAB RET`.

> or why it should affect ag, though.

It shouldn't, at least not by default :).

**Comment by antoine-levitt** [comment]
OK, I'll open the issue at prescient, thanks!
