### ISSUE TITLE
how to refresh candidates

### ISSUE THREAD

**Issue by AnthonyDiGirolamo** [abo-abo/swiper#322]
Hello! I'm making the switch from helm to ivy/counsel/swiper and it's been great so far. I love the minimal impact your packages have.

One thing I miss from helm is being able too kill buffers from the buffer selection screen (helm-mini). I'm trying to reproduce this behavior with a hydra but I'm not sure if it's the best approach. I like pulling up hydras when ivy is active where I can emulate a vim normal mode similar to the ones I've seen on your blog.

Is there a way to kill a selected buffer and keep the ivy session open but have the killed buffer removed from the candidates list? Here is what I have so far (I'm an elisp noob):

```elisp
(defun amd-ivy-kill-buffer ()
  (interactive)
  (kill-buffer ivy--current)
  ;; refresh or remove current candidate from possible completions?
)

(defhydra hydra-counsel-switch-buffer (:color pink)
  ("k" amd-ivy-kill-buffer)
  ("h" ivy-beginning-of-buffer)
  ("n" ivy-next-line)
  ("e" ivy-previous-line)
  ("l" ivy-end-of-buffer)
  ("o" keyboard-escape-quit :exit t)
  ("C-g" keyboard-escape-quit :exit t)
  ("i" nil)
)

(define-key ivy-minibuffer-map (kbd "C-b") 'hydra-counsel-switch-buffer/body)
``` 

If there is a better workflow I'm very open to trying it. Thanks for your time!

**Comment by AnthonyDiGirolamo** [comment]
I should mention that this hydra is for use after calling `(switch-to-buffer)`.

**Comment by abo-abo** [comment]
You should be already able to do it: `ivy-mode` remaps `switch-buffer` to `ivy-switch-buffer`.

Once you've called `ivy-switch-buffer`, press <kbd>C-o ak</kbd> to set the current action to "kill", instead of "select".

Then use <kbd>j</kbd> and <kbd>k</kbd> to navigate and <kbd>g</kbd> to kill the selected buffer, with an update in the buffer list.

Or press <kbd>C-o</kbd> to hide the hydra and kill buffers without leaving session with <kbd>C-M-m</kbd>.

Also have a look at this bit in the source:

```elisp
(ivy-set-actions
 'ivy-switch-buffer
 '(("k"
    (lambda (x)
      (kill-buffer x)
      (ivy--reset-state ivy-last))
    "kill")
   ("j"
    ivy--switch-buffer-other-window-action
    "other")
   ("r"
    ivy--rename-buffer-action
    "rename")))
```

For your function, you're missing the `(ivy--reset-state ivy-last)` bit to refresh the buffer list.

**Comment by AnthonyDiGirolamo** [comment]
That is very helpful, thank you for the fast response! I knew about using <kbd>C-o</kdb> for pulling up the ivy-hydra but was completely missed the multiple actions feature. That seems like a better way to add more options.
