### ISSUE TITLE
why ivy is not available on melpa anymore?

### ISSUE THREAD

**Issue by redguardtoo** [abo-abo/swiper#36]

**Comment by abo-abo** [comment]
ivy.el was always part of the swiper repository.  MELPA allowed for
separate files from that repo to be separate packages.  But swiper is
also in GNU ELPA, and the inter-dependencies were causing build
problems.

It's easier for me to merge them together in MELPA, rather than split
them into separate repositories. And that's one repo less to merge
manually into GNU ELPA.

If you want ivy.el, just install swiper.

**Comment by redguardtoo** [comment]
got, thanks
