### ISSUE TITLE
completion-at-point triggers ivy completion but I don't want it for in-buffer completion

### ISSUE THREAD

**Issue by tsdh** [abo-abo/swiper#367]
Due to lack of time, I didn't follow ivy and emacs development closely in the last months.  I use a current emacs from the emacs-25 branch together with swiper 20160129.104 from MELPA.

The problem I face since recently is that `M-TAB` (calling `completion-at-point`) now triggers ivy completion instead of the traditional emacs completion which would simply complete up to the longest common prefix string and show a *Completions* buffer if it can't complete any further.  So now with `M-TAB` I'm put into the minibuffer with ivy completion.

I really love ivy but how can I opt out for using it for in-buffer completion?  I didn't find any customization variable that seemed relevant.

Steps to reproduce:

1. Maybe you need emacs 25 and the MELPA swiper package
2. `emacs -Q`
3. `M-x package-initialize RET` & `M-x ivy-mode RET`
4. Switch to *scratch* in case you're not there
5. Insert "(d" and hit `M-TAB` and you're put into the minibuffer with ivy completion

**Comment by abo-abo** [comment]
Welcome back:)

Too bad you don't like ivy's completion in region, I thought it was a universal improvement over the defaults, so there was no way to disable it.

## Example 1

In `*scratch*`, `|` is the point:

```elisp
(with-n|)
```

<kbd>C-M-i</kbd> results in:

```elisp
(with-no-warnings|)
```

without a completion session, because it's a single candidate.

## Example 2

```elisp
(d|)
```

<kbd>C-M-i</kbd> results in ivy completion with 1118 candidates, restricted to ones that start with `d`. Note that you can use <kbd>C-M-n</kbd> to cycle matching candidates: they will appear in the buffer right away.

Without `ivy-mode`, it results in a huge `*Completions*` window popping up, with 563 lines, 2 candidates on each line.

## Summary

I think with `ivy-mode` the completion is region becomes far easier. You can now disable it by setting `ivy-do-completion-in-region`. But I'd appreciate pointers to make it as good or better than the default.

**Comment by tsdh** [comment]
My full story is that I already use `company-mode` for in-buffer completion and almost never have a need for `M-TAB`.  However, I use `(setq tab-always-indent 'complete)` so a normal `TAB` might either indent or complete, the latter triggering ivy in region completion.

One thing which I got used to is that the standard emacs completion places point after the completed symbol even if it actually didn't need to complete anything and the current symbol already was the single possible match, e.g., with `(do|list` `M-TAB` results in `(dolist|` where | is point.  I'd suggest that ivy acts likewise.  (I have the habit to use that as a kind of forward-symbol.  I know that's a bit awkward but `TAB` is just convenient. ;-))

And sometimes, when there are many completions, I do like a *Completions* buffer because it is usually 2 columns wide, sorted, and I can easily scroll it page-wise by just hitting `TAB` again.  (I guess I can sort the ivy in region candidates, too, right?)

That said, I also see the positive sides of ivy in region.  It's just triggered too often when I don't want it.  (I'm constantly tabbing out of habit...)

What I could imagine was that the ivy in region completion was triggered only when I call `completion-at-point` interactively (`M-TAB`) but not when that is called by something else like `indent-for-tab-command` (`TAB`) in my case.
