### ISSUE TITLE
ivy-mode: File completion order

### ISSUE THREAD

**Issue by tsdh** [abo-abo/swiper#38]
Currently, the files and directories are sorted alphabetically with directories coming first.  Most of the time, I want to find a file in the current directory, and then having directories first is inconvenient.  Also, alphabetical sorting with is usually not what one would expect.  Instead, one would usually expect a sorting according to `string-collate-lessp` which gives the order you'd get in a shell, too.

Long story short: I think it would be nice if there were customize options that allow to specify the sorting order.  E.g., a value for file completion could be `'(#'ivy-directories-first-p #'string<)` which would replicate the current behavior, and I would just go with `'(string-collate-lessp)` to get the behavior I like.

BTW: I don't see a reason to have `./`, i.e., the current directory, in file completion matches, and also `../` is questionable as you can go up one directory with `DEL` anyway.

**Comment by abo-abo** [comment]
Thanks for the suggestions, I'll look into it.  The file completion feature is only a day old, I haven't worked out all the bits.

The reason for `./` is so that you can select the current directory and exit with <kbd>C-j</kbd> or <kbd>C-m</kbd>.  Currently, there's no other way to do it if you already entered a directory that you want to select, unless you've planned ahead and pressed <kbd>C-m</kbd> and not <kbd>C-j</kbd> while selecting the directory that you wanted.

**Comment by abo-abo** [comment]
> sorting according to string-collate-lessp which gives the order you'd get in a shell, too

That's an Emacs25 C function though. It's not even in 24.5. Do you know of an Elisp equivalent?

**Comment by tsdh** [comment]
I don't think there is one, but `string-lessp` is good enough if it's not available.

**Comment by abo-abo** [comment]
OK, this should do it for you:

```elisp
(setq ivy-sort-file-function 'string-lessp)
(setq ivy-extra-directories nil)
```

You can even have `string-collate-lessp` if you're on 25.

**Comment by tsdh** [comment]
Thank you!
