### ISSUE TITLE
Copying and yanking current candidate

### ISSUE THREAD

**Issue by Andre0991** [abo-abo/swiper#381]
Sometimes I would like to copy the text of the selected candidate and/or insert it in the buffer I'm editing. This can be done in Helm with `C-c C-y` and `C-c C-i`, for example.

Is there a command to do this in Ivy? I looked at `ivy-minibuffer-map` and haven't found anything. The closest is `M-i`, but it doesn't copy the candidate.

Thanks and sorry if I'm missing something obvious here.

**Comment by Andre0991** [comment]
Never mind: I found a way in one of your comments on `oremacs`.

`C-SPC C-a M-y`, which I didn't know because I actually haven't managed to learn Emacs editing keybindings (I've been using Evil since day one).

I think I'll use this everyday so I'll probably bind it to some key.

**Comment by abo-abo** [comment]
The equivalent of helm's <kbd>C-c C-y</kbd> is <kbd>M-i</kbd> (mnemonic for "insert").  There no equivalent for helm's <kbd>C-c C-i</kbd>, but it's easy to make one.

You can add your own actions to any or every ivy command. For example:

    (defun ivy-yank-action (x)
      (kill-new x))
    
    (defun ivy-copy-to-buffer-action (x)
      (with-ivy-window
        (insert x)))
    
    (ivy-set-actions
     t
     '(("i" ivy-copy-to-buffer-action "insert")
       ("y" ivy-yank-action "yank")))


Now you can press <kbd>M-o y</kbd> in any session to yank the current candidate, and <kbd>M-o i</kbd> to insert it into the buffer.

You can also do it without finishing the completion by using <kbd>C-M-o</kbd> instead of <kbd>M-o</kbd>.

**Comment by Andre0991** [comment]
Thanks @abo-abo, adding actions it's dead simple, indeed. I'm using those now :)

**Comment by Andre0991** [comment]
Just one caveat: `i` might conflict with `info`, so I am able to choose only one of them. I think I'll  use upper case letters for my own actions in case of conflict. I don't know if there's a better way to prevent this situation.

Maybe it would be nice if after pressing `i` another letter showed up in all `i` actions (something avy-like), although it'd be better to not have this situation at all in the first place.

**Comment by abo-abo** [comment]
> it'd be better to not have this situation at all in the first place, of course.

Let's go with that for now, no need to complicate things. It's just like minor and major mode bindings - there are bound to be conflicts, because of all the combinations, but the user can resolve them.

**Comment by Andre0991** [comment]
> no need to complicate things

I don't think this is possible - if you choose to leave it as it is, there will be a complication on the users side; if you decide to implement something to handle repeated letters, there's complication on your side - [this trade-off is ancient](https://www.jwz.org/doc/worse-is-better.html) :)

But I agree, it might be too early to jump to the implementation, perhaps someone will come up with a more elegant solution for this.

**Comment by abo-abo** [comment]
What I mean here is that e.g. <kbd>C-f</kbd> is bound to `forward-char` by default. The users are advised not to use that binding in their config, and otherwise have to deal with the repercussions.

Isn't the fact that <kbd>i</kbd> is bound in `counsel-describe-function` by default make it similar to <kbd>C-f</kbd> and `forward-char`? Means the user is advised not to use <kbd>i</kbd> as a global binding ...

However, if the user *really* wants to bind <kbd>i</kbd> globally, then this code need to be overridden in the user config:

```elisp
(ivy-set-actions
 'counsel-describe-function
 '(("i" counsel-info-lookup-symbol "info")
   ("d" counsel--find-symbol "definition")))
```

**Comment by Andre0991** [comment]
Fair point.

I'll just rebind those custom actions - I don't think I'll add more global actions anyway, just specific ones, so this sort of issue probably won't happen very frequently.
