### ISSUE TITLE
Efficiency of counsel--async-filter

### ISSUE THREAD

**Issue by hmelman** [abo-abo/swiper#395]
`counsel--async-filter` is using `(forward-line (buffer-size))` on the whole buffer to compute the number of candidates to show in the prompt. Since it's also doing `(split-string (buffer-string) "\n" t)` to find all the candidates couldn't it just do length on the result to get the size and save a second traversal through the whole buffer?

**Comment by abo-abo** [comment]
I remember thinking the same when I wrote it. It turned out that `forward-line` method is just faster.

Of course, it could be faster if I wrote my own `split-string` that also counted the number of elements while splitting. But that's not very productive.  And I think the bottleneck is in Emacs' interaction with processes anyway (sometimes 4x slower than a shell tool), so nothing I do will produce a very significant speedup (or slowdown).

In any case, if you have an optimization that improves performance and some data to prove it, feel free to PR.
