### ISSUE TITLE
add update-fn to swiper-all

### ISSUE THREAD

**Issue by hmelman** [abo-abo/swiper#401]
I added the following to swiper-all so that navigating the list shows the item in its buffer
    :update-fn (lambda () (swiper-multi-action-2 ivy--current))

I'm not sure if it was deliberately left out or not (doesn't seem to be slow). In helm, enabling this behavior is via helm-follow-mode which can be toggled while executing a command. I don't see a way in swiper I can enable this without redefining the defun in my config and missing out on any future updates without manually checking them.

**Comment by abo-abo** [comment]
Thanks, that's a very nice improvement.

I wrote `swiper-all` as an experiment. Didn't use it because of the slow startup time - 3 seconds for 70000 lines across 135 buffers.

But with some caching and a collection interface that doesn't need to `append` all 135 sources into a single list it could be much faster. This could be a nice feature to work on in the future.

**Comment by hmelman** [comment]
Great. It's been useful to me in learning swiper/ivy/counsel and searching across 5-10 buffers. It feels like every ivy command should have an update-fn and there should be an ivy-map keybinding to toggle auto-updating of position and perhaps some properties so some commands could have it turned off by default.

**Comment by abo-abo** [comment]
> an ivy-map keybinding to toggle auto-updating of position and perhaps some properties so some commands could have it turned off by default.

There is one already: <kbd>C-o c</kbd> (`ivy-toggle-calling`).
