### ISSUE TITLE
swiper-all + ivy-occur + wgrep

### ISSUE THREAD

**Issue by manuel-uberti** [abo-abo/swiper#423]
As of now, with latest `swiper` and `ivy` from MELPA I can play with `ivy-occur` and `wgrep` only if I issue `C-c C-o` from `M-x swiper`. The buffer I get from `C-c C-o` during `swiper-all` doesn't let me use `wgrep`. 

When using `M-x swiper`, I can see at the top of the `ivy-occur` buffer the following line:
```
-*- mode:grep; default-directory: "/home/manuel/org/" -*-
```

This line doesn't appear in the `ivy-occur` buffer generated by pressing `C-c C-o` during `M-x swiper-all`. So I guess I am not in grep mode.

Is this the intended behaviour?

**Comment by abo-abo** [comment]
In order for `wgrep` to work, the buffer has to be reformatted in a suitable way.

For `swiper` and `counsel-git-grep` this is done via:

    (ivy-set-occur 'counsel-git-grep 'counsel-git-grep-occur)
    (ivy-set-occur 'swiper 'swiper-occur)
    
If you'd like to implement `swiper-all-occur`, you'll need to:

1. Group all files under a single `default-directory` (sometimes impossible, e.g. with remotes).
2. Reformat the candidates to show the path and line number.

I'm not a big fan of `swiper-all`, since it's not very fast. A single large buffer can really slow down things.  Besides, since I'm always in some git project, `counsel-git-grep` looks through everything anyway.

**Comment by manuel-uberti** [comment]
Oh I see.

However, I'm not in a git project but in a directory with many Org files for my writings, so I cannot rely on `counsel-git-grep`.

No problem, though, I really don't want to make it complicated for you. I have always `ag` and `wgrep-ag` for such cases.

**Comment by abo-abo** [comment]
You can now use `wgrep` with `ivy-occur` and `counsel-ag`.

**Comment by manuel-uberti** [comment]
Awesome, thanks!
