### ISSUE TITLE
Naming convention for third-party libraries?

### ISSUE THREAD

**Issue by justbur** [abo-abo/swiper#445]
I'm going to port helm-bibtex to use an ivy backend. Do you prefer the name counsel-bibtex, ivy-bibtex, or something else?

**Comment by abo-abo** [comment]
I'd prefer for third party libraries to be called e.g. `bibtex-completion`, and offer completion for as many back ends as possible. That means first try to see if `completing-read` is enough. And if it's not, offer both a Helm and Ivy variant, or whatever else you're interested in.

Hopefully, we'll get an better `completing-read` interface soon, so that functions can be written to simply give completion, and will work automatically if `helm-mode` or `ivy-mode` are enabled.

**Comment by justbur** [comment]
Hm, yes that would be ideal. I'll see if the helm-bibtex maintainer wants
to build it into his package. As you know, helm has its own way of doing
things, so there is still some translation needed. Having multiple actions
is useful for this package, and that's not easily doable with
completing-read at the moment.

**Comment by justbur** [comment]
We're taking care of it. Thanks for the feedback
