### ISSUE TITLE
Prototype for initial counsel-projectile

### ISSUE THREAD

**Issue by DamienCassou** [abo-abo/swiper#471]
I've just wrote the following that might be useful to others. I can send a PR against `counsel.el` if you want.

```emacs
(defun counsel-projectile-switch-project ()
      (interactive)
      (ivy-read "Switch to project: "
                projectile-known-projects
                :require-match t
                :action '(1
                          ("o" projectile-switch-project-by-name "Select file in project")
                          ("g" projectile-vc "Open project using vc-dir, magit or monky"))))
(with-eval-after-load "projectile"
      (define-key projectile-command-map (kbd "p") #'counsel-projectile-switch-project))
```

**Comment by abo-abo** [comment]
Seems fine, please PR. But don't touch `projectile-command-map`. Maybe in `counsel-mode` with a remap, the user should be able to restore the old state.

**Comment by DamienCassou** [comment]
This is how it's done with `helm-projectile`: https://github.com/bbatsov/helm-projectile/blob/master/helm-projectile.el#L814. What do you think?

**Comment by abo-abo** [comment]
OK, it's fine like this.

**Comment by ericdanan** [comment]
If it helps, I use the following function

```
(defun counsel-projectile ()
  (interactive)
  (ivy-read "Switch to project: "
	    projectile-known-projects
	    (if (projectile-project-p)
                (cons (abbreviate-file-name (projectile-project-root))
                      (projectile-relevant-known-projects))
              projectile-known-projects)
	    :action 'projectile-switch-project-by-name
	    :require-match t
	    :caller 'counsel-projectile))
```

And the following additional actions

```
(ivy-set-actions
 'counsel-projectile
 '(("f" (lambda (dir)
	  (let ((projectile-switch-project-action 'projectile-find-file))
	    (projectile-switch-project-by-name dir)))
    "find file")
   ("F" (lambda (dir)
	  (let ((projectile-switch-project-action 'projectile-find-file-other-window))
	    (projectile-switch-project-by-name dir)))
    "find file other window")
   ("d" (lambda (dir)
	  (let ((projectile-switch-project-action 'projectile-find-dir))
	    (projectile-switch-project-by-name dir)))
    "find directory")
   ("D" (lambda (dir)
	  (let ((projectile-switch-project-action 'projectile-find-dir-other-window))
	    (projectile-switch-project-by-name dir)))
    "find directory other window")
   ("b" (lambda (dir)
	  (let ((projectile-switch-project-action 'projectile-switch-to-buffer))
	    (projectile-switch-project-by-name dir)))
    "switch to buffer")
   ("s" (lambda (dir)
	  (let ((projectile-switch-project-action 'projectile-save-project-buffers))
	    (projectile-switch-project-by-name dir)))
    "save all buffers")
   ("k" (lambda (dir)
	  (let ((projectile-switch-project-action 'projectile-kill-buffers))
	    (projectile-switch-project-by-name dir)))
    "kill all buffers")
   ("r" (lambda (dir)
	  (let ((projectile-switch-project-action
		 'projectile-remove-current-project-from-known-projects))
	    (projectile-switch-project-by-name dir)))
    "remove from knwon projects")
   ("l" (lambda (dir)
	  (let ((projectile-switch-project-action 'projectile-edit-dir-locals))
	    (projectile-switch-project-by-name dir)))
    "edit dir-locals")
   ("g" (lambda (dir)
	  (let ((projectile-switch-project-action 'projectile-vc))
	    (projectile-switch-project-by-name dir)))
    "open in vc-dir / magit / monky")
   ("n" (lambda (dir)
	  (let ((projectile-switch-project-action 'projectile-org-notes))
	    (projectile-switch-project-by-name dir)))
    "open notes")))
```

The `if`` statement in the function is makes the current project show up first in the list of candidates, so I can quickly apply actions to it.

**Comment by abo-abo** [comment]
@ericdanan Wow, that's really a lot of stuff. You should consider starting something like this: https://github.com/bbatsov/helm-projectile.

**Comment by DamienCassou** [comment]
@ericdanan why are your actions always going through `projectile-switch-project-by-name` instead of just calling the function you put in `projectile-switch-project-action`? You also seem to be much more ready to submit the PR yourself :-).

**Comment by ericdanan** [comment]
@DamienCassou because some functions don't take the project root as optional argument (`projectile-vc` does, but eg `projectile-find-file` or `projectile-switch-to-buffer` don't). So the workaround I found is to let-bind `projectile-project-action` and call `projectile-switch-project-by-name`.

Also this makes sure that `projectile-before-switch-project-hook` and `projectile-switch-project-action-hook` are run. Personally I use the former hook to make sure the dir-locals of the project root are loaded before `switch-project-action` is called.

And sure I can do the PR.

@abo-abo Do you mean that I should rather add a single action to call `helm-projectile` instead of using my long action list? In fact I was using `helm` and `helm-projectile` before, but I find `ivy` more convenient than `helm` and now that I switched to it it seems simpler to me to add a list of `ivy` actions rather than loading `helm`. So I defined this `counsel-projectile` function as a replacement for `helm-projectile`. I may misunderstand you, please let me know what you have in mind so I can prepare a PR.

**Comment by abo-abo** [comment]
@ericdanan 

> I may misunderstand you, please let me know what you have in mind so I can prepare a PR.

Make a PR if that suits you best. Although you need to have an Emacs CA for changes over 15 lines.

But I was actually suggesting that you start your own repository `counsel-projectile` to keep things neatly separate, instead of adding a large amount of code to `counsel.el`. And put `counsel-projectile` on MELPA.

**Comment by ericdanan** [comment]
OK then I will create a separate repository for `counsel-projectile` and let you know when it is ready.

**Comment by manuel-uberti** [comment]
Thanks for the code, @DamienCassou. I'll add it to my setup while I wait for your PR. ;)

**Comment by DamienCassou** [comment]
@manuel-uberti you'd better hope for @ericdanan to create a new project. His code is much more advanced.

**Comment by manuel-uberti** [comment]
^ Indeed, but yours is all I need. :)

**Comment by ericdanan** [comment]
OK I just created a repository:

https://github.com/ericdanan/counsel-projectile

I basically copied there the code I pasted at the beginning of this thread with a couple of minor changes:
- Added optional `arg` to invalidate projectile cache (as in `projectile.el`)
- Defined `counsel-projectile-find-file`, `counsel-projectile-find-dir`, and `counsel-projectile-switch-to-buffer` with additional action to find/switch in other window (this allowed me to shorten a bit the long list of `counsel-projectile` actions).

I hope this is more or less what you had in mind @abo-abo and others. I did not yet submit the file to MELPA because:
- I have to read the documentation on how to do it
- I did not yet write a readme.md
- I guess the code needs a lot of improvement beforehands

Any feedback is very welcome!

**Comment by DamienCassou** [comment]
@ericdanan thank you very much

- I can do the melpa process if you want, I did many already
- line 164: knwon -> known
- helm-projectile has a feature to start an eshell on a project

**Comment by abo-abo** [comment]
@ericdanan Looks very good, thanks. Congrats on your first Elisp repo :)

**Comment by manuel-uberti** [comment]
Very nice, great job @ericdanan!

**Comment by ericdanan** [comment]
Thank you all!

@DamienCassou I fixed the typo and added the `eshell` action (I suppose it it `projectile-run-eshell`). I will be very grateful if you do the MELPA process for me when it is time to do so (I don't know what is the good practice, wait for the library to improve or make it available early). In any case I will try to write a short `README` soon.

**Comment by ericdanan** [comment]
Just to let you know that `counsel-projectile` is now available from `MELPA` and `el-get`.

I guess it is better to close the dicsussion here and continue there if you have more suggestions.

Thank you again.

**Comment by abo-abo** [comment]
@ericdanan Thanks, closing this one. I'd suggest to add an infrastructure for byte-compilation, and maybe testing in the future. I can send a PR if you like.

**Comment by ericdanan** [comment]
@abo-abo I don't know how to do that but I would of course be happy to
receive a PR.
