### ISSUE TITLE
Help using ivy-read API over a text file

### ISSUE THREAD

**Issue by kaushalmodi** [abo-abo/swiper#478]
Hi,

I have a CSV text file like this:

```
a,b,x
c,d,y
e,f,x
g,h,x
```

I've got something working using the below:

```el
;; http://stackoverflow.com/a/20747279/1219634
(defun modi/read-file (f)
  "Return the contents of file F as a string."
  (with-temp-buffer
    (insert-file-contents f)
    (buffer-substring-no-properties (point-min) (point-max))))

(defun my/ivy-insert-from-file ()
  (interactive)
  (let ((ivy-height 5))
    (ivy-read "Task: "
              (split-string (modi/read-file "/path/to/file")
                            "\n" :omit-nulls)
              ;; :matcher ??
              ;; ??
              :action #'insert)))
```

But I need some help with the following:

1. Need the `ivy-read` to show only the lines that end in `\bx$` as possible selection candidates.
2. If the `a,b,x` line is selected, insert that line as `||a|b|` instead of `a,b,x`.

**Comment by abo-abo** [comment]
> Need the ivy-read to show only the lines that end in \bx$ as possible selection candidates.

Simple:

```elisp
(cl-remove-if-not
 (lambda (x)
   (string-match "x$" x))
 (split-string (modi/read-file "test.csv") "\n" t))
```

> if the a,b,x line is selected, insert that line as ||a|b| instead of a,b,x.

Not very clear what the rule is, but something like this:

```elisp
(lambda (x)
  (insert
   (format "||%s|"
           (mapconcat #'identity
                      (delete "x" (split-string x ","))
                      "|"))))
```

The whole code:

```elisp
(defun my/ivy-insert-from-file ()
  (interactive)
  (let ((ivy-height 5))
    (ivy-read "Task: "
              (cl-remove-if-not
               (lambda (x)
                 (string-match "x$" x))
               (split-string (modi/read-file "test.csv") "\n" t))
              :action
              (lambda (x)
                (insert
                 (format "||%s|"
                         (mapconcat #'identity
                                    (delete "x" (split-string x ","))
                                    "|")))))))
```

**Comment by kaushalmodi** [comment]
That works! Thank you!

I was curious if I needed `:matcher` or `:predicate` for this. I read the `ivy` docs but the API was not clear from that. For example, the `:matcher` takes any function that has `(RE STRING)` as args. I learnt that from its example uses. Also I see the use of the global var `ivy-text` at places.

Can you please please elaborate of how each `:OPTION` to `ivy-read` is designed to be used in its manual? Also what other variables like `ivy-text` are designed to be used in the API?

**Comment by abo-abo** [comment]
> I was curious if I needed :matcher or :predicate for this. I read the ivy docs but the API was not clear from that. For example, the :matcher takes any function that has (RE STRING) as args. I learnt that from its example uses. Also I see the use of the global var ivy-text at places.

`:matcher` should not be needed too often. The matcher replaces the whole matching process, i.e. it overrides the `:re-builder` etc.  A good example of `:matcher` is `counsel-git-grep-matcher`: since the regular re-builder can't accomplish the task of stripping the file and line information from the match, it's done this way.

`:predicate` is a relic of `completing-read`. It's a predicate that applies to the collection before using it. But it occurs to me: why not apply the predicate yourself?  The code `(ivy-read "foo: " bar :predicate pred)` is absolutely equivalent to `(ivy-read "foo: " (cl-remove-if-not pred bar))`.

In your particular case, you simply need to modify your collection to exclude a few strings. There's no reason to pass the unmodified collection to `ivy-read`.

> Also I see the use of the global var ivy-text at places.

At all times, `ivy-text` is the current input string. At some point I want to move it into an `ivy-last` field.

> Can you please please elaborate of how each :OPTION to ivy-read is designed to be used in its manual? Also what other variables like ivy-text are designed to be used in the API?

I'll try to add some docs when I have the time. Contributions welcome.
