### ISSUE TITLE
ivy breaks multi-isearch

### ISSUE THREAD

**Issue by PythonNut** [abo-abo/swiper#482]
`multi-isearch` is probably not the only thing broken by this, but it's the only one I can think of ATM.

**Steps to reproduce**

* <kbd>M-x</kbd> `multi-isearch-buffers` <kbd>RET</kbd>
* <kbd>RET</kbd>

Now, try to <kbd>RET</kbd> to start the search. Unfortunately, because `ivy` requires a match, you can't escape.

**Comment by abo-abo** [comment]
Works fine for me. I've seen this problem too many times: <kbd>C-j</kbd> or <kbd>RET</kbd> selects the current candidate, while <kbd>C-M-j</kbd> (`ivy-immediate-done`) selects the current text.

You'll just have to get used to `ivy-immediate-done` being on <kbd>C-M-j</kbd>. If I put it on <kbd>RET</kbd> it would wreck havoc: selecting the input instead of the candidate means completion does nothing.

**Comment by abo-abo** [comment]
Please confirm that <kbd>C-M-j</kbd> actually works for you.

**Comment by PythonNut** [comment]
Yes, <kbd>C-M-j</kbd> works fine for me. Thanks for pointing that out.
