### ISSUE TITLE
ivy-switch-buffer prefers special buffers

### ISSUE THREAD

**Issue by benmaughan** [abo-abo/swiper#522]
Hi,
First, thanks for the great software!
I see some unexpected (to me) behaviour in `ivy-switch-buffer`. Say I have two buffers called

     out.txt
     *Shell Command Output*

and I start `ivy-switch-buffers` and type "out" then the `*Shell Command Output*` buffer is highlighted and I have to continue typing or use the arrows to select `out.txt`. I would have expected `out.txt` to be the preferred match since the string is at the start of the buffer name. I realise I could type "^out" to match `out.txt` but I would have expected the priority of the results to be different. This seems to be the case whenever there is a `*special*` buffer that matches the search string anywhere in the name.

Is this the intended behaviour?

Cheers,
 Ben

**Comment by ardpp** [comment]
This is the expected behaviour as far as I know. See if https://github.com/abo-abo/swiper/issues/513 and https://github.com/abo-abo/swiper/issues/496 answer your question.

Andrej

**Comment by abo-abo** [comment]
This is a bug related to the fact that `ivy-switch-buffer` starts with candidate index 1 instead of the usual index 0. This is to enable the quick last buffer cycle with <kbd>RET</kbd>. This behavior is compatible with Emacs defaults and isn't going away.

However, this reveals that bug in the anchoring algorithm. The anchoring algorithm recomputes the candidate index with updates in the input.  It tries to make it so the closest matching candidate below the previous one is selected. This fix isn't trivial, and I don't have enough time to fix it properly right now. So this issue and the mentioned ones will have to stay open for a while.

The simplest way to fix it is to reset the index to 0 with each input, however it's a lazy solution and I'd rather have the proper one.

**Comment by benmaughan** [comment]
Thanks for clarifying.
