### ISSUE TITLE
Different file matching algorithms

### ISSUE THREAD

**Issue by hmelman** [abo-abo/swiper#551]
I have two directory in $HOME:

~/Delicious Library/
~/elisp/

I often want to go to the ~/elisp directory and use counsel-find-file and type `eli` but it matches the first directory and not the second. 

As I understand it, it's because this is the generated sort order because "D" is before "e" and this is known before I start typing. Fine. Still after I've type "eli" or just "el" or even "e" I'd like "elisp" selected before the other because it's the beginning of the name even if they are listed in this same order. After looking at customize group and the manual I'm not sure if I need to customize sorting (does that only happen before typing?) or some matching process. Pointers appreciated.

**Comment by abo-abo** [comment]
Sorting in Ivy can happen twice for Sync collections (your case) and once for Async collections (e.g. `counsel-git-grep`).

In the first stage of Sync collection completion, all possible candidates are retrieved and sorted.  The variable customizing this is `ivy-sort-functions-alist`. For file name completion, by default you get `ivy-sort-file-function-default`, which puts directories ahead of files and sorts alphabetically. This explains your situation: `Del..` is before `elisp` alphabetically. And as long as they both match, you'll likely have `Del..` as your selected candidate.

In the second state of Sync collection completion (applies to Async as well) is `ivy-sort-matches-functions-alist`. This one sorts only the matches for your current input.  This can be very inefficient for a large number of matches, since you'd be doing a sort after each key press.  See e.g. the interaction of `ivy-flx-limit` and `ivy--flx-sort`.

As for possible solutions, the first one is to use `ivy--regex-fuzzy` and `flx`. I don't use it myself, but it will certainly have a different candidate ordering.

A second solution is to use something like `smex` for everything, not just `counsel-M-x`. Then your most often used candidates will be sorted first. See #436.

**Comment by sooheon** [comment]
So to fix hmelman's issue, a third solution can be to write the appropriate sorting function and add it to `ivy-sort-matches-functions-alist`, under `counsel-find-file`?

**Comment by abo-abo** [comment]
@sooheon Yes, exactly.

**Comment by sooheon** [comment]
Well then we already have a function written for that it seems. @hmelman try the following:

```
(setq ivy-sort-matches-functions-alist '((t . nil)
                                        (ivy-switch-buffer . ivy-sort-function-buffer)
                                        (counsel-find-file . ivy-sort-function-buffer))
```

This makes counsel-find-file use the same sorting as ivy-switch-buffer, which prioritizes matches at start.

**Comment by hmelman** [comment]
That does seem to help. With that the string "el" in my `~/` matches `elisp/` before `.eshell` which is definitely better.

**Comment by abo-abo** [comment]
@hmelman Is your issue solved then?

**Comment by hmelman** [comment]
Yes. Thanks.

**Comment by abo-abo** [comment]
You're welcome.
