### ISSUE TITLE
First character cut off in ivy buffer

### ISSUE THREAD

**Issue by landakram** [abo-abo/swiper#602]
Hi! I recently switched from helm to ivy, and I'm experiencing a strange visual bug with ivy that I'm not sure how to proceed with. 

Basically, the ivy completion buffer has the first character cut off for most completions. In addition, when I cycle through the entries, the buffer "redraws" the highlighted entry over a position, but still with the first character missing. It's a little hard to visualize, so I've attached a GIF that is worth a thousand words: 

![ivy-visual-bug](https://cloud.githubusercontent.com/assets/700616/17187708/3a869a10-53ef-11e6-99f2-90b1483f872b.gif)

As you can see, some entries are _not_ cut off, like `init.el`, which is the last entry visible in the buffer. In fact, the last visible entry is _always_ shown correctly, even when I scroll down. As soon as the last entry becomes the second to last entry, its first character gets cut off. 

I'm relatively new to emacs and ivy, so I'm not sure if this is an ivy specific issue or something wrong elsewhere, but other commands in the minibuffer don't get cut off.

Also, it seems to happen with all ivy-related commands (i.e. `swiper`, `counsel-M-x`, `counsel-find-file`, etc.) as well as a command I have defined myself that uses ivy's completion for `apropos`. 

Has anyone experienced this issue or could point me in the right direction for debugging it?

**Comment by abo-abo** [comment]
> I'm relatively new to emacs and ivy, so I'm not sure if this is an ivy specific issue or something wrong elsewhere, but other commands in the minibuffer don't get cut off.

This is likely caused by another loaded package.

Here's a workflow for this type of bug for *any* type of Emacs package (not just `ivy`):

### Step 1: see if you can reproduce with `emacs -Q`

If you can, it means that I can probably reproduce it too and maybe fix it.

What I would suggest is making a file `temp-init.el`, put only `ivy` config there and launch a new Emacs like this:

    emacs -Q -l temp-init.el
    
Then see if the bug still happens. If it does not, move on to step 2.

### Step 2: bisect your config

Comment out about half of your config (but not the package that you're debugging) and restart Emacs.  Check if the bug still happens.
If it does, it means it's in the un-commented config, otherwise swap the commented and un-commented config.

Once you've narrowed the bug to only half of your code, split it in half once more. And so on, until you find the offending line.

**Comment by landakram** [comment]
@abo-abo, thank you so much for the advice. 

I managed to narrow the cause down to this line in my config: 

```
(setq-default left-margin-width 1)
```

Removing it solved the visual bug in the ivy buffer, which makes total sense. And now I have a much better strategy for debugging issues in the future!
