### ISSUE TITLE
Question: list most recent commands, and delete multiple buffers

### ISSUE THREAD

**Issue by ttmarek** [abo-abo/swiper#682]
Hi, I'm looking to replace Helm with ivy, swiper, counsel. I've been playing around with it for a couple of days and I'm really liking it. Nice work! I just have a few questions:

1. In helm, my most recent commands show up at the top of the `M-x` list. Is there a way to configure `counsel-M-x` to do the same?

2. Is there a way to delete multiple buffers in counsel/ivy?

Keep up the good work :smile:

**Comment by abo-abo** [comment]
> In helm, my most recent commands show up at the top of the M-x list. Is there a way to configure counsel-M-x to do the same?

Install `smex` package, `counsel-M-x` uses it automatically.

> Is there a way to delete multiple buffers in counsel/ivy?

1. Press <kbd>C-M-o k</kbd> to delete a buffer without exiting. 
2. If you matched a big group and want to delete them all, press <kbd>C-c C-o</kbd> which generates a new `ibuffer`, then <kbd>tD</kbd>.
3. Press <kbd>C-M-a k</kbd> to select the "kill" action for the current session. From here on, <kbd>C-M-m</kbd> and <kbd>C-M-n</kbd> will kill buffers instead of selecting them.
4. A variation of 3: <kbd>C-o ak</kbd> to select the "kill" action, <kbd>j/k</kbd> to navigate, <kbd>g</kbd> to kill.

**Comment by ttmarek** [comment]
Thanks @abo-abo!
