### ISSUE TITLE
make counsel-ag search the whole project directory instead of only the current directory ?

### ISSUE THREAD

**Issue by CSRaghunandan** [abo-abo/swiper#686]
Looks like `counsel-ag` only checks for files under the **current directory**. Is it possible to get `counsel-ag` to search the whole project directory just like `counsel-git-grep` does ??

**Comment by abo-abo** [comment]
`counsel-ag` simply forwards to `ag`. If `ag` has this option, you can customize `counsel-ag-base-command` for that.

**Comment by CSRaghunandan** [comment]
I do not know how I can modify `counsel-ag-base-command` to work like this. And, `projectile` has the command `projectile-ag` (which searches at the root directory of  the project instead of current directory), but it'll just output the result in a new buffer and not provide preview of candidates like `counsel-ag` or `swiper` does. So, I was wondering if I could get `counsel-ag` to work like `projectile-ag`.

**Comment by abo-abo** [comment]
Like this:

```elisp
(defun counsel-ag-projectile ()
  (interactive)
  (counsel-ag nil (projectile-project-root)))
```

**Comment by CSRaghunandan** [comment]
That works perfectly :) cheers. 
I need to learn me some elsip so I can write simple functions like these.

And, when should once use `counsel-ag-projectile` vs `counsel-git-grep` ? for projects with a large number of files, which would be better ?

**Comment by abo-abo** [comment]
> And, when should once use counsel-ag-projectile vs counsel-git-grep ? for projects with a large number of files, which would be better ?

`counsel-git-grep` is optimized specifically for huge projects, I test it from time to time on the Linux kernel, and the Emacs code base.

While the `ag` executable may be a bit faster than `git-grep` executable, if you get 100000 matches for a partial query most of the execution time will be spent on piping that string output to Emacs. That's why `counsel-git-grep` pipes only the first 200 results, which makes it very fast. To get more than 200 results, use `ivy-occur`.

**Comment by abo-abo** [comment]
Forgot to mention that although only 200 results are piped, you still get the precise amount of results displayed as well.
