### ISSUE TITLE
Flx not being used for swiper searches

### ISSUE THREAD

**Issue by andresilva** [abo-abo/swiper#718]
Currently `flx` sorting isn't being used for swiper searches. [This](https://github.com/abo-abo/swiper/blob/master/ivy.el#L2452) comparison fails when doing a swiper search since `ivy--regex-function` will be set to `swiper--re-builder`.

**Comment by abo-abo** [comment]
`flx` sorting is disabled on purpose for `swiper`. The condition of earlier lines coming before the later lines must be satisfied.
With your fix in #719 here's an example sequence of line numbers: 1876, 2495, 1834, 95...

**Comment by andrebeat** [comment]
Sorry I didn't know that was the expected behavior. I prefer having `flx` sorting for `swiper` because otherwise with the fuzzy regex a lot of lines match. I also couple this with `(defun ivy-recompute-index-swiper (_re-str cands) 0))` to always have the first candidate selected, so maybe my use case is different from yours.

**Comment by andresilva** [comment]
Closing as stale.
