### ISSUE TITLE
rgrep: Impossible to input file pattern

### ISSUE THREAD

**Issue by rootzlevel** [abo-abo/swiper#72]
rgrep first asks the user for a grep pattern, which works as expected. But then it wants a filename-pattern to limit search to a number of files.

Unfortunately, with ivy-mode enabled, ivy tries to complete this second pattern in filename completion mode, which makes it impossible to enter for example "*.[ch]" to include only .c and .h files

**Comment by abo-abo** [comment]
The `rgrep` interaction is weird because globs can be accepted where normally only file names should be.  So if you use <kbd>C-m</kbd> (`ivy-done`), you'll get this in the expansion and it won't work:

    -iname /home/oleh/git/gnu-emacs/\*.\[ch\]

But if you type in `*.[ch]` and press <kbd>C-u C-j</kbd> (`ivy-alt-done` with a prefix arg), or call `ivy-immediate-done` (currently unbound), you'll get this:

    -iname \*.\[ch\]

which will work properly. <kbd>C-u C-j</kbd> works for any instance of ivy completion: it exits with the current text ignoring the completions.
