### ISSUE TITLE
Headlong functionality (take action when unique match)

### ISSUE THREAD

**Issue by noctuid** [abo-abo/swiper#838]
There are some cases where I think it would be useful to automatically call `ivy-done` when there is only one candidate left. I'd find this useful for some commands where there aren't too many candidates (e.g. `counsel-find-files` from dired; inspired by the ranger file manager's command that will jump to a file or directory as soon as there is a unique match).

The method from your headlong package of overriding `self-insert-command` seems to work (though if I check `ivy--length`, it isn't updated yet). Another feature ranger has is that it will ignore input for a short time afterwards since the user may still be typing to get a unique match. That or waiting for the user to stop typing would also be a nice addition to prevent accidental keypresses.

**Comment by abo-abo** [comment]
I use `headlong` only for bookmarks, since jumping to a bookmark is non-destructive, and `kill-buffer` reverses it.
`ivy-read`, on the other hand, is generic, and I'd rather not have something destructive happen because of a typo, provided <kbd>RET</kbd> was not pressed.

> though if I check ivy--length, it isn't updated yet

`ivy--length` is updated in `ivy--exhibit`, which is attached to `post-command-hook`. You can call it from your command, I think. Calling that function twice shouldn't do anything bad.

You can probably advice `ivy--exhibit` and append code after it: if `ivy--length` is 1, call `ivy-done`. But I think it should be a user config thing.

**Comment by noctuid** [comment]
That makes sense. I wasn't necessarily thinking of adding specific commands as much as something like `headlong-with`, but advising `ivy--exhibit` works and is much simpler. Thank you for the suggestion.
