### ISSUE TITLE
How to let `ivy-partial-or-done' only complete and do not open file or directory? 

### ISSUE THREAD

**Issue by tumashu** [abo-abo/swiper#86]
I want to use TAB to complete directory or file name, but don't open, is it possible?

**Comment by abo-abo** [comment]
Just bind `ivy-partial` like this:

```emacs
(define-key ivy-minibuffer-map (kbd "TAB") 'ivy-partial)
```

**Comment by tumashu** [comment]
Thanks!

**Comment by tumashu** [comment]
I try, but feel confusion, following code seed more comfort

```
(defun eh-ivy-partial-or-done ()
  (interactive)
  (or (ivy-partial)
      (ivy-alt-done)))

(define-key ivy-minibuffer-map (kbd "TAB") 'eh-ivy-partial-or-done)

```

**Comment by tumashu** [comment]
I also find the follow configure is also a comfort tip:

```
(define-key ivy-minibuffer-map (kbd "<return>") 'ivy-alt-done)
```

**Comment by Ergus** [comment]
Hi, sorry for necropumping this thread, but it is very related 

I am trying this:
(define-key ivy-minibuffer-map (kbd "TAB") 'ivy-partial)

and the behaviour is ALMOST what I wanted. BUT the candidates list is not shown if I press tab many times, it requires to press C-j to be shown. Basically I want this to behave like bash or zsh completion because it is more intuitive I think. 
My idea is that pressing tab  I should get a completion if it is unique else the candidates list, and only open a file (or dired maybe) if I press enter or C-j.

What is missing now it the candidates list with the second tab press, because it does nothing. 

I don't want to bother too much, but I don't know if this is the expected behaviour or an issue, maybe it is something I can configure or it requires more complicated work??

Any help please?

**Comment by abo-abo** [comment]
> What is missing now it the candidates list with the second tab press, because it does nothing.

What do you think should happen with the second tab press? The candidates list is already shown and there's nothing further to complete.

If you really see a use case improvement, please open a new issue and describe a detailed scenario of how you think it should work.

**Comment by Ergus** [comment]
What happens to me is  when looking for a file.  The candidates list is not there after a completion and it needs C-j to be shown. 

C-x C-f /ho

![image](https://user-images.githubusercontent.com/6975176/45259490-8c1ac680-b3ce-11e8-8c64-bb43d90c2860.png)

TAB

![image](https://user-images.githubusercontent.com/6975176/45259494-a785d180-b3ce-11e8-9c98-64a571b96476.png)

Now TAB here does nothing.

C-j (This is what I thing the second tab should do)

![image](https://user-images.githubusercontent.com/6975176/45259502-d00dcb80-b3ce-11e8-80b0-2763b54ab3c5.png)

**Comment by Ergus** [comment]
Hi abo-abo:

If the function ivy--directory-done substituting the 2 calls to (ivy-done) with an "alias" function (initialized by default to ivy-done); then we can reassign the alias symbol in the configuration. That option can be configured very easily.  because we can just reassign the alias to nothing and the behaviour  like bash; or to something else for advanced users. 

Does it makes sense?

**Comment by abo-abo** [comment]
@Ergus Please have a look at the change. If there are more changes required, please open a new issue.

**Comment by Ergus** [comment]
Now it is perfect. Than you very much!

**Comment by Moki-19** [comment]
@Ergus @abo-abo , could you please detail the final solution which matches bash completion behavior ?  (I think that last TAB should not perform ENTER actions too)

**Comment by Moki-19** [comment]
@Ergus thanks for your reply. I think I had already tried this configuration. But trying it again, lets me realize that the way I'd like to use completion in Ivy is not exactly the same as bash but a mix between bash and default Ivy behavior : TAB only for completion (after entering a character or navigating with up or down arrows), ENTER only for opening file or directory.

If someone succeeds in configuring a similar behavior in Ivy, please let me know.

In the meantime, I'll give a try to @Ergus configuration, and who knows, maybe even adopt it !
