### ISSUE TITLE
completing-read-multiple behaves as if REQUIRE-MATCH were non-nil

### ISSUE THREAD

**Issue by tarsius** [abo-abo/swiper#907]
When `ivy-mode` is enabled, `completing-read-multiple` always behaves as if its REQUIRE-MATCH argument were non-nil.

**Comment by abo-abo** [comment]
`ivy-mode` does this:

```elisp
(when ivy-do-completion-in-region
  (setq completion-in-region-function 'ivy-completion-in-region))
```

`completing-read-multiple` calls `read-from-minibuffer`. While in the minibuffer, <kbd>TAB</kbd> calls `completion-in-region-function`.

At this point, `require-match` is not passed from anywhere. I set it to `t` since my most common use of <kbd>TAB</kbd> is during `eval-expression`, and `:require-match t` makes sense in that case.

It's easy to change to `require-match nil`, but this results in a loss of convenience during `eval-expression`. Suggestions welcome.

**Comment by tarsius** [comment]
I'll look into it, if you don't come up with something first. But I probably won't get to it soon. Could you please assign this issue to me, so that it shows up in my version of https://github.com/issues/assigned.

**Comment by abo-abo** [comment]
I'm still not sure how `ivy-completion-in-region` should perform if the input did not match any of the candidates.
Since the completion was initiated for the prefix, the prefix is now erased and the new thing is inserted. I wonder if the prefix should be kept.
On the other hand, keeping the prefix is just equivalent to canceling the completion and typing the thing in manually.

**Comment by tarsius** [comment]
I am also quite unsure what the best approach is... Ah, well.
