### ISSUE TITLE
! ! ! breaks ivy--exhibit

### ISSUE THREAD

**Issue by Wilfred** [abo-abo/swiper#976]
Typing "! ! ! " in the minibuffer with `counsel-M-x` produces:

```
Error in post-command-hook (ivy--exhibit): (error "Unexpected: use only one !")
```

This seems to happen with all counsel commands. Once this error has been triggered, ivy stops filtering results until you `C-g` and try again.

I'm using `ivy--regex-ignore-order` in `ivy-re-builders-alist`.

**Comment by abo-abo** [comment]
Thanks, I did some testing to reproduce the bug.

```elisp
(should (equal (ivy--regex-ignore-order "^v f") '(("^v" . t) ("f" . t))))
(should (equal (ivy--regex-ignore-order "^v ! f") '(("^v" . t) ("f"))))
(should (equal (ivy--regex-ignore-order "^v") '(("^v" . t))))
(should (equal (ivy--regex-ignore-order "^v! ") '(("^v" . t))))
```

The last test fails. Could you look into fixing it (if I remember correctly, some of `ivy--regex-ignore-order` code is yours)?

How it's supposed to work: everything after the last `!` are negation groups, separated by spaces. They should not match, e.g. `("f" . nil)` instead of `("f" . t)` as in the test above.

But that means currently that it's impossible to match a literal `!`. My suggestion is to deal with exclamation marks same as with spaces: `!!` translates to a literal `!`, `!!!` to literal `!!` etc.

**Comment by Wilfred** [comment]
Ha, I bumped into this again today when trying to search for literal !. I'll try to write a PR.

How do you feel about using `\!` for a literal `!`? This would be more consistent with regexp special characters.

**Comment by abo-abo** [comment]
That's fine as well.
